using System;
using System.Threading;
using Sussudio.Models;

namespace Sussudio.Services.Capture;

// Health snapshot projection for diagnostics and automation health checks.
// Keep this read-only; lifecycle mutations belong in coordinator/transition paths.
public partial class CaptureService
{
    public CaptureHealthSnapshot GetHealthSnapshot()
    {
        var sink = _libavSink;
        var unifiedVideoCapture = _unifiedVideoCapture;
        var fbSink = _flashbackSink;
        var bufMgr = _flashbackBufferManager;
        var fbPlayback = _flashbackPlaybackController;
        var fatalCleanupInProgress = Volatile.Read(ref _fatalCleanupInProgress) != 0;
        var flashbackCleanupInProgress = Volatile.Read(ref _flashbackCleanupInProgress) != 0;
        var observedTelemetry = ResolveObservedFrameTelemetry();
        var sourceTelemetrySuppressedReason = ResolveSourceTelemetrySuppressedReason(_latestSourceTelemetry);
        var sourceTelemetrySuppressed = !string.IsNullOrWhiteSpace(sourceTelemetrySuppressedReason);
        var sourceCadence = unifiedVideoCapture?.GetSourceCadenceMetrics()
            ?? default(MfSourceReaderVideoCapture.SourceCadenceMetrics);
        var mjpegTimingSnapshot = unifiedVideoCapture?.GetMjpegPipelineTimingSnapshot();
        var mjpegTiming = mjpegTimingSnapshot?.Summary ?? _lastMjpegPipelineTimingMetrics;
        var mjpegFullTiming = mjpegTimingSnapshot?.Details ?? _lastFullMjpegPipelineTimingMetrics;
        var mjpegPreviewJitter = unifiedVideoCapture?.GetMjpegPreviewJitterMetrics()
            ?? default(MjpegPreviewJitterBuffer.Metrics);
        var visualCadence = unifiedVideoCapture?.GetPreviewVisualCadenceMetrics()
            ?? VisualCadenceTracker.Empty;
        var visualCenterCadence = unifiedVideoCapture?.GetPreviewVisualCenterCadenceMetrics()
            ?? VisualCadenceTracker.Empty;
        var mjpegPacketHash = unifiedVideoCapture?.GetMjpegPacketHashMetrics()
            ?? FrameFingerprintCadenceTracker.Empty;
        var (avSyncDriftMs, avSyncDriftRate) = ComputeAvSyncDrift();
        var (avSyncEncoderDriftMs, avSyncEncoderCorrectionSamples) = GetEncoderAvSyncDrift();
        var recordingHealth = CaptureRecordingHealthSnapshotFields(sink, fbSink);
        var flashbackExport = CaptureFlashbackExportHealthSnapshotFields();
        var flashbackBackendSettings = _flashbackBackendSettings;

        var snapshotUtcUnixMs = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        var flashbackExportElapsedMs = ComputeFlashbackExportElapsedMs(
            flashbackExport.Active,
            flashbackExport.StartedUtcUnixMs,
            flashbackExport.CompletedUtcUnixMs,
            snapshotUtcUnixMs);
        var flashbackExportLastProgressAgeMs = ComputeFlashbackExportLastProgressAgeMs(
            flashbackExport.Active,
            flashbackExport.StartedUtcUnixMs,
            flashbackExport.LastProgressUtcUnixMs,
            snapshotUtcUnixMs);
        var flashbackExportOutputBytes = GetFileLengthOrZero(
            !string.IsNullOrWhiteSpace(flashbackExport.OutputPath)
                ? flashbackExport.OutputPath
                : flashbackExport.LastResult?.OutputPath);
        var flashbackExportThroughputBytesPerSec = flashbackExportElapsedMs > 0
            ? flashbackExportOutputBytes / (flashbackExportElapsedMs / 1000.0)
            : 0;
        var flashbackBackendSettingsStaleReason = fbSink == null
            ? string.Empty
            : ResolveFlashbackBackendSettingsStaleReason(flashbackBackendSettings, _currentSettings);
        var flashbackPlayback = CaptureFlashbackPlaybackHealthSnapshotFields(fbPlayback);

        return new CaptureHealthSnapshot
        {
            TimestampUtc = DateTimeOffset.FromUnixTimeMilliseconds(snapshotUtcUnixMs),
            SessionState = _sessionState,
            IsRecording = _isRecording,
            RecordingBackend = ResolveRecordingBackendName(),
            FlashbackActive = fbSink != null,
            FlashbackBufferedDurationMs = (long)(bufMgr?.BufferedDuration.TotalMilliseconds ?? 0),
            FlashbackSegmentCount = bufMgr?.SegmentCount ?? 0,
            FlashbackDiskBytes = bufMgr?.TotalDiskBytes ?? 0,
            FlashbackTotalBytesWritten = bufMgr?.TotalBytesWritten ?? 0,
            FlashbackTempDriveFreeBytes = bufMgr?.TempDriveAvailableFreeBytes ?? 0,
            FlashbackStartupCacheBudgetBytes = bufMgr?.StartupCacheBudgetBytes ?? 0,
            FlashbackStartupCacheBytes = bufMgr?.StartupCacheBytes ?? 0,
            FlashbackStartupCacheSessionCount = bufMgr?.StartupCacheSessionCount ?? 0,
            FlashbackStartupCacheDeletedSessionCount = bufMgr?.StartupCacheDeletedSessionCount ?? 0,
            FlashbackStartupCacheFreedBytes = bufMgr?.StartupCacheFreedBytes ?? 0,
            FlashbackStartupCacheOverBudget = bufMgr?.StartupCacheOverBudget ?? false,
            FlashbackOutputBytes = fbSink?.OutputBytes ?? 0,
            FlashbackFilePath = bufMgr?.ActiveFilePath,
            FlashbackEncodedFrames = fbSink?.EncodedVideoFrames ?? 0,
            FlashbackDroppedFrames = fbSink?.DroppedVideoFrames ?? 0,
            FlashbackGpuEncoding = fbSink?.GpuEncodingEnabled ?? false,
            FlashbackBackendSettingsStale = !string.IsNullOrEmpty(flashbackBackendSettingsStaleReason),
            FlashbackBackendSettingsStaleReason = flashbackBackendSettingsStaleReason,
            FlashbackBackendActiveFormat = flashbackBackendSettings?.Format.ToString() ?? string.Empty,
            FlashbackBackendRequestedFormat = _currentSettings?.Format.ToString() ?? string.Empty,
            FlashbackBackendActivePreset = flashbackBackendSettings?.NvencPreset.ToString() ?? string.Empty,
            FlashbackBackendRequestedPreset = _currentSettings?.NvencPreset.ToString() ?? string.Empty,
            EncoderCodecName = fbSink?.CodecName,
            EncoderTargetBitRate = fbSink?.TargetBitRate ?? 0,
            EncoderWidth = fbSink?.EncoderWidth ?? 0,
            EncoderHeight = fbSink?.EncoderHeight ?? 0,
            EncoderFrameRate = fbSink?.EncoderFrameRate ?? 0,
            EncoderFrameRateNumerator = fbSink?.EncoderFrameRateNumerator,
            EncoderFrameRateDenominator = fbSink?.EncoderFrameRateDenominator,
            FlashbackVideoQueueDepth = fbSink?.VideoQueueCount ?? 0,
            FlashbackAudioQueueDepth = fbSink?.AudioQueueCount ?? 0,
            FlashbackAudioQueueCapacity = fbSink?.AudioQueueCapacityPackets ?? 0,
            FlashbackPlaybackState = flashbackPlayback.State,
            FlashbackPlaybackPositionMs = flashbackPlayback.PositionMs,
            FlashbackDecoderHwAccel = flashbackPlayback.DecoderHwAccel,
            FlashbackPlaybackFrameCount = flashbackPlayback.FrameCount,
            FlashbackPlaybackLateFrames = flashbackPlayback.LateFrames,
            FlashbackPlaybackDroppedFrames = flashbackPlayback.DroppedFrames,
            FlashbackPlaybackAudioMasterDelayDoubles = flashbackPlayback.AudioMasterDelayDoubles,
            FlashbackPlaybackAudioMasterDelayShrinks = flashbackPlayback.AudioMasterDelayShrinks,
            FlashbackPlaybackAudioMasterFallbacks = flashbackPlayback.AudioMasterFallbacks,
            FlashbackPlaybackAudioMasterUnavailableFallbacks = flashbackPlayback.AudioMasterUnavailableFallbacks,
            FlashbackPlaybackAudioMasterStaleFallbacks = flashbackPlayback.AudioMasterStaleFallbacks,
            FlashbackPlaybackAudioMasterDriftOutlierFallbacks = flashbackPlayback.AudioMasterDriftOutlierFallbacks,
            FlashbackPlaybackAudioMasterLastFallbackReason = flashbackPlayback.AudioMasterLastFallbackReason,
            FlashbackPlaybackAudioMasterLastFallbackDriftMs = flashbackPlayback.AudioMasterLastFallbackDriftMs,
            FlashbackPlaybackAudioMasterLastFallbackClockAgeMs = flashbackPlayback.AudioMasterLastFallbackClockAgeMs,
            FlashbackPlaybackSegmentSwitches = flashbackPlayback.SegmentSwitches,
            FlashbackPlaybackFmp4Reopens = flashbackPlayback.Fmp4Reopens,
            FlashbackPlaybackWriteHeadWaits = flashbackPlayback.WriteHeadWaits,
            FlashbackPlaybackNearLiveSnaps = flashbackPlayback.NearLiveSnaps,
            FlashbackPlaybackDecodeErrorSnaps = flashbackPlayback.DecodeErrorSnaps,
            FlashbackPlaybackSubmitFailures = flashbackPlayback.SubmitFailures,
            FlashbackPlaybackLastDropUtcUnixMs = flashbackPlayback.LastDropUtcUnixMs,
            FlashbackPlaybackLastDropReason = flashbackPlayback.LastDropReason,
            FlashbackPlaybackLastSubmitFailureUtcUnixMs = flashbackPlayback.LastSubmitFailureUtcUnixMs,
            FlashbackPlaybackLastSubmitFailure = flashbackPlayback.LastSubmitFailure,
            FlashbackPlaybackLastSegmentSwitchUtcUnixMs = flashbackPlayback.LastSegmentSwitchUtcUnixMs,
            FlashbackPlaybackLastFmp4ReopenUtcUnixMs = flashbackPlayback.LastFmp4ReopenUtcUnixMs,
            FlashbackPlaybackLastWriteHeadWaitGapMs = flashbackPlayback.LastWriteHeadWaitGapMs,
            FlashbackPlaybackTargetFps = flashbackPlayback.TargetFps,
            FlashbackPlaybackObservedFps = flashbackPlayback.ObservedFps,
            FlashbackPlaybackAvgFrameMs = flashbackPlayback.AvgFrameMs,
            FlashbackPlaybackCadenceSampleCount = flashbackPlayback.CadenceSampleCount,
            FlashbackPlaybackP95FrameMs = flashbackPlayback.P95FrameMs,
            FlashbackPlaybackP99FrameMs = flashbackPlayback.P99FrameMs,
            FlashbackPlaybackMaxFrameMs = flashbackPlayback.MaxFrameMs,
            FlashbackPlaybackSlowFrames = flashbackPlayback.SlowFrames,
            FlashbackPlaybackSlowFramePercent = flashbackPlayback.SlowFramePercent,
            FlashbackPlaybackOnePercentLowFps = flashbackPlayback.OnePercentLowFps,
            FlashbackPlaybackFivePercentLowFps = flashbackPlayback.FivePercentLowFps,
            FlashbackPlaybackSampleDurationMs = flashbackPlayback.SampleDurationMs,
            FlashbackPlaybackRecentFrameIntervalsMs = flashbackPlayback.RecentFrameIntervalsMs,
            FlashbackPlaybackPtsCadenceMismatchCount = flashbackPlayback.PtsCadenceMismatchCount,
            FlashbackPlaybackLastPtsCadenceMismatchUtcUnixMs = flashbackPlayback.LastPtsCadenceMismatchUtcUnixMs,
            FlashbackPlaybackLastPtsCadenceDeltaMs = flashbackPlayback.LastPtsCadenceDeltaMs,
            FlashbackPlaybackLastPtsCadenceExpectedMs = flashbackPlayback.LastPtsCadenceExpectedMs,
            FlashbackPlaybackSeekForwardDecodeCapHits = flashbackPlayback.SeekForwardDecodeCapHits,
            FlashbackPlaybackLastSeekHitForwardDecodeCap = flashbackPlayback.LastSeekHitForwardDecodeCap,
            FlashbackPlaybackDecodeSampleCount = flashbackPlayback.DecodeSampleCount,
            FlashbackPlaybackDecodeAvgMs = flashbackPlayback.DecodeAvgMs,
            FlashbackPlaybackDecodeP95Ms = flashbackPlayback.DecodeP95Ms,
            FlashbackPlaybackDecodeP99Ms = flashbackPlayback.DecodeP99Ms,
            FlashbackPlaybackDecodeMaxMs = flashbackPlayback.DecodeMaxMs,
            FlashbackPlaybackMaxDecodePhase = flashbackPlayback.MaxDecodePhase,
            FlashbackPlaybackMaxDecodeReceiveMs = flashbackPlayback.MaxDecodeReceiveMs,
            FlashbackPlaybackMaxDecodeFeedMs = flashbackPlayback.MaxDecodeFeedMs,
            FlashbackPlaybackMaxDecodeReadMs = flashbackPlayback.MaxDecodeReadMs,
            FlashbackPlaybackMaxDecodeSendMs = flashbackPlayback.MaxDecodeSendMs,
            FlashbackPlaybackMaxDecodeAudioMs = flashbackPlayback.MaxDecodeAudioMs,
            FlashbackPlaybackMaxDecodeConvertMs = flashbackPlayback.MaxDecodeConvertMs,
            FlashbackPlaybackMaxDecodeUtcUnixMs = flashbackPlayback.MaxDecodeUtcUnixMs,
            FlashbackPlaybackMaxDecodePositionMs = flashbackPlayback.MaxDecodePositionMs,
            FlashbackAvDriftMs = flashbackPlayback.AvDriftMs,
            FlashbackPlaybackThreadAlive = flashbackPlayback.ThreadAlive,
            FlashbackPlaybackCommandsEnqueued = flashbackPlayback.CommandsEnqueued,
            FlashbackPlaybackCommandsProcessed = flashbackPlayback.CommandsProcessed,
            FlashbackPlaybackCommandsDropped = flashbackPlayback.CommandsDropped,
            FlashbackPlaybackCommandsSkippedNotReady = flashbackPlayback.CommandsSkippedNotReady,
            FlashbackPlaybackScrubUpdatesCoalesced = flashbackPlayback.ScrubUpdatesCoalesced,
            FlashbackPlaybackSeekCommandsCoalesced = flashbackPlayback.SeekCommandsCoalesced,
            FlashbackPlaybackCommandQueueCapacity = flashbackPlayback.CommandQueueCapacity,
            FlashbackPlaybackPendingCommands = flashbackPlayback.PendingCommands,
            FlashbackPlaybackMaxPendingCommands = flashbackPlayback.MaxPendingCommands,
            FlashbackPlaybackLastCommandQueueLatencyMs = flashbackPlayback.LastCommandQueueLatencyMs,
            FlashbackPlaybackMaxCommandQueueLatencyMs = flashbackPlayback.MaxCommandQueueLatencyMs,
            FlashbackPlaybackMaxCommandQueueLatencyCommand = flashbackPlayback.MaxCommandQueueLatencyCommand,
            FlashbackPlaybackLastCommandQueued = flashbackPlayback.LastCommandQueued,
            FlashbackPlaybackLastCommandProcessed = flashbackPlayback.LastCommandProcessed,
            FlashbackPlaybackLastCommandQueuedUtcUnixMs = flashbackPlayback.LastCommandQueuedUtcUnixMs,
            FlashbackPlaybackLastCommandProcessedUtcUnixMs = flashbackPlayback.LastCommandProcessedUtcUnixMs,
            FlashbackPlaybackLastCommandFailureUtcUnixMs = flashbackPlayback.LastCommandFailureUtcUnixMs,
            FlashbackPlaybackLastCommandFailure = flashbackPlayback.LastCommandFailure,
            FlashbackExportActive = flashbackExport.Active,
            FlashbackExportId = flashbackExport.Id,
            FlashbackExportStatus = flashbackExport.Status,
            FlashbackExportOutputPath = flashbackExport.OutputPath,
            FlashbackExportStartedUtcUnixMs = flashbackExport.StartedUtcUnixMs,
            FlashbackExportLastProgressUtcUnixMs = flashbackExport.LastProgressUtcUnixMs,
            FlashbackExportCompletedUtcUnixMs = flashbackExport.CompletedUtcUnixMs,
            FlashbackExportElapsedMs = flashbackExportElapsedMs,
            FlashbackExportLastProgressAgeMs = flashbackExportLastProgressAgeMs,
            FlashbackExportOutputBytes = flashbackExportOutputBytes,
            FlashbackExportThroughputBytesPerSec = flashbackExportThroughputBytesPerSec,
            FlashbackExportSegmentsProcessed = flashbackExport.SegmentsProcessed,
            FlashbackExportTotalSegments = flashbackExport.TotalSegments,
            FlashbackExportPercent = flashbackExport.Percent,
            FlashbackExportInPointMs = flashbackExport.InPointMs,
            FlashbackExportOutPointMs = flashbackExport.OutPointMs,
            FlashbackExportMessage = flashbackExport.Message,
            FlashbackExportFailureKind = flashbackExport.FailureKind,
            FlashbackExportForceRotateFallbacks = flashbackExport.ForceRotateFallbacks,
            FlashbackExportLastForceRotateFallbackUtcUnixMs = flashbackExport.LastForceRotateFallbackUtcUnixMs,
            FlashbackExportLastForceRotateFallbackSegments = flashbackExport.LastForceRotateFallbackSegments,
            FlashbackExportLastForceRotateFallbackInPointMs = flashbackExport.LastForceRotateFallbackInPointMs,
            FlashbackExportLastForceRotateFallbackOutPointMs = flashbackExport.LastForceRotateFallbackOutPointMs,
            // Surface the silent codec/preset substitution alongside the existing
            // export status so automation, the verifier, and (eventually) the UI
            // can show what was actually encoded vs what the user requested.
            FlashbackExportVerificationFormat = ResolveFlashbackExportVerificationFormat(_currentSettings, unifiedVideoCapture),
            FlashbackCodecDowngradeReason = ResolveFlashbackCodecDowngradeReason(_currentSettings, unifiedVideoCapture),
            LastExportId = flashbackExport.LastResultId,
            LastExportPath = flashbackExport.LastResult?.OutputPath,
            LastExportSuccess = flashbackExport.LastResult?.Succeeded,
            LastExportMessage = flashbackExport.LastResult?.StatusMessage,
            RecordingElapsedMs = _isRecording ? _recordingStopwatch.ElapsedMilliseconds : 0,
            ExpectedFrameRate = _actualFrameRate ?? _currentSettings?.FrameRate ?? 0,
            NegotiatedWidth = _actualWidth,
            NegotiatedHeight = _actualHeight,
            NegotiatedFrameRate = _actualFrameRate,
            NegotiatedFrameRateArg = _actualFrameRateArg,
            NegotiatedFrameRateNumerator = _actualFrameRateNumerator,
            NegotiatedFrameRateDenominator = _actualFrameRateDenominator,
            NegotiatedPixelFormat = _actualPixelFormat,
            RequestedReaderSubtype = _currentSettings?.RequestedPixelFormat,
            ReaderSourceStreamType = (_isRecording || _isVideoPreviewActive) && unifiedVideoCapture != null
                ? "MfSourceReader"
                : null,
            ReaderSourceSubtype = _actualPixelFormat,
            FirstObservedFramePixelFormat = observedTelemetry.FirstObservedFramePixelFormat,
            LatestObservedFramePixelFormat = observedTelemetry.LatestObservedFramePixelFormat,
            ObservedP010FrameCount = observedTelemetry.ObservedP010FrameCount,
            ObservedNv12FrameCount = observedTelemetry.ObservedNv12FrameCount,
            ObservedOtherFrameCount = observedTelemetry.ObservedOtherFrameCount,
            SourceTelemetryAvailability = _latestSourceTelemetry.Availability,
            SourceTelemetryOrigin = _latestSourceTelemetry.Origin,
            SourceTelemetryConfidence = _latestSourceTelemetry.Confidence,
            SourceTelemetryOriginDetail = _latestSourceTelemetry.OriginDetail,
            SourceTelemetryDiagnosticSummary = _latestSourceTelemetry.DiagnosticSummary,
            SourceTelemetryTimestampUtc = _latestSourceTelemetry.TimestampUtc,
            SourceWidth = _latestSourceTelemetry.Width,
            SourceHeight = _latestSourceTelemetry.Height,
            SourceFrameRateExact = _latestSourceTelemetry.FrameRateExact,
            SourceFrameRateArg = _latestSourceTelemetry.FrameRateArg,
            SourceIsHdr = _latestSourceTelemetry.IsHdr,
            SourceVideoFormat = _latestSourceTelemetry.VideoFormat,
            SourceColorimetry = _latestSourceTelemetry.Colorimetry,
            SourceQuantization = _latestSourceTelemetry.Quantization,
            SourceHdrTransferFunction = _latestSourceTelemetry.HdrTransferFunction,
            SourceHdrTransferCode = _latestSourceTelemetry.HdrTransferCode,
            SourceFirmware = _latestSourceTelemetry.Firmware,
            SourceAudioFormat = _latestSourceTelemetry.AudioFormat,
            SourceAudioSampleRate = _latestSourceTelemetry.AudioSampleRate,
            SourceInputSource = _latestSourceTelemetry.InputSource,
            SourceUsbHostProtocol = _latestSourceTelemetry.UsbHostProtocol,
            SourceHdcpMode = _latestSourceTelemetry.HdcpMode,
            SourceHdcpVersion = _latestSourceTelemetry.HdcpVersion,
            SourceRxTxHdcpVersion = _latestSourceTelemetry.RxTxHdcpVersion,
            SourceRawTimingHex = _latestSourceTelemetry.RawTimingHex,
            SourceTelemetryDetails = _latestSourceTelemetry.DetailEntries,
            SourceTelemetryBackend = ResolveSourceTelemetryBackend(_latestSourceTelemetry),
            SourceTelemetrySuppressedReason = sourceTelemetrySuppressedReason,
            SourceTelemetrySuppressed = sourceTelemetrySuppressed,
            SourceTelemetryCircuitState = ResolveSourceTelemetryCircuitState(
                _latestSourceTelemetry.Availability,
                sourceTelemetrySuppressed),
            LastFrameArrivalMs = ComputeTickAge(unifiedVideoCapture?.LastVideoFrameArrivedTick ?? 0),
            VideoFramesArrived = unifiedVideoCapture?.VideoFramesArrived ?? 0,
            VideoFramesQueued = recordingHealth.VideoQueueDepth,
            VideoFramesDropped = recordingHealth.DroppedFrames,
            VideoFramesDroppedBacklog = recordingHealth.VideoDropsBacklogEviction,
            VideoFramesConverted = recordingHealth.EncodedVideoFrames,
            VideoDropsQueueSaturated = recordingHealth.VideoDropsQueueSaturated,
            VideoDropsBacklogEviction = recordingHealth.VideoDropsBacklogEviction,
            RecordingEncodingFailed = recordingHealth.EncodingFailed,
            RecordingEncodingFailureType = recordingHealth.FailureType,
            RecordingEncodingFailureMessage = recordingHealth.FailureMessage,
            RecordingVideoQueueCapacity = recordingHealth.VideoQueueCapacity,
            RecordingVideoQueueMaxDepth = recordingHealth.VideoQueueMaxDepth,
            RecordingVideoFramesSubmittedToEncoder = recordingHealth.VideoFramesSubmitted,
            RecordingVideoEncoderPts = recordingHealth.VideoEncoderPts,
            RecordingVideoEncoderPacketsWritten = recordingHealth.VideoEncoderPacketsWritten,
            RecordingVideoEncoderDroppedFrames = recordingHealth.VideoEncoderDroppedFrames,
            RecordingVideoSequenceGaps = recordingHealth.VideoSequenceGaps,
            RecordingVideoQueueOldestFrameAgeMs = recordingHealth.VideoQueueOldestFrameAgeMs,
            RecordingVideoQueueLastLatencyMs = recordingHealth.VideoQueueLastLatencyMs,
            RecordingVideoQueueLatencySampleCount = recordingHealth.VideoQueueLatencyMetrics.SampleCount,
            RecordingVideoQueueLatencyAvgMs = recordingHealth.VideoQueueLatencyMetrics.AverageMs,
            RecordingVideoQueueLatencyP95Ms = recordingHealth.VideoQueueLatencyMetrics.P95Ms,
            RecordingVideoQueueLatencyP99Ms = recordingHealth.VideoQueueLatencyMetrics.P99Ms,
            RecordingVideoQueueLatencyMaxMs = recordingHealth.VideoQueueLatencyMetrics.MaxMs,
            RecordingVideoBackpressureWaitMs = recordingHealth.VideoBackpressureWaitMs,
            RecordingVideoBackpressureEvents = recordingHealth.VideoBackpressureEvents,
            RecordingVideoBackpressureLastWaitMs = recordingHealth.VideoBackpressureLastWaitMs,
            RecordingVideoBackpressureMaxWaitMs = recordingHealth.VideoBackpressureMaxWaitMs,
            RecordingGpuQueueDepth = recordingHealth.GpuQueueDepth,
            RecordingGpuQueueCapacity = recordingHealth.GpuQueueCapacity,
            RecordingGpuQueueMaxDepth = recordingHealth.GpuQueueMaxDepth,
            RecordingGpuFramesEnqueued = recordingHealth.GpuFramesEnqueued,
            RecordingGpuFramesDropped = recordingHealth.GpuFramesDropped,
            RecordingCudaQueueDepth = sink?.CudaQueueCount ?? 0,
            RecordingCudaQueueCapacity = sink?.CudaQueueCapacityFrames ?? 0,
            RecordingCudaQueueMaxDepth = sink?.CudaQueueMaxDepth ?? 0,
            RecordingCudaFramesEnqueued = sink?.CudaFramesEnqueued ?? 0,
            RecordingCudaFramesDropped = sink?.CudaFramesDropped ?? 0,
            FlashbackEncodingFailed = recordingHealth.FlashbackEncodingFailed,
            FlashbackEncodingFailureType = recordingHealth.FlashbackFailureType,
            FlashbackEncodingFailureMessage = recordingHealth.FlashbackFailureMessage,
            FatalCleanupInProgress = fatalCleanupInProgress,
            FlashbackCleanupInProgress = flashbackCleanupInProgress,
            FlashbackForceRotateActive = fbSink?.IsForceRotateActive ?? false,
            FlashbackForceRotateRequested = fbSink?.IsForceRotateRequested ?? false,
            FlashbackForceRotateDraining = fbSink?.IsForceRotateDraining ?? false,
            FlashbackVideoQueueCapacity = fbSink?.VideoQueueCapacityFrames ?? 0,
            FlashbackVideoQueueMaxDepth = fbSink?.VideoQueueMaxDepth ?? 0,
            FlashbackVideoFramesSubmittedToEncoder = fbSink?.VideoFramesSubmittedToEncoder ?? 0,
            FlashbackVideoEncoderPts = fbSink?.VideoEncoderPts ?? 0,
            FlashbackVideoEncoderPacketsWritten = fbSink?.VideoEncoderPacketsWritten ?? 0,
            FlashbackVideoEncoderDroppedFrames = fbSink?.VideoEncoderDroppedFrames ?? 0,
            FlashbackVideoSequenceGaps = fbSink?.VideoSequenceGaps ?? 0,
            FlashbackVideoQueueRejectedFrames = fbSink?.VideoQueueRejectedFrames ?? 0,
            FlashbackVideoQueueLastRejectReason = fbSink?.LastVideoQueueRejectReason ?? string.Empty,
            FlashbackVideoQueueOldestFrameAgeMs = fbSink?.VideoQueueOldestFrameAgeMs ?? 0,
            FlashbackVideoQueueLastLatencyMs = fbSink?.LastVideoQueueLatencyMs ?? 0,
            FlashbackVideoQueueLatencySampleCount = recordingHealth.FlashbackVideoQueueLatencyMetrics.SampleCount,
            FlashbackVideoQueueLatencyAvgMs = recordingHealth.FlashbackVideoQueueLatencyMetrics.AverageMs,
            FlashbackVideoQueueLatencyP95Ms = recordingHealth.FlashbackVideoQueueLatencyMetrics.P95Ms,
            FlashbackVideoQueueLatencyP99Ms = recordingHealth.FlashbackVideoQueueLatencyMetrics.P99Ms,
            FlashbackVideoQueueLatencyMaxMs = recordingHealth.FlashbackVideoQueueLatencyMetrics.MaxMs,
            FlashbackVideoBackpressureWaitMs = fbSink?.VideoBackpressureWaitMs ?? 0,
            FlashbackVideoBackpressureEvents = fbSink?.VideoBackpressureEvents ?? 0,
            FlashbackVideoBackpressureLastWaitMs = fbSink?.LastVideoBackpressureWaitMs ?? 0,
            FlashbackVideoBackpressureMaxWaitMs = fbSink?.MaxVideoBackpressureWaitMs ?? 0,
            FlashbackGpuQueueDepth = fbSink?.GpuQueueCount ?? 0,
            FlashbackGpuQueueCapacity = fbSink?.GpuQueueCapacityFrames ?? 0,
            FlashbackGpuQueueMaxDepth = fbSink?.GpuQueueMaxDepth ?? 0,
            FlashbackGpuFramesEnqueued = fbSink?.GpuFramesEnqueued ?? 0,
            FlashbackGpuFramesDropped = fbSink?.GpuFramesDropped ?? 0,
            FlashbackGpuQueueRejectedFrames = fbSink?.GpuQueueRejectedFrames ?? 0,
            FlashbackGpuQueueLastRejectReason = fbSink?.LastGpuQueueRejectReason ?? string.Empty,
            AudioDropsQueueSaturated = recordingHealth.AudioDropsQueueSaturated,
            AudioDropsBacklogEviction = recordingHealth.AudioDropsBacklogEviction,
            AudioChunksDropped = recordingHealth.AudioDropsQueueSaturated + recordingHealth.AudioDropsBacklogEviction,
            ConversionQueueDepth = 0,
            FfmpegVideoQueueDepth = recordingHealth.VideoQueueDepth,
            FfmpegAudioQueueDepth = recordingHealth.AudioQueueDepth,
            VideoFramesEnqueued = recordingHealth.VideoFramesEnqueued,
            LastVideoEnqueueAgeMs = ComputeTickAge(recordingHealth.LastVideoEnqueueTick),
            LastVideoWriteAgeMs = ComputeTickAge(recordingHealth.LastVideoWriteTick),
            CaptureCadenceSampleCount = sourceCadence.SampleCount,
            CaptureCadenceObservedFps = sourceCadence.ObservedFps,
            CaptureCadenceExpectedIntervalMs = sourceCadence.ExpectedIntervalMs,
            CaptureCadenceAverageIntervalMs = sourceCadence.AverageIntervalMs,
            CaptureCadenceP95IntervalMs = sourceCadence.P95IntervalMs,
            CaptureCadenceP99IntervalMs = sourceCadence.P99IntervalMs,
            CaptureCadenceMaxIntervalMs = sourceCadence.MaxIntervalMs,
            CaptureCadenceOnePercentLowFps = sourceCadence.OnePercentLowFps,
            CaptureCadenceFivePercentLowFps = sourceCadence.FivePercentLowFps,
            CaptureCadenceSampleDurationMs = sourceCadence.SampleDurationMs,
            CaptureCadenceRecentIntervalsMs = sourceCadence.RecentIntervalsMs,
            CaptureCadenceJitterStdDevMs = sourceCadence.JitterStdDevMs,
            CaptureCadenceSevereGapCount = sourceCadence.SevereGapCount,
            CaptureCadenceEstimatedDroppedFrames = sourceCadence.EstimatedDroppedFrames,
            CaptureCadenceEstimatedDropPercent = sourceCadence.EstimatedDropPercent,
            MjpegDecodeSampleCount = mjpegTiming.DecodeSampleCount,
            MjpegDecodeAvgMs = mjpegTiming.DecodeAvgMs,
            MjpegDecodeP95Ms = mjpegTiming.DecodeP95Ms,
            MjpegDecodeMaxMs = mjpegTiming.DecodeMaxMs,
            MjpegInteropCopySampleCount = mjpegTiming.InteropCopySampleCount,
            MjpegInteropCopyAvgMs = mjpegTiming.InteropCopyAvgMs,
            MjpegInteropCopyP95Ms = mjpegTiming.InteropCopyP95Ms,
            MjpegInteropCopyMaxMs = mjpegTiming.InteropCopyMaxMs,
            MjpegCallbackSampleCount = mjpegTiming.CallbackSampleCount,
            MjpegCallbackAvgMs = mjpegTiming.CallbackAvgMs,
            MjpegCallbackP95Ms = mjpegTiming.CallbackP95Ms,
            MjpegCallbackMaxMs = mjpegTiming.CallbackMaxMs,
            MjpegDecoderCount = mjpegFullTiming?.DecoderCount ?? 0,
            MjpegReorderSampleCount = mjpegFullTiming?.ReorderSampleCount ?? 0,
            MjpegReorderAvgMs = mjpegFullTiming?.ReorderAvgMs ?? 0,
            MjpegReorderP95Ms = mjpegFullTiming?.ReorderP95Ms ?? 0,
            MjpegReorderMaxMs = mjpegFullTiming?.ReorderMaxMs ?? 0,
            MjpegPipelineSampleCount = mjpegFullTiming?.PipelineSampleCount ?? 0,
            MjpegPipelineAvgMs = mjpegFullTiming?.PipelineAvgMs ?? 0,
            MjpegPipelineP95Ms = mjpegFullTiming?.PipelineP95Ms ?? 0,
            MjpegPipelineMaxMs = mjpegFullTiming?.PipelineMaxMs ?? 0,
            MjpegTotalDecoded = mjpegFullTiming?.TotalDecoded ?? 0,
            MjpegTotalEmitted = mjpegFullTiming?.TotalEmitted ?? 0,
            MjpegTotalDropped = mjpegFullTiming?.TotalDropped ?? 0,
            MjpegCompressedFramesQueued = mjpegFullTiming?.CompressedFramesQueued ?? 0,
            MjpegCompressedFramesDequeued = mjpegFullTiming?.CompressedFramesDequeued ?? 0,
            MjpegCompressedDropsQueueFull = mjpegFullTiming?.CompressedDropsQueueFull ?? 0,
            MjpegCompressedDropsByteBudget = mjpegFullTiming?.CompressedDropsByteBudget ?? 0,
            MjpegCompressedDropsDisposed = mjpegFullTiming?.CompressedDropsDisposed ?? 0,
            MjpegDecodeFailures = mjpegFullTiming?.DecodeFailures ?? 0,
            MjpegReorderCollisions = mjpegFullTiming?.ReorderCollisions ?? 0,
            MjpegEmitFailures = mjpegFullTiming?.EmitFailures ?? 0,
            MjpegCompressedQueueDepth = mjpegFullTiming?.CompressedQueueDepth ?? 0,
            MjpegCompressedQueueBytes = mjpegFullTiming?.CompressedQueueBytes ?? 0,
            MjpegCompressedQueueByteBudget = mjpegFullTiming?.CompressedQueueByteBudget ?? 0,
            MjpegReorderSkips = mjpegFullTiming?.ReorderSkips ?? 0,
            MjpegReorderBufferDepth = mjpegFullTiming?.ReorderBufferDepth ?? 0,
            MjpegPreviewJitterEnabled = mjpegPreviewJitter.Enabled,
            MjpegPreviewJitterTargetDepth = mjpegPreviewJitter.TargetDepth,
            MjpegPreviewJitterMaxDepth = mjpegPreviewJitter.MaxDepth,
            MjpegPreviewJitterQueueDepth = mjpegPreviewJitter.QueueDepth,
            MjpegPreviewJitterTotalQueued = mjpegPreviewJitter.TotalQueued,
            MjpegPreviewJitterTotalSubmitted = mjpegPreviewJitter.TotalSubmitted,
            MjpegPreviewJitterTotalDropped = mjpegPreviewJitter.TotalDropped,
            MjpegPreviewJitterUnderflowCount = mjpegPreviewJitter.UnderflowCount,
            MjpegPreviewJitterResumeReprimeCount = mjpegPreviewJitter.ResumeReprimeCount,
            MjpegPreviewJitterInputSampleCount = mjpegPreviewJitter.InputIntervalSampleCount,
            MjpegPreviewJitterInputAvgMs = mjpegPreviewJitter.InputIntervalAvgMs,
            MjpegPreviewJitterInputP95Ms = mjpegPreviewJitter.InputIntervalP95Ms,
            MjpegPreviewJitterInputMaxMs = mjpegPreviewJitter.InputIntervalMaxMs,
            MjpegPreviewJitterOutputSampleCount = mjpegPreviewJitter.OutputIntervalSampleCount,
            MjpegPreviewJitterOutputAvgMs = mjpegPreviewJitter.OutputIntervalAvgMs,
            MjpegPreviewJitterOutputP95Ms = mjpegPreviewJitter.OutputIntervalP95Ms,
            MjpegPreviewJitterOutputMaxMs = mjpegPreviewJitter.OutputIntervalMaxMs,
            MjpegPreviewJitterLatencySampleCount = mjpegPreviewJitter.QueueLatencySampleCount,
            MjpegPreviewJitterLatencyAvgMs = mjpegPreviewJitter.QueueLatencyAvgMs,
            MjpegPreviewJitterLatencyP95Ms = mjpegPreviewJitter.QueueLatencyP95Ms,
            MjpegPreviewJitterLatencyMaxMs = mjpegPreviewJitter.QueueLatencyMaxMs,
            MjpegPreviewJitterDeadlineDropCount = mjpegPreviewJitter.DeadlineDropCount,
            MjpegPreviewJitterClearedDropCount = mjpegPreviewJitter.ClearedDropCount,
            MjpegPreviewJitterTargetIncreaseCount = mjpegPreviewJitter.TargetIncreaseCount,
            MjpegPreviewJitterTargetDecreaseCount = mjpegPreviewJitter.TargetDecreaseCount,
            MjpegPreviewJitterLastSelectedPreviewPresentId = mjpegPreviewJitter.LastSelectedPreviewPresentId,
            MjpegPreviewJitterLastSelectedSourceSequenceNumber = mjpegPreviewJitter.LastSelectedSourceSequenceNumber,
            MjpegPreviewJitterLastSelectedQpc = mjpegPreviewJitter.LastSelectedQpc,
            MjpegPreviewJitterLastSelectedSourceLatencyMs = mjpegPreviewJitter.LastSelectedSourceLatencyMs,
            MjpegPreviewJitterLastDroppedSourceSequenceNumber = mjpegPreviewJitter.LastDroppedSourceSequenceNumber,
            MjpegPreviewJitterLastDropQpc = mjpegPreviewJitter.LastDropQpc,
            MjpegPreviewJitterLastDropReason = mjpegPreviewJitter.LastDropReason ?? string.Empty,
            MjpegPreviewJitterLastUnderflowQpc = mjpegPreviewJitter.LastUnderflowQpc,
            MjpegPreviewJitterLastUnderflowReason = mjpegPreviewJitter.LastUnderflowReason ?? string.Empty,
            MjpegPreviewJitterLastUnderflowQueueDepth = mjpegPreviewJitter.LastUnderflowQueueDepth,
            MjpegPreviewJitterLastUnderflowInputAgeMs = mjpegPreviewJitter.LastUnderflowInputAgeMs,
            MjpegPreviewJitterLastUnderflowOutputAgeMs = mjpegPreviewJitter.LastUnderflowOutputAgeMs,
            MjpegPreviewJitterLastScheduleLateMs = mjpegPreviewJitter.LastScheduleLateMs,
            MjpegPreviewJitterMaxScheduleLateMs = mjpegPreviewJitter.MaxScheduleLateMs,
            MjpegPreviewJitterScheduleLateCount = mjpegPreviewJitter.ScheduleLateCount,
            MjpegPacketHashSampleCount = mjpegPacketHash.SampleCount,
            MjpegPacketHashUniqueFrameCount = mjpegPacketHash.UniqueFrameCount,
            MjpegPacketHashDuplicateFrameCount = mjpegPacketHash.DuplicateFrameCount,
            MjpegPacketHashLongestDuplicateRun = mjpegPacketHash.LongestDuplicateRun,
            MjpegPacketHashInputObservedFps = mjpegPacketHash.InputObservedFps,
            MjpegPacketHashUniqueObservedFps = mjpegPacketHash.UniqueObservedFps,
            MjpegPacketHashDuplicateFramePercent = mjpegPacketHash.DuplicateFramePercent,
            MjpegPacketHashLastHash = mjpegPacketHash.LastHash,
            MjpegPacketHashLastFrameDuplicate = mjpegPacketHash.LastFrameDuplicate,
            MjpegPacketHashPattern = mjpegPacketHash.Pattern,
            MjpegPacketHashRecentInputIntervalsMs = mjpegPacketHash.RecentInputIntervalsMs,
            MjpegPacketHashRecentUniqueIntervalsMs = mjpegPacketHash.RecentUniqueIntervalsMs,
            MjpegPacketHashRecentDuplicateFlags = mjpegPacketHash.RecentDuplicateFlags,
            VisualCadenceSampleCount = visualCadence.SampleCount,
            VisualCadenceChangedFrameCount = visualCadence.ChangedFrameCount,
            VisualCadenceRepeatFrameCount = visualCadence.RepeatFrameCount,
            VisualCadenceLongestRepeatRun = visualCadence.LongestRepeatRun,
            VisualCadenceOutputObservedFps = visualCadence.OutputObservedFps,
            VisualCadenceChangeObservedFps = visualCadence.ChangeObservedFps,
            VisualCadenceRepeatFramePercent = visualCadence.RepeatFramePercent,
            VisualCadenceLastDelta = visualCadence.LastDelta,
            VisualCadenceAverageDelta = visualCadence.AverageDelta,
            VisualCadenceP95Delta = visualCadence.P95Delta,
            VisualCadenceMotionScore = visualCadence.MotionScore,
            VisualCadenceMotionConfidence = visualCadence.MotionConfidence,
            VisualCadenceRecentOutputIntervalsMs = visualCadence.RecentOutputIntervalsMs,
            VisualCadenceRecentChangeIntervalsMs = visualCadence.RecentChangeIntervalsMs,
            VisualCenterCadenceSampleCount = visualCenterCadence.SampleCount,
            VisualCenterCadenceChangedFrameCount = visualCenterCadence.ChangedFrameCount,
            VisualCenterCadenceRepeatFrameCount = visualCenterCadence.RepeatFrameCount,
            VisualCenterCadenceLongestRepeatRun = visualCenterCadence.LongestRepeatRun,
            VisualCenterCadenceOutputObservedFps = visualCenterCadence.OutputObservedFps,
            VisualCenterCadenceChangeObservedFps = visualCenterCadence.ChangeObservedFps,
            VisualCenterCadenceRepeatFramePercent = visualCenterCadence.RepeatFramePercent,
            VisualCenterCadenceLastDelta = visualCenterCadence.LastDelta,
            VisualCenterCadenceAverageDelta = visualCenterCadence.AverageDelta,
            VisualCenterCadenceP95Delta = visualCenterCadence.P95Delta,
            VisualCenterCadenceMotionScore = visualCenterCadence.MotionScore,
            VisualCenterCadenceMotionConfidence = visualCenterCadence.MotionConfidence,
            VisualCenterCadenceRecentOutputIntervalsMs = visualCenterCadence.RecentOutputIntervalsMs,
            VisualCenterCadenceRecentChangeIntervalsMs = visualCenterCadence.RecentChangeIntervalsMs,
            MjpegPerDecoder = mjpegFullTiming?.PerDecoder is { Length: > 0 } perDecoder
                ? Array.ConvertAll(
                    perDecoder,
                    worker => new MjpegDecoderHealthSnapshot(
                        worker.WorkerIndex,
                        worker.SampleCount,
                        worker.AvgMs,
                        worker.P95Ms,
                        worker.MaxMs))
                : Array.Empty<MjpegDecoderHealthSnapshot>(),
            AvSyncCaptureDriftMs = avSyncDriftMs,
            AvSyncCaptureDriftRateMsPerSec = avSyncDriftRate,
            AvSyncEncoderDriftMs = avSyncEncoderDriftMs,
            AvSyncEncoderCorrectionSamples = avSyncEncoderCorrectionSamples
        };
    }
}
