using System.Collections.Generic;
using Sussudio.Models;

namespace Sussudio.Tools;

public static partial class AutomationCommandCatalog
{
    private static void RegisterCaptureEntries(Dictionary<AutomationCommandKind, AutomationCommandMetadata> entries)
    {
        Set(entries, AutomationCommandKind.RefreshDevices, "{}", ready: false, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "device refresh", "Refresh capture and audio device lists.");
        Set(entries, AutomationCommandKind.SelectDevice, "{ deviceId?: string, deviceName?: string }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "device select <name>", "Select a capture device.", Optional("deviceId", AutomationPayloadFieldType.String), Optional("deviceName", AutomationPayloadFieldType.String));
        Set(entries, AutomationCommandKind.SelectAudioInputDevice, "{ deviceId?: string, deviceName?: string }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "device audio-select <name>", "Select an audio input device.", Optional("deviceId", AutomationPayloadFieldType.String), Optional("deviceName", AutomationPayloadFieldType.String));
        Set(entries, AutomationCommandKind.SetCustomAudioInput, "{ enabled: bool }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "device custom-audio on|off", "Enable or disable custom audio input.", Required("enabled", AutomationPayloadFieldType.Boolean));
        Set(entries, AutomationCommandKind.SetResolution, "{ resolution: string }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set resolution <value>", "Set capture resolution.", Required("resolution", AutomationPayloadFieldType.String));
        Set(entries, AutomationCommandKind.SetFrameRate, "{ frameRate: double }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set fps <value>", "Set capture frame rate.", Required("frameRate", AutomationPayloadFieldType.Number));
        Set(entries, AutomationCommandKind.SetRecordingFormat, "{ format: string }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set format <value>", "Set recording container and codec format.", Required("format", AutomationPayloadFieldType.String));
        Set(entries, AutomationCommandKind.SetQuality, "{ quality: string }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set quality <value>", "Set recording quality.", Required("quality", AutomationPayloadFieldType.String));
        Set(entries, AutomationCommandKind.SetCustomBitrate, "{ bitrateMbps: double }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set bitrate <value>", "Set custom recording bitrate in Mbps.", Required("bitrateMbps", AutomationPayloadFieldType.Number));
        Set(entries, AutomationCommandKind.SetHdrEnabled, "{ enabled: bool }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set hdr on|off", "Enable or disable HDR recording mode.", Required("enabled", AutomationPayloadFieldType.Boolean));
        Set(entries, AutomationCommandKind.SetAudioEnabled, "{ enabled: bool }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set audio on|off", "Enable or disable audio capture.", Required("enabled", AutomationPayloadFieldType.Boolean));
        Set(entries, AutomationCommandKind.SetAudioPreviewEnabled, "{ enabled: bool }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set audio-preview on|off", "Enable or disable live audio monitoring.", Required("enabled", AutomationPayloadFieldType.Boolean));
        Set(entries, AutomationCommandKind.SetOutputPath, "{ outputPath: string }", ready: false, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.Directory, "set output <path>", "Set recording output directory.", Required("outputPath", AutomationPayloadFieldType.String));
        Set(entries, AutomationCommandKind.SetPreviewEnabled, "{ enabled: bool }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "preview start|stop", "Start or stop live preview.", Required("enabled", AutomationPayloadFieldType.Boolean));
        Set(entries, AutomationCommandKind.SetRecordingEnabled, "{ enabled: bool }", ready: true, timeoutMs: AutomationPipeProtocol.RecordingResponseTimeoutMs, pathPolicy: AutomationCommandPathPolicy.None, "record start|stop", "Start or stop recording.", Required("enabled", AutomationPayloadFieldType.Boolean));
        Set(entries, AutomationCommandKind.SetTrueHdrPreviewEnabled, "{ enabled: bool }", ready: false, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set hdr-preview on|off", "Enable or disable true HDR preview.", Required("enabled", AutomationPayloadFieldType.Boolean));
        Set(entries, AutomationCommandKind.ProbeVideoSource, "{}", ready: false, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "probe source", "Probe live video source formats.");
        Set(entries, AutomationCommandKind.ProbePreviewColor, "{}", ready: false, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "probe color", "Probe preview color metadata.");
        Set(entries, AutomationCommandKind.CapturePreviewFrame, "{ outputPath?: string }", ready: false, timeoutMs: AutomationPipeProtocol.ExtendedResponseTimeoutMs, pathPolicy: AutomationCommandPathPolicy.WriteFile, "frame [path]", "Capture the next preview frame to disk.", Optional("outputPath", AutomationPayloadFieldType.String));
        Set(entries, AutomationCommandKind.CaptureWindowScreenshot, "{ outputPath?: string }", ready: false, timeoutMs: AutomationPipeProtocol.ExtendedResponseTimeoutMs, pathPolicy: AutomationCommandPathPolicy.WriteFile, "screenshot [path]", "Capture the application window to disk.", Optional("outputPath", AutomationPayloadFieldType.String));
        Set(entries, AutomationCommandKind.SetVideoFormat, "{ videoFormat: string }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set video-format <value>", "Set video format override.", Required("videoFormat", AutomationPayloadFieldType.String));
        Set(entries, AutomationCommandKind.GetCaptureOptions, "{}", ready: false, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "options", "Get capture option metadata.");
        Set(entries, AutomationCommandKind.SetPreset, "{ preset: string }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set preset <value>", "Set encoder preset.", Required("preset", AutomationPayloadFieldType.String));
        Set(entries, AutomationCommandKind.SetSplitEncodeMode, "{ splitEncodeMode: string }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set split <value>", "Set split encode mode.", Required("splitEncodeMode", AutomationPayloadFieldType.String));
        Set(entries, AutomationCommandKind.SetMjpegDecoderCount, "{ decoderCount: int }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set decoders <value>", "Set MJPEG decoder count.", Required("decoderCount", AutomationPayloadFieldType.Integer));
        Set(entries, AutomationCommandKind.SetDeviceAudioMode, "{ mode: string }", ready: false, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set audio-mode hdmi|analog", "Set device audio mode.", Required("mode", AutomationPayloadFieldType.String));
        Set(entries, AutomationCommandKind.SetAnalogAudioGain, "{ gain: double }", ready: true, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set gain <value>", "Set analog audio input gain.", Required("gain", AutomationPayloadFieldType.Number));
        Set(entries, AutomationCommandKind.SetMicrophoneEnabled, "{ enabled: bool }", ready: false, timeoutMs: DefaultTimeout, pathPolicy: AutomationCommandPathPolicy.None, "set mic on|off", "Enable or disable microphone recording.", Required("enabled", AutomationPayloadFieldType.Boolean));
    }
}
