using System;
using Sussudio.Models;

namespace Sussudio.Services.Automation;

public sealed partial class AutomationDiagnosticsHub
{
    private static PerformanceTimelineCoreProjection BuildPerformanceTimelineCoreProjection(
        AutomationSnapshot snapshot)
        => new(
            TimestampUtc: snapshot.TimestampUtc,
            CaptureFps: snapshot.CaptureCadenceObservedFps,
            PreviewFps: snapshot.PreviewCadenceObservedFps,
            VideoQueueDepth: snapshot.FfmpegVideoQueueDepth,
            VideoDrops: snapshot.VideoDropsQueueSaturated,
            CaptureCadenceAverageMs: snapshot.CaptureCadenceAverageIntervalMs,
            CaptureCadenceP95Ms: snapshot.CaptureCadenceP95IntervalMs,
            CaptureCadenceP99Ms: snapshot.CaptureCadenceP99IntervalMs,
            CaptureCadenceMaxMs: snapshot.CaptureCadenceMaxIntervalMs,
            CaptureCadenceOnePercentLowFps: snapshot.CaptureCadenceOnePercentLowFps,
            CaptureCadenceFivePercentLowFps: snapshot.CaptureCadenceFivePercentLowFps);

    private static PerformanceTimelineEntry BuildPerformanceTimelineEntry(AutomationSnapshot snapshot)
    {
        var core = BuildPerformanceTimelineCoreProjection(snapshot);
        var preview = BuildPerformanceTimelinePreviewProjection(snapshot);
        var flashbackPlayback = BuildPerformanceTimelineFlashbackPlaybackProjection(snapshot);
        var flashbackExport = BuildPerformanceTimelineFlashbackExportProjection(snapshot);
        var system = BuildPerformanceTimelineSystemProjection(snapshot);

        return new()
        {
            TimestampUtc = core.TimestampUtc,
            CaptureFps = core.CaptureFps,
            PreviewFps = core.PreviewFps,
            VideoQueueDepth = core.VideoQueueDepth,
            VideoDrops = core.VideoDrops,
            CaptureCadenceAverageMs = core.CaptureCadenceAverageMs,
            CaptureCadenceP95Ms = core.CaptureCadenceP95Ms,
            CaptureCadenceP99Ms = core.CaptureCadenceP99Ms,
            CaptureCadenceMaxMs = core.CaptureCadenceMaxMs,
            CaptureCadenceOnePercentLowFps = core.CaptureCadenceOnePercentLowFps,
            CaptureCadenceFivePercentLowFps = core.CaptureCadenceFivePercentLowFps,
            PreviewCadenceAverageMs = preview.CadenceAverageMs,
            PreviewCadenceP95Ms = preview.CadenceP95Ms,
            PreviewCadenceP99Ms = preview.CadenceP99Ms,
            PreviewCadenceMaxMs = preview.CadenceMaxMs,
            PreviewCadenceOnePercentLowFps = preview.CadenceOnePercentLowFps,
            PreviewCadenceFivePercentLowFps = preview.CadenceFivePercentLowFps,
            PreviewCadenceSlowFramePercent = preview.CadenceSlowFramePercent,
            VisualCadenceChangeObservedFps = preview.VisualCadenceChangeObservedFps,
            VisualCadenceRepeatFramePercent = preview.VisualCadenceRepeatFramePercent,
            VisualCadenceMotionConfidence = preview.VisualCadenceMotionConfidence,
            MjpegPacketHashInputObservedFps = preview.MjpegPacketHashInputObservedFps,
            MjpegPacketHashUniqueObservedFps = preview.MjpegPacketHashUniqueObservedFps,
            MjpegPacketHashDuplicateFramePercent = preview.MjpegPacketHashDuplicateFramePercent,
            MjpegPreviewJitterEnabled = preview.MjpegPreviewJitterEnabled,
            MjpegPreviewJitterTargetDepth = preview.MjpegPreviewJitterTargetDepth,
            MjpegPreviewJitterMaxDepth = preview.MjpegPreviewJitterMaxDepth,
            MjpegPreviewJitterQueueDepth = preview.MjpegPreviewJitterQueueDepth,
            MjpegPreviewJitterTotalDropped = preview.MjpegPreviewJitterTotalDropped,
            MjpegPreviewJitterDeadlineDropCount = preview.MjpegPreviewJitterDeadlineDropCount,
            MjpegPreviewJitterClearedDropCount = preview.MjpegPreviewJitterClearedDropCount,
            MjpegPreviewJitterUnderflowCount = preview.MjpegPreviewJitterUnderflowCount,
            MjpegPreviewJitterResumeReprimeCount = preview.MjpegPreviewJitterResumeReprimeCount,
            MjpegPreviewJitterLatencyP95Ms = preview.MjpegPreviewJitterLatencyP95Ms,
            MjpegPreviewJitterLatencyMaxMs = preview.MjpegPreviewJitterLatencyMaxMs,
            MjpegPreviewJitterLastDropReason = preview.MjpegPreviewJitterLastDropReason,
            MjpegPreviewJitterLastUnderflowReason = preview.MjpegPreviewJitterLastUnderflowReason,
            MjpegPreviewJitterLastUnderflowInputAgeMs = preview.MjpegPreviewJitterLastUnderflowInputAgeMs,
            MjpegPreviewJitterLastUnderflowOutputAgeMs = preview.MjpegPreviewJitterLastUnderflowOutputAgeMs,
            MjpegPreviewJitterMaxScheduleLateMs = preview.MjpegPreviewJitterMaxScheduleLateMs,
            MjpegPreviewJitterScheduleLateCount = preview.MjpegPreviewJitterScheduleLateCount,
            PreviewD3DPendingFrameCount = preview.D3DPendingFrameCount,
            PreviewD3DPresentCallP95Ms = preview.D3DPresentCallP95Ms,
            PreviewD3DTotalFrameCpuP95Ms = preview.D3DTotalFrameCpuP95Ms,
            PreviewD3DInputUploadCpuP99Ms = preview.D3DInputUploadCpuP99Ms,
            PreviewD3DRenderSubmitCpuP99Ms = preview.D3DRenderSubmitCpuP99Ms,
            PreviewD3DPresentCallP99Ms = preview.D3DPresentCallP99Ms,
            PreviewD3DTotalFrameCpuP99Ms = preview.D3DTotalFrameCpuP99Ms,
            PreviewD3DPipelineLatencyP95Ms = preview.D3DPipelineLatencyP95Ms,
            PreviewD3DPipelineLatencyP99Ms = preview.D3DPipelineLatencyP99Ms,
            PreviewD3DPipelineLatencyMaxMs = preview.D3DPipelineLatencyMaxMs,
            PreviewD3DFrameLatencyWaitTimeoutCount = preview.D3DFrameLatencyWaitTimeoutCount,
            PreviewD3DFrameLatencyWaitP95Ms = preview.D3DFrameLatencyWaitP95Ms,
            PreviewD3DFrameLatencyWaitMaxMs = preview.D3DFrameLatencyWaitMaxMs,
            PreviewD3DFrameStatsRecentMissedRefreshCount = preview.D3DFrameStatsRecentMissedRefreshCount,
            PreviewD3DFrameStatsRecentFailureCount = preview.D3DFrameStatsRecentFailureCount,
            PreviewD3DLastRenderedSchedulerToPresentMs = preview.D3DLastRenderedSchedulerToPresentMs,
            PreviewD3DLastRenderedPipelineLatencyMs = preview.D3DLastRenderedPipelineLatencyMs,
            PreviewD3DLastDropReason = preview.D3DLastDropReason,
            PreviewPacingLikelySlowStage = preview.PacingLikelySlowStage,
            PreviewPacingSlowStageConfidence = preview.PacingSlowStageConfidence,
            PreviewPacingSlowStageEvidence = preview.PacingSlowStageEvidence,
            FlashbackPlaybackState = flashbackPlayback.State,
            FlashbackPlaybackTargetFps = flashbackPlayback.TargetFps,
            FlashbackPlaybackObservedFps = flashbackPlayback.ObservedFps,
            FlashbackPlaybackP99FrameMs = flashbackPlayback.P99FrameMs,
            FlashbackPlaybackMaxFrameMs = flashbackPlayback.MaxFrameMs,
            FlashbackPlaybackOnePercentLowFps = flashbackPlayback.OnePercentLowFps,
            FlashbackPlaybackFivePercentLowFps = flashbackPlayback.FivePercentLowFps,
            FlashbackPlaybackSlowFramePercent = flashbackPlayback.SlowFramePercent,
            FlashbackPlaybackDecodeP99Ms = flashbackPlayback.DecodeP99Ms,
            FlashbackPlaybackDecodeMaxMs = flashbackPlayback.DecodeMaxMs,
            FlashbackPlaybackMaxDecodePhase = flashbackPlayback.MaxDecodePhase,
            FlashbackPlaybackMaxDecodeReceiveMs = flashbackPlayback.MaxDecodeReceiveMs,
            FlashbackPlaybackMaxDecodeFeedMs = flashbackPlayback.MaxDecodeFeedMs,
            FlashbackPlaybackMaxDecodeReadMs = flashbackPlayback.MaxDecodeReadMs,
            FlashbackPlaybackMaxDecodeSendMs = flashbackPlayback.MaxDecodeSendMs,
            FlashbackPlaybackMaxDecodeAudioMs = flashbackPlayback.MaxDecodeAudioMs,
            FlashbackPlaybackMaxDecodeConvertMs = flashbackPlayback.MaxDecodeConvertMs,
            FlashbackPlaybackMaxDecodeUtcUnixMs = flashbackPlayback.MaxDecodeUtcUnixMs,
            FlashbackPlaybackMaxDecodePositionMs = flashbackPlayback.MaxDecodePositionMs,
            FlashbackPlaybackSeekForwardDecodeCapHits = flashbackPlayback.SeekForwardDecodeCapHits,
            FlashbackPlaybackLastSeekHitForwardDecodeCap = flashbackPlayback.LastSeekHitForwardDecodeCap,
            FlashbackPlaybackPendingCommands = flashbackPlayback.PendingCommands,
            FlashbackPlaybackMaxPendingCommands = flashbackPlayback.MaxPendingCommands,
            FlashbackPlaybackCommandsEnqueued = flashbackPlayback.CommandsEnqueued,
            FlashbackPlaybackCommandsProcessed = flashbackPlayback.CommandsProcessed,
            FlashbackPlaybackCommandsDropped = flashbackPlayback.CommandsDropped,
            FlashbackPlaybackCommandsSkippedNotReady = flashbackPlayback.CommandsSkippedNotReady,
            FlashbackPlaybackScrubUpdatesCoalesced = flashbackPlayback.ScrubUpdatesCoalesced,
            FlashbackPlaybackSeekCommandsCoalesced = flashbackPlayback.SeekCommandsCoalesced,
            FlashbackPlaybackLastCommandQueued = flashbackPlayback.LastCommandQueued,
            FlashbackPlaybackLastCommandProcessed = flashbackPlayback.LastCommandProcessed,
            FlashbackPlaybackMaxCommandQueueLatencyMs = flashbackPlayback.MaxCommandQueueLatencyMs,
            FlashbackPlaybackMaxCommandQueueLatencyCommand = flashbackPlayback.MaxCommandQueueLatencyCommand,
            FlashbackPlaybackSubmitFailures = flashbackPlayback.SubmitFailures,
            FlashbackPlaybackLastDropUtcUnixMs = flashbackPlayback.LastDropUtcUnixMs,
            FlashbackPlaybackLastDropReason = flashbackPlayback.LastDropReason,
            FlashbackPlaybackLastSubmitFailureUtcUnixMs = flashbackPlayback.LastSubmitFailureUtcUnixMs,
            FlashbackPlaybackLastSubmitFailure = flashbackPlayback.LastSubmitFailure,
            FlashbackPlaybackDroppedFrames = flashbackPlayback.DroppedFrames,
            FlashbackPlaybackAudioMasterDelayDoubles = flashbackPlayback.AudioMasterDelayDoubles,
            FlashbackPlaybackAudioMasterDelayShrinks = flashbackPlayback.AudioMasterDelayShrinks,
            FlashbackPlaybackAudioMasterFallbacks = flashbackPlayback.AudioMasterFallbacks,
            FlashbackPlaybackAudioMasterUnavailableFallbacks = flashbackPlayback.AudioMasterUnavailableFallbacks,
            FlashbackPlaybackAudioMasterStaleFallbacks = flashbackPlayback.AudioMasterStaleFallbacks,
            FlashbackPlaybackAudioMasterDriftOutlierFallbacks = flashbackPlayback.AudioMasterDriftOutlierFallbacks,
            FlashbackPlaybackAudioMasterLastFallbackReason = flashbackPlayback.AudioMasterLastFallbackReason,
            FlashbackPlaybackAudioMasterLastFallbackClockAgeMs = flashbackPlayback.AudioMasterLastFallbackClockAgeMs,
            FlashbackPlaybackSegmentSwitches = flashbackPlayback.SegmentSwitches,
            FlashbackPlaybackFmp4Reopens = flashbackPlayback.Fmp4Reopens,
            FlashbackPlaybackWriteHeadWaits = flashbackPlayback.WriteHeadWaits,
            FlashbackPlaybackNearLiveSnaps = flashbackPlayback.NearLiveSnaps,
            FlashbackPlaybackDecodeErrorSnaps = flashbackPlayback.DecodeErrorSnaps,
            FlashbackPlaybackLastWriteHeadWaitGapMs = flashbackPlayback.LastWriteHeadWaitGapMs,
            FlashbackPlaybackLastCommandFailureUtcUnixMs = flashbackPlayback.LastCommandFailureUtcUnixMs,
            FlashbackPlaybackLastCommandFailure = flashbackPlayback.LastCommandFailure,
            FlashbackBackendSettingsStale = flashbackPlayback.BackendSettingsStale,
            FlashbackBackendSettingsStaleReason = flashbackPlayback.BackendSettingsStaleReason,
            FlashbackBackendActiveFormat = flashbackPlayback.BackendActiveFormat,
            FlashbackBackendRequestedFormat = flashbackPlayback.BackendRequestedFormat,
            FlashbackBackendActivePreset = flashbackPlayback.BackendActivePreset,
            FlashbackBackendRequestedPreset = flashbackPlayback.BackendRequestedPreset,
            FlashbackVideoQueueRejectedFrames = flashbackPlayback.VideoQueueRejectedFrames,
            FlashbackVideoQueueLastRejectReason = flashbackPlayback.VideoQueueLastRejectReason,
            FlashbackGpuQueueRejectedFrames = flashbackPlayback.GpuQueueRejectedFrames,
            FlashbackGpuQueueLastRejectReason = flashbackPlayback.GpuQueueLastRejectReason,
            FatalCleanupInProgress = flashbackPlayback.FatalCleanupInProgress,
            FlashbackCleanupInProgress = flashbackPlayback.CleanupInProgress,
            FlashbackForceRotateRequested = flashbackPlayback.ForceRotateRequested,
            FlashbackForceRotateDraining = flashbackPlayback.ForceRotateDraining,
            FlashbackExportActive = flashbackExport.Active,
            FlashbackExportStatus = flashbackExport.Status,
            FlashbackExportFailureKind = flashbackExport.FailureKind,
            FlashbackExportElapsedMs = flashbackExport.ElapsedMs,
            FlashbackExportLastProgressAgeMs = flashbackExport.LastProgressAgeMs,
            FlashbackExportOutputBytes = flashbackExport.OutputBytes,
            FlashbackExportThroughputBytesPerSec = flashbackExport.ThroughputBytesPerSec,
            FlashbackExportSegmentsProcessed = flashbackExport.SegmentsProcessed,
            FlashbackExportTotalSegments = flashbackExport.TotalSegments,
            FlashbackExportPercent = flashbackExport.Percent,
            FlashbackExportInPointMs = flashbackExport.InPointMs,
            FlashbackExportOutPointMs = flashbackExport.OutPointMs,
            FlashbackExportMessage = flashbackExport.Message,
            FlashbackExportForceRotateFallbacks = flashbackExport.ForceRotateFallbacks,
            FlashbackExportLastForceRotateFallbackUtcUnixMs = flashbackExport.LastForceRotateFallbackUtcUnixMs,
            FlashbackExportLastForceRotateFallbackSegments = flashbackExport.LastForceRotateFallbackSegments,
            FlashbackExportLastForceRotateFallbackInPointMs = flashbackExport.LastForceRotateFallbackInPointMs,
            FlashbackExportLastForceRotateFallbackOutPointMs = flashbackExport.LastForceRotateFallbackOutPointMs,
            PipelineLatencyMs = system.PipelineLatencyMs,
            ProcessCpuPercent = system.ProcessCpuPercent,
            MemoryWorkingSetMb = system.MemoryWorkingSetMb,
            MemoryManagedHeapMb = system.MemoryManagedHeapMb,
            GcGen0Collections = system.GcGen0Collections,
            GcGen1Collections = system.GcGen1Collections,
            GcGen2Collections = system.GcGen2Collections,
            GcPauseTimePercent = system.GcPauseTimePercent,
            ThreadPoolWorkerAvailable = system.ThreadPoolWorkerAvailable,
            ThreadPoolIoAvailable = system.ThreadPoolIoAvailable
        };
    }

    private readonly record struct PerformanceTimelineCoreProjection(
        DateTimeOffset TimestampUtc,
        double CaptureFps,
        double PreviewFps,
        int VideoQueueDepth,
        long VideoDrops,
        double CaptureCadenceAverageMs,
        double CaptureCadenceP95Ms,
        double CaptureCadenceP99Ms,
        double CaptureCadenceMaxMs,
        double CaptureCadenceOnePercentLowFps,
        double CaptureCadenceFivePercentLowFps);

    private static PerformanceTimelineFlashbackExportProjection BuildPerformanceTimelineFlashbackExportProjection(
        AutomationSnapshot snapshot)
        => new(
            Active: snapshot.FlashbackExportActive,
            Status: snapshot.FlashbackExportStatus,
            FailureKind: snapshot.FlashbackExportFailureKind,
            ElapsedMs: snapshot.FlashbackExportElapsedMs,
            LastProgressAgeMs: snapshot.FlashbackExportLastProgressAgeMs,
            OutputBytes: snapshot.FlashbackExportOutputBytes,
            ThroughputBytesPerSec: snapshot.FlashbackExportThroughputBytesPerSec,
            SegmentsProcessed: snapshot.FlashbackExportSegmentsProcessed,
            TotalSegments: snapshot.FlashbackExportTotalSegments,
            Percent: snapshot.FlashbackExportPercent,
            InPointMs: snapshot.FlashbackExportInPointMs,
            OutPointMs: snapshot.FlashbackExportOutPointMs,
            Message: snapshot.FlashbackExportMessage,
            ForceRotateFallbacks: snapshot.FlashbackExportForceRotateFallbacks,
            LastForceRotateFallbackUtcUnixMs: snapshot.FlashbackExportLastForceRotateFallbackUtcUnixMs,
            LastForceRotateFallbackSegments: snapshot.FlashbackExportLastForceRotateFallbackSegments,
            LastForceRotateFallbackInPointMs: snapshot.FlashbackExportLastForceRotateFallbackInPointMs,
            LastForceRotateFallbackOutPointMs: snapshot.FlashbackExportLastForceRotateFallbackOutPointMs);

    private readonly record struct PerformanceTimelineFlashbackExportProjection(
        bool Active,
        string Status,
        string FailureKind,
        long ElapsedMs,
        long LastProgressAgeMs,
        long OutputBytes,
        double ThroughputBytesPerSec,
        int SegmentsProcessed,
        int TotalSegments,
        double Percent,
        long InPointMs,
        long OutPointMs,
        string Message,
        long ForceRotateFallbacks,
        long LastForceRotateFallbackUtcUnixMs,
        int LastForceRotateFallbackSegments,
        long LastForceRotateFallbackInPointMs,
        long LastForceRotateFallbackOutPointMs);

    private static PerformanceTimelineSystemProjection BuildPerformanceTimelineSystemProjection(
        AutomationSnapshot snapshot)
        => new(
            PipelineLatencyMs: snapshot.EstimatedPipelineLatencyMs,
            ProcessCpuPercent: snapshot.ProcessCpuPercent,
            MemoryWorkingSetMb: snapshot.MemoryWorkingSetMb,
            MemoryManagedHeapMb: snapshot.MemoryManagedHeapMb,
            GcGen0Collections: snapshot.MemoryGcGen0Collections,
            GcGen1Collections: snapshot.MemoryGcGen1Collections,
            GcGen2Collections: snapshot.MemoryGcGen2Collections,
            GcPauseTimePercent: snapshot.MemoryGcPauseTimePercent,
            ThreadPoolWorkerAvailable: snapshot.ThreadPoolWorkerAvailable,
            ThreadPoolIoAvailable: snapshot.ThreadPoolIoAvailable);

    private readonly record struct PerformanceTimelineSystemProjection(
        long PipelineLatencyMs,
        double ProcessCpuPercent,
        double MemoryWorkingSetMb,
        double MemoryManagedHeapMb,
        int GcGen0Collections,
        int GcGen1Collections,
        int GcGen2Collections,
        double GcPauseTimePercent,
        int ThreadPoolWorkerAvailable,
        int ThreadPoolIoAvailable);
}
