using System.Text;
using System.Text.Json;
using Sussudio.Tools;

namespace Sussudio.Tools.Ssctl;

internal static partial class Formatters
{
    private static void AppendSnapshotFlashbackPlaybackStatusSection(StringBuilder builder, JsonElement snapshot)
    {
        builder.AppendLine($"Playback: {AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackState")} | Pos: {AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackPositionMs")}ms | Decoder: {AutomationSnapshotFormatter.Get(snapshot, "FlashbackDecoderHwAccel")}");
        builder.AppendLine($"Playback Commands: pending={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackPendingCommands")}/{AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackCommandQueueCapacity")} maxPending={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackMaxPendingCommands")} lastLatency={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackLastCommandQueueLatencyMs")}ms maxLatency={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackMaxCommandQueueLatencyMs")}ms maxLatencyCommand={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackMaxCommandQueueLatencyCommand")} enq={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackCommandsEnqueued")} proc={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackCommandsProcessed")} drop={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackCommandsDropped")} skip={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackCommandsSkippedNotReady")} coalescedScrub={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackScrubUpdatesCoalesced")} coalescedSeek={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackSeekCommandsCoalesced")} threadAlive={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackThreadAlive")} lastQueued={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackLastCommandQueued")} lastProcessed={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackLastCommandProcessed")} failure={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackLastCommandFailure", "")} failureUtc={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackLastCommandFailureUtcUnixMs")}");
    }

    private static void AppendSnapshotFlashbackPlaybackMetricsSection(StringBuilder builder, JsonElement snapshot)
    {
        var pbFps = AutomationSnapshotFormatter.GetDouble(snapshot, "FlashbackPlaybackObservedFps");
        var pbAvgMs = AutomationSnapshotFormatter.GetDouble(snapshot, "FlashbackPlaybackAvgFrameMs");
        var avDrift = AutomationSnapshotFormatter.GetDouble(snapshot, "FlashbackAvDriftMs");
        builder.AppendLine($"Playback Frame Time: avg={AutomationSnapshotFormatter.FormatNumber(pbAvgMs, "F2")}ms P95={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackP95FrameMs")}ms P99={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackP99FrameMs")}ms max={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackMaxFrameMs")}ms | Average Rate: {AutomationSnapshotFormatter.FormatNumber(pbFps, "F1")} fps | Target: {AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackTargetFps")} fps | 5% Low: {AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackFivePercentLowFps")} fps | 1% Low: {AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackOnePercentLowFps")} fps | Samples: {AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackCadenceSampleCount")} over {AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackSampleDurationMs")}ms");
        builder.AppendLine($"Playback Decode: avg={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackDecodeAvgMs")}ms P95={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackDecodeP95Ms")}ms P99={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackDecodeP99Ms")}ms max={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackDecodeMaxMs")}ms phase={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackMaxDecodePhase", "")} receive={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackMaxDecodeReceiveMs")}ms feed={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackMaxDecodeFeedMs")}ms read={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackMaxDecodeReadMs")}ms send={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackMaxDecodeSendMs")}ms audio={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackMaxDecodeAudioMs")}ms convert={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackMaxDecodeConvertMs")}ms maxPos={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackMaxDecodePositionMs")}ms samples={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackDecodeSampleCount")} seekCapHits={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackSeekForwardDecodeCapHits")} lastSeekCap={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackLastSeekHitForwardDecodeCap")}");
        builder.AppendLine($"Playback Frames: total={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackFrameCount")} late={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackLateFrames")} slow={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackSlowFrames")} ({AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackSlowFramePercent")}%) dropped={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackDroppedFrames")} audioMasterDouble={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackAudioMasterDelayDoubles")} audioMasterShrink={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackAudioMasterDelayShrinks")} audioMasterFallback={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackAudioMasterFallbacks")} unavailable={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackAudioMasterUnavailableFallbacks")} stale={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackAudioMasterStaleFallbacks")} driftOutlier={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackAudioMasterDriftOutlierFallbacks")} lastAudioFallback={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackAudioMasterLastFallbackReason", "")}/{AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackAudioMasterLastFallbackClockAgeMs")}ms lastDrop={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackLastDropReason", "")} lastDropUtc={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackLastDropUtcUnixMs")} submitFailures={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackSubmitFailures")} lastSubmitFailure={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackLastSubmitFailure", "")} lastSubmitFailureUtc={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackLastSubmitFailureUtcUnixMs")}");
        builder.AppendLine($"Playback Stages: switches={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackSegmentSwitches")} fmp4Reopens={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackFmp4Reopens")} writeHeadWaits={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackWriteHeadWaits")} nearLiveSnaps={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackNearLiveSnaps")} decodeErrorSnaps={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackDecodeErrorSnaps")} lastWriteHeadGap={AutomationSnapshotFormatter.Get(snapshot, "FlashbackPlaybackLastWriteHeadWaitGapMs")}ms");
        builder.AppendLine($"A/V Drift: {AutomationSnapshotFormatter.FormatNumber(avDrift, "+0.0;-0.0;0.0")}ms (+ = audio ahead) | Audio buffered={AutomationSnapshotFormatter.Get(snapshot, "WasapiPlaybackBufferedDurationMs")}ms queue={AutomationSnapshotFormatter.Get(snapshot, "WasapiPlaybackQueueDurationMs")}ms active={AutomationSnapshotFormatter.Get(snapshot, "WasapiPlaybackActiveChunkDurationMs")}ms endpoint={AutomationSnapshotFormatter.Get(snapshot, "WasapiPlaybackEndpointQueuedDurationMs")}ms streamLatency={AutomationSnapshotFormatter.Get(snapshot, "WasapiPlaybackStreamLatencyMs")}ms | File: {AutomationSnapshotFormatter.Get(snapshot, "FlashbackFilePath")}");
    }
}
