using System.Threading.Tasks;

static partial class Program
{
    internal static Task AutomationSnapshotFormatter_SourceOwnership_IsSplit()
    {
        var sharedFormatterSource = global::Sussudio.Tests.RuntimeContractSource.ReadAutomationSnapshotFormatterSource();
        var sharedFormatterRootSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.cs");
        var sharedFormatterCoreSectionsSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.CoreSections.cs");
        var sharedFormatterAudioSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Audio.cs");
        var sharedFormatterRecordingSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Recording.cs");
        var sharedFormatterProcessResourcesSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.ProcessResources.cs");
        var sharedFormatterCaptureSettingsSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.CaptureSettings.cs");
        var sharedFormatterVideoPipelineSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.VideoPipeline.cs");
        var sharedFormatterDiagnosticsSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Diagnostics.cs");
        var sharedFormatterCaptureCadenceSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.CaptureCadence.cs");
        var sharedFormatterAvSyncSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.AvSync.cs");
        var sharedFormatterSourceSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Source.cs");
        var sharedFormatterValuesSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Values.cs");
        var sharedFormatterDisplayValuesSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.DisplayValues.cs");
        var sharedFormatterFlashbackSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Flashback.cs");
        var sharedFormatterFlashbackEncodingSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Flashback.Encoding.cs");
        var sharedFormatterFlashbackEncodingStatusSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Flashback.Encoding.Status.cs");
        var sharedFormatterFlashbackEncodingHealthSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Flashback.Encoding.Health.cs");
        var sharedFormatterFlashbackExportSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Flashback.Export.cs");
        var sharedFormatterFlashbackPlaybackCommandsSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Flashback.Playback.Commands.cs");
        var sharedFormatterFlashbackPlaybackPerformanceSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Flashback.Playback.Performance.cs");
        var sharedFormatterMjpegTimingSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.MjpegTiming.cs");
        var sharedFormatterMjpegPreviewJitterSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.MjpegTiming.PreviewJitter.cs");
        var sharedFormatterPreviewSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.Preview.cs");
        var sharedFormatterPreviewD3DSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.PreviewD3D.cs");
        var sharedFormatterPreviewD3DTimingSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.PreviewD3D.Timing.cs");
        var sharedFormatterPreviewD3DFrameFlowSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.PreviewD3D.FrameFlow.cs");
        var sharedFormatterPreviewD3DSlowFramesSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.PreviewD3D.SlowFrames.cs");
        var sharedFormatterThreadHealthSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.ThreadHealth.cs");
        var sharedFormatterThreadHealthSourceReaderSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.ThreadHealth.SourceReader.cs");
        var sharedFormatterThreadHealthWasapiCaptureSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.ThreadHealth.WasapiCapture.cs");
        var sharedFormatterThreadHealthWasapiPlaybackSource = ReadRepoFile("tools/Common/AutomationSnapshotFormatter.ThreadHealth.WasapiPlayback.cs");
        AssertContains(sharedFormatterRootSource, "AppendStateSection(builder, snapshot);");
        AssertContains(sharedFormatterRootSource, "AppendCaptureSettingsSection(builder, snapshot);");
        AssertContains(sharedFormatterRootSource, "AppendAudioSection(builder, snapshot);");
        AssertContains(sharedFormatterRootSource, "AppendVideoPipelineSection(builder, snapshot);");
        AssertContains(sharedFormatterRootSource, "AppendRecordingSection(builder, snapshot);");
        AssertContains(sharedFormatterRootSource, "AppendFlashbackSection(builder, snapshot);");
        AssertContains(sharedFormatterRootSource, "AppendDiagnosticsSection(builder, snapshot);");
        AssertContains(sharedFormatterRootSource, "AppendPerformanceSection(builder, snapshot);");
        AssertContains(sharedFormatterRootSource, "AppendMemorySection(builder, snapshot);");
        AssertContains(sharedFormatterRootSource, "AppendCaptureCadenceSection(builder, snapshot);");
        AssertDoesNotContain(sharedFormatterRootSource, "builder.AppendLine(\"== Sussudio State ==\");");
        AssertDoesNotContain(sharedFormatterRootSource, "var selectedFriendlyFrameRate = Get(snapshot, \"SelectedFriendlyFrameRate\", string.Empty);");
        AssertDoesNotContain(sharedFormatterRootSource, "builder.AppendLine(\"== Audio ==\");");
        AssertDoesNotContain(sharedFormatterRootSource, "builder.AppendLine(\"== Video Pipeline ==\");");
        AssertDoesNotContain(sharedFormatterRootSource, "builder.AppendLine(\"== Recording ==\");");
        AssertDoesNotContain(sharedFormatterRootSource, "builder.AppendLine(\"== Diagnostics ==\");");
        AssertDoesNotContain(sharedFormatterRootSource, "builder.AppendLine(\"== Performance ==\");");
        AssertDoesNotContain(sharedFormatterRootSource, "builder.AppendLine(\"== Memory & GC ==\");");
        AssertDoesNotContain(sharedFormatterRootSource, "builder.AppendLine(\"== Capture Cadence ==\");");
        AssertDoesNotContain(sharedFormatterRootSource, "RecordingIntegrityStatus");
        AssertDoesNotContain(sharedFormatterRootSource, "ProcessCpuPercent");
        AssertContains(sharedFormatterCoreSectionsSource, "private static void AppendStateSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterCoreSectionsSource, "builder.AppendLine(\"== Sussudio State ==\");");
        AssertContains(sharedFormatterCoreSectionsSource, "CaptureCommandLastCorrelationId");
        AssertContains(sharedFormatterCaptureSettingsSource, "private static void AppendCaptureSettingsSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterCaptureSettingsSource, "private static string FormatFrameRateSummary(JsonElement snapshot)");
        AssertContains(sharedFormatterCaptureSettingsSource, "SelectedFriendlyFrameRate");
        AssertDoesNotContain(sharedFormatterCoreSectionsSource, "private static void AppendAudioSection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(sharedFormatterCoreSectionsSource, "AudioFramesWrittenToSink");
        AssertContains(sharedFormatterAudioSource, "private static void AppendAudioSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterAudioSource, "builder.AppendLine(\"== Audio ==\");");
        AssertContains(sharedFormatterAudioSource, "AudioFramesWrittenToSink");
        AssertContains(sharedFormatterVideoPipelineSource, "private static void AppendVideoPipelineSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterVideoPipelineSource, "builder.AppendLine(\"== Video Pipeline ==\");");
        AssertContains(sharedFormatterVideoPipelineSource, "RecordingVideoQueueLatencyP99Ms");
        AssertContains(sharedFormatterVideoPipelineSource, "AppendThreadHealthSection(builder, snapshot);");
        AssertDoesNotContain(sharedFormatterCoreSectionsSource, "private static void AppendRecordingSection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(sharedFormatterCoreSectionsSource, "RecordingIntegrityStatus");
        AssertContains(sharedFormatterRecordingSource, "private static void AppendRecordingSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterRecordingSource, "builder.AppendLine(\"== Recording ==\");");
        AssertContains(sharedFormatterRecordingSource, "RecordingIntegrityStatus");
        AssertContains(sharedFormatterDiagnosticsSource, "private static void AppendDiagnosticsSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterDiagnosticsSource, "builder.AppendLine(\"== Diagnostics ==\");");
        AssertContains(sharedFormatterDiagnosticsSource, "DiagnosticEvidence");
        AssertDoesNotContain(sharedFormatterCoreSectionsSource, "private static void AppendPerformanceSection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(sharedFormatterCoreSectionsSource, "private static void AppendMemorySection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(sharedFormatterCoreSectionsSource, "ProcessCpuPercent");
        AssertContains(sharedFormatterProcessResourcesSource, "private static void AppendPerformanceSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterProcessResourcesSource, "Pipeline Latency: {Get(snapshot, \"EstimatedPipelineLatencyMs\")}ms (app receive -> estimated visible)");
        AssertContains(sharedFormatterProcessResourcesSource, "private static void AppendMemorySection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterProcessResourcesSource, "ProcessCpuPercent");
        AssertContains(sharedFormatterProcessResourcesSource, "ThreadPoolWorkerAvailable");
        AssertContains(sharedFormatterCaptureCadenceSource, "private static void AppendCaptureCadenceSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterCaptureCadenceSource, "FormatFrameBudgetMs(snapshot, \"ExpectedCaptureFrameRate\")");
        AssertContains(sharedFormatterCaptureCadenceSource, "MjpegPacketHashInputObservedFps");
        AssertContains(sharedFormatterCaptureCadenceSource, "AppendMjpegTimingSection(builder, snapshot);");
        AssertContains(sharedFormatterCaptureCadenceSource, "AppendAvSyncSection(builder, snapshot);");
        AssertContains(sharedFormatterCaptureCadenceSource, "AppendPreviewSection(builder, snapshot);");
        AssertContains(sharedFormatterCaptureCadenceSource, "AppendSourceSection(builder, snapshot);");
        AssertContains(sharedFormatterValuesSource, "internal static string Get(JsonElement element, string propertyName, string fallback = \"N/A\")");
        AssertContains(sharedFormatterValuesSource, "internal static double GetDouble(JsonElement element, string propertyName, double fallback = 0.0)");
        AssertContains(sharedFormatterValuesSource, "internal static bool GetBool(JsonElement element, string propertyName)");
        AssertDoesNotContain(sharedFormatterValuesSource, "internal static string FormatBytes(long bytes)");
        AssertDoesNotContain(sharedFormatterValuesSource, "internal static long ComputeTickAgeMs(long tickMs)");
        AssertContains(sharedFormatterDisplayValuesSource, "internal static string FormatBytes(long bytes)");
        AssertContains(sharedFormatterDisplayValuesSource, "internal static string FormatIntervalMs(JsonElement element, string propertyName, string fallback = \"N/A\")");
        AssertContains(sharedFormatterDisplayValuesSource, "internal static string FormatFrameBudgetMs(JsonElement element, string fpsPropertyName, string fallback = \"N/A\")");
        AssertContains(sharedFormatterDisplayValuesSource, "internal static string FormatNumber(double value, string format)");
        AssertContains(sharedFormatterDisplayValuesSource, "internal static long ComputeTickAgeMs(long tickMs)");
        AssertContains(sharedFormatterFlashbackSource, "private static void AppendFlashbackSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterFlashbackSource, "var flashbackActive = Get(snapshot, \"FlashbackActive\", \"false\");");
        AssertContains(sharedFormatterFlashbackSource, "AppendFlashbackEncodingSection(builder, snapshot);");
        AssertContains(sharedFormatterFlashbackSource, "AppendFlashbackPlaybackStatusSection(builder, snapshot);");
        AssertContains(sharedFormatterFlashbackSource, "AppendFlashbackExportSection(builder, snapshot);");
        AssertContains(sharedFormatterFlashbackSource, "AppendFlashbackPlaybackMetricsSection(builder, snapshot);");
        AssertDoesNotContain(sharedFormatterFlashbackSource, "private static void AppendFlashbackEncodingSection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(sharedFormatterFlashbackSource, "Encoder: {codec}");
        AssertDoesNotContain(sharedFormatterFlashbackSource, "Flashback Queue Latency:");
        AssertDoesNotContain(sharedFormatterFlashbackSource, "Flashback GPU Queue:");
        AssertContains(sharedFormatterFlashbackEncodingSource, "private static void AppendFlashbackEncodingSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterFlashbackEncodingSource, "AppendFlashbackEncodingStatusSection(builder, snapshot);");
        AssertContains(sharedFormatterFlashbackEncodingSource, "AppendFlashbackEncodingHealthSection(builder, snapshot);");
        AssertDoesNotContain(sharedFormatterFlashbackEncodingSource, "Encoder: {codec}");
        AssertDoesNotContain(sharedFormatterFlashbackEncodingSource, "Flashback Queue Latency:");
        AssertDoesNotContain(sharedFormatterFlashbackEncodingSource, "Flashback GPU Queue:");
        AssertContains(sharedFormatterFlashbackEncodingStatusSource, "private static void AppendFlashbackEncodingStatusSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterFlashbackEncodingStatusSource, "Encoder: {codec}");
        AssertContains(sharedFormatterFlashbackEncodingStatusSource, "Temp Cache:");
        AssertContains(sharedFormatterFlashbackEncodingStatusSource, "Cleanup:");
        AssertDoesNotContain(sharedFormatterFlashbackEncodingStatusSource, "Flashback Queue Latency:");
        AssertDoesNotContain(sharedFormatterFlashbackEncodingStatusSource, "Flashback GPU Queue:");
        AssertDoesNotContain(sharedFormatterFlashbackEncodingStatusSource, "Flashback Failure:");
        AssertContains(sharedFormatterFlashbackEncodingHealthSource, "private static void AppendFlashbackEncodingHealthSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterFlashbackEncodingHealthSource, "Flashback Queue Latency:");
        AssertContains(sharedFormatterFlashbackEncodingHealthSource, "Flashback Backpressure:");
        AssertContains(sharedFormatterFlashbackEncodingHealthSource, "Flashback Failure:");
        AssertContains(sharedFormatterFlashbackEncodingHealthSource, "Flashback GPU Queue:");
        AssertDoesNotContain(sharedFormatterFlashbackEncodingHealthSource, "Encoder: {codec}");
        AssertDoesNotContain(sharedFormatterFlashbackSource, "Export: active=");
        AssertDoesNotContain(sharedFormatterFlashbackSource, "Playback Decode:");
        AssertDoesNotContain(sharedFormatterFlashbackSource, "A/V Drift:");
        AssertContains(sharedFormatterFlashbackExportSource, "private static void AppendFlashbackExportSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterFlashbackExportSource, "Export: active=");
        AssertContains(sharedFormatterFlashbackExportSource, "FlashbackExportThroughputBytesPerSec");
        AssertContains(sharedFormatterFlashbackExportSource, "forceRotateFallbacks=");
        AssertContains(sharedFormatterFlashbackPlaybackCommandsSource, "private static void AppendFlashbackPlaybackStatusSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterFlashbackPlaybackCommandsSource, "Playback Commands:");
        AssertDoesNotContain(sharedFormatterFlashbackPlaybackCommandsSource, "Playback Decode:");
        AssertDoesNotContain(sharedFormatterFlashbackPlaybackCommandsSource, "A/V Drift:");
        AssertContains(sharedFormatterFlashbackPlaybackPerformanceSource, "private static void AppendFlashbackPlaybackMetricsSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterFlashbackPlaybackPerformanceSource, "Playback Decode:");
        AssertContains(sharedFormatterFlashbackPlaybackPerformanceSource, "A/V Drift:");
        AssertDoesNotContain(sharedFormatterFlashbackPlaybackPerformanceSource, "Playback Commands:");
        AssertDoesNotContain(sharedFormatterRootSource, "builder.AppendLine(\"== Thread Health ==\");");
        AssertDoesNotContain(sharedFormatterRootSource, "WasapiPlaybackQueueDurationMs");
        AssertContains(sharedFormatterThreadHealthSource, "private static void AppendThreadHealthSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterThreadHealthSource, "builder.AppendLine(\"== Thread Health ==\");");
        AssertContains(sharedFormatterThreadHealthSource, "AppendSourceReaderThreadHealthLine(builder, snapshot);");
        AssertContains(sharedFormatterThreadHealthSource, "AppendWasapiCaptureThreadHealthLine(builder, snapshot);");
        AssertContains(sharedFormatterThreadHealthSource, "AppendWasapiPlaybackThreadHealthLine(builder, snapshot);");
        AssertDoesNotContain(sharedFormatterThreadHealthSource, "SourceReaderFrameChannelDepth");
        AssertDoesNotContain(sharedFormatterThreadHealthSource, "WasapiCaptureCallbackSevereGapCount");
        AssertDoesNotContain(sharedFormatterThreadHealthSource, "WasapiPlaybackQueueDurationMs");
        AssertContains(sharedFormatterThreadHealthSourceReaderSource, "private static void AppendSourceReaderThreadHealthLine(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterThreadHealthSourceReaderSource, "SourceReaderFrameChannelDepth");
        AssertContains(sharedFormatterThreadHealthWasapiCaptureSource, "private static void AppendWasapiCaptureThreadHealthLine(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterThreadHealthWasapiCaptureSource, "WasapiCaptureCallbackSevereGapCount");
        AssertContains(sharedFormatterThreadHealthWasapiPlaybackSource, "private static void AppendWasapiPlaybackThreadHealthLine(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterThreadHealthWasapiPlaybackSource, "WasapiPlaybackQueueDurationMs");
        AssertContains(sharedFormatterMjpegTimingSource, "private static void AppendMjpegTimingSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterMjpegTimingSource, "var mjpegDecodeSamples = Get(snapshot, \"MjpegDecodeSampleCount\", \"0\");");
        AssertContains(sharedFormatterMjpegTimingSource, "AppendMjpegPreviewJitterSection(builder, snapshot);");
        AssertDoesNotContain(sharedFormatterMjpegTimingSource, "Preview Jitter Latency:");
        AssertContains(sharedFormatterMjpegPreviewJitterSource, "private static void AppendMjpegPreviewJitterSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterMjpegPreviewJitterSource, "Preview Jitter Latency:");
        AssertContains(sharedFormatterMjpegPreviewJitterSource, "Preview Jitter Underflow:");
        AssertContains(sharedFormatterCaptureCadenceSource, "AppendAvSyncSection(builder, snapshot);");
        AssertContains(sharedFormatterCaptureCadenceSource, "AppendSourceSection(builder, snapshot);");
        AssertDoesNotContain(sharedFormatterCaptureCadenceSource, "private static void AppendAvSyncSection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(sharedFormatterCaptureCadenceSource, "private static void AppendSourceSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterAvSyncSource, "private static void AppendAvSyncSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterAvSyncSource, "var avSyncDrift = Get(snapshot, \"AvSyncCaptureDriftMs\", string.Empty);");
        AssertContains(sharedFormatterPreviewSource, "private static void AppendPreviewSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterPreviewSource, "AppendPreviewD3DSection(builder, snapshot);");
        AssertDoesNotContain(sharedFormatterPreviewSource, "AppendPreviewSlowFrameDiagnostics(builder, snapshot);");
        AssertDoesNotContain(sharedFormatterPreviewSource, "D3D CPU timing:");
        AssertContains(sharedFormatterPreviewD3DSource, "private static void AppendPreviewD3DSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterPreviewD3DSource, "private static bool IsPreviewD3DRendererMode(string rendererMode)");
        AssertContains(sharedFormatterPreviewD3DSource, "AppendPreviewD3DCpuTiming(builder, snapshot);");
        AssertContains(sharedFormatterPreviewD3DSource, "AppendPreviewD3DPipelineLatency(builder, snapshot);");
        AssertContains(sharedFormatterPreviewD3DSource, "AppendPreviewD3DFrameLatencyWait(builder, snapshot);");
        AssertContains(sharedFormatterPreviewD3DSource, "AppendPreviewD3DFrameStats(builder, snapshot);");
        AssertContains(sharedFormatterPreviewD3DSource, "AppendPreviewD3DFrameOwnership(builder, snapshot);");
        AssertContains(sharedFormatterPreviewD3DSource, "AppendPreviewSlowFrameDiagnostics(builder, snapshot);");
        AssertOccursBefore(sharedFormatterPreviewD3DSource, "AppendPreviewD3DCpuTiming(builder, snapshot);", "AppendPreviewD3DPipelineLatency(builder, snapshot);");
        AssertOccursBefore(sharedFormatterPreviewD3DSource, "AppendPreviewD3DPipelineLatency(builder, snapshot);", "AppendPreviewD3DFrameLatencyWait(builder, snapshot);");
        AssertOccursBefore(sharedFormatterPreviewD3DSource, "AppendPreviewD3DFrameLatencyWait(builder, snapshot);", "AppendPreviewD3DFrameStats(builder, snapshot);");
        AssertOccursBefore(sharedFormatterPreviewD3DSource, "AppendPreviewD3DFrameStats(builder, snapshot);", "AppendPreviewD3DFrameOwnership(builder, snapshot);");
        AssertOccursBefore(sharedFormatterPreviewD3DSource, "AppendPreviewD3DFrameOwnership(builder, snapshot);", "AppendPreviewSlowFrameDiagnostics(builder, snapshot);");
        AssertDoesNotContain(sharedFormatterPreviewD3DSource, "private static void AppendPreviewD3DCpuTiming(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(sharedFormatterPreviewD3DSource, "D3D CPU timing:");
        AssertDoesNotContain(sharedFormatterPreviewD3DSource, "private static void AppendPreviewD3DFrameStats(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(sharedFormatterPreviewD3DSource, "D3D DXGI stats:");
        AssertContains(sharedFormatterPreviewD3DTimingSource, "private static void AppendPreviewD3DCpuTiming(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterPreviewD3DTimingSource, "D3D CPU timing:");
        AssertContains(sharedFormatterPreviewD3DTimingSource, "private static void AppendPreviewD3DPipelineLatency(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterPreviewD3DTimingSource, "D3D pipeline latency:");
        AssertContains(sharedFormatterPreviewD3DTimingSource, "private static void AppendPreviewD3DFrameLatencyWait(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterPreviewD3DTimingSource, "D3D frame-latency wait:");
        AssertContains(sharedFormatterPreviewD3DFrameFlowSource, "private static void AppendPreviewD3DFrameStats(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterPreviewD3DFrameFlowSource, "D3D DXGI stats:");
        AssertContains(sharedFormatterPreviewD3DFrameFlowSource, "private static void AppendPreviewD3DFrameOwnership(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterPreviewD3DFrameFlowSource, "D3D Ownership:");
        AssertDoesNotContain(sharedFormatterPreviewD3DSource, "D3D Slow Frames:");
        AssertDoesNotContain(sharedFormatterPreviewD3DSource, "private static string FormatDiagnosticMs(JsonElement element, string propertyName)");
        AssertContains(sharedFormatterPreviewD3DSlowFramesSource, "internal static void AppendPreviewSlowFrameDiagnostics(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterPreviewD3DSlowFramesSource, "private static string FormatDiagnosticMs(JsonElement element, string propertyName)");
        AssertContains(sharedFormatterPreviewD3DSlowFramesSource, "D3D Slow Frames:");
        AssertContains(sharedFormatterSourceSource, "private static void AppendSourceSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(sharedFormatterSourceSource, "var sourceFrameRate = Get(snapshot, \"DetectedSourceFrameRate\", string.Empty);");
        AssertContains(sharedFormatterSource, "CaptureCommandOldestPendingCommandAgeMs");
        AssertContains(sharedFormatterSource, "CaptureCommandMaxQueueLatencyMs");
        AssertContains(sharedFormatterSource, "CaptureCommandCommandsCoalesced");
        AssertContains(sharedFormatterSource, "CaptureCommandLastOutcome");
        AssertContains(sharedFormatterSource, "CaptureCommandLastCorrelationId");
        AssertContains(sharedFormatterSource, "PreviewD3DInputUploadCpuP99Ms");
        AssertContains(sharedFormatterSource, "PreviewD3DTotalFrameCpuMaxMs");
        AssertContains(sharedFormatterSource, "ProcessCpuPercent");

        return Task.CompletedTask;
    }
}
