using System.Threading.Tasks;

static partial class Program
{
    internal static Task SsctlFormatters_SnapshotSourceOwnership_IsSplit()
    {
        var ssctlFormatterCommonSource = ReadRepoFile("tools/ssctl/Formatters.Common.cs");
        var ssctlFormatterSource = global::Sussudio.Tests.RuntimeContractSource.ReadSsctlSnapshotFormatterSource();
        var ssctlSnapshotRootSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.cs");
        var ssctlSnapshotCoreSectionsSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.CoreSections.cs");
        var ssctlSnapshotAudioSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Audio.cs");
        var ssctlSnapshotRecordingSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Recording.cs");
        var ssctlSnapshotProcessResourcesSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.ProcessResources.cs");
        var ssctlSnapshotCaptureSettingsSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.CaptureSettings.cs");
        var ssctlSnapshotCaptureCadenceSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.CaptureCadence.cs");
        var ssctlSnapshotAvSyncSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.AvSync.cs");
        var ssctlSnapshotSourceSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Source.cs");
        var ssctlSnapshotDiagnosticLanesSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.DiagnosticLanes.cs");
        var ssctlSnapshotFlashbackSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Flashback.cs");
        var ssctlSnapshotFlashbackEncodingSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Flashback.Encoding.cs");
        var ssctlSnapshotFlashbackEncodingStatusSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Flashback.Encoding.Status.cs");
        var ssctlSnapshotFlashbackEncodingHealthSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Flashback.Encoding.Health.cs");
        var ssctlSnapshotFlashbackExportSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Flashback.Export.cs");
        var ssctlSnapshotFlashbackPlaybackCommandsSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Flashback.Playback.Commands.cs");
        var ssctlSnapshotFlashbackPlaybackPerformanceSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Flashback.Playback.Performance.cs");
        var ssctlSnapshotMjpegSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Mjpeg.cs");
        var ssctlSnapshotMjpegDecodeSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Mjpeg.Decode.cs");
        var ssctlSnapshotMjpegPipelineSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Mjpeg.Pipeline.cs");
        var ssctlSnapshotMjpegPreviewJitterSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Mjpeg.PreviewJitter.cs");
        var ssctlSnapshotPreviewSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Preview.cs");
        var ssctlSnapshotPreviewD3DSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.PreviewD3D.cs");
        var ssctlSnapshotPreviewD3DTimingSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.PreviewD3D.Timing.cs");
        var ssctlSnapshotPreviewD3DFrameFlowSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.PreviewD3D.FrameFlow.cs");
        var ssctlSnapshotRuntimeSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.Runtime.cs");
        var ssctlSnapshotThreadHealthSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.ThreadHealth.cs");
        var ssctlSnapshotThreadHealthSourceReaderSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.ThreadHealth.SourceReader.cs");
        var ssctlSnapshotThreadHealthWasapiCaptureSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.ThreadHealth.WasapiCapture.cs");
        var ssctlSnapshotThreadHealthWasapiPlaybackSource = ReadRepoFile("tools/ssctl/Formatters.Snapshot.ThreadHealth.WasapiPlayback.cs");
        AssertDoesNotContain(ssctlFormatterCommonSource, "public static string FormatSnapshot");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotStateSection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotCaptureSettingsSection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotAudioSection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotVideoPipelineSection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotFlashbackSection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotDiagnosticLanesSection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotPerformanceSection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotMemorySection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotCaptureCadenceSection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotMjpegTimingSection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotAvSyncSection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotPreviewSection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotThreadHealthSection(builder, snapshot);");
        AssertContains(ssctlSnapshotRootSource, "AppendSnapshotSourceSection(builder, snapshot);");
        AssertDoesNotContain(ssctlSnapshotRootSource, "builder.AppendLine(\"== Sussudio State ==\");");
        AssertDoesNotContain(ssctlSnapshotRootSource, "var selectedFriendlyFrameRate = AutomationSnapshotFormatter.Get(snapshot, \"SelectedFriendlyFrameRate\", string.Empty);");
        AssertDoesNotContain(ssctlSnapshotRootSource, "builder.AppendLine(\"== Audio ==\");");
        AssertDoesNotContain(ssctlSnapshotRootSource, "builder.AppendLine(\"== Video Pipeline ==\");");
        AssertDoesNotContain(ssctlSnapshotRootSource, "builder.AppendLine(\"== Recording ==\");");
        AssertDoesNotContain(ssctlSnapshotRootSource, "builder.AppendLine(\"== Diagnostics ==\");");
        AssertDoesNotContain(ssctlSnapshotRootSource, "builder.AppendLine(\"== Performance ==\");");
        AssertDoesNotContain(ssctlSnapshotRootSource, "builder.AppendLine(\"== Capture Cadence ==\");");
        AssertDoesNotContain(ssctlSnapshotRootSource, "var flashbackActive = AutomationSnapshotFormatter.Get(snapshot, \"FlashbackActive\", \"false\");");
        AssertDoesNotContain(ssctlSnapshotRootSource, "builder.AppendLine(\"== Memory & GC ==\");");
        AssertDoesNotContain(ssctlSnapshotRootSource, "var mjpegDecodeSamples = AutomationSnapshotFormatter.Get(snapshot, \"MjpegDecodeSampleCount\", \"0\");");
        AssertDoesNotContain(ssctlSnapshotRootSource, "var avSyncDrift = AutomationSnapshotFormatter.Get(snapshot, \"AvSyncCaptureDriftMs\", string.Empty);");
        AssertDoesNotContain(ssctlSnapshotRootSource, "var rendererMode = AutomationSnapshotFormatter.Get(snapshot, \"PreviewRendererMode\");");
        AssertDoesNotContain(ssctlSnapshotRootSource, "builder.AppendLine(\"== Thread Health ==\");");
        AssertDoesNotContain(ssctlSnapshotRootSource, "var sourceReaderLastFrameAgeMs = AutomationSnapshotFormatter.ComputeTickAgeMs");
        AssertDoesNotContain(ssctlSnapshotRootSource, "builder.AppendLine(\"== Source ==\");");
        AssertContains(ssctlSnapshotCoreSectionsSource, "private static void AppendSnapshotStateSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotCoreSectionsSource, "builder.AppendLine(\"== Sussudio State ==\");");
        AssertContains(ssctlSnapshotCaptureSettingsSource, "private static void AppendSnapshotCaptureSettingsSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotCaptureSettingsSource, "private static string FormatSnapshotFrameRateSummary(JsonElement snapshot)");
        AssertDoesNotContain(ssctlSnapshotCoreSectionsSource, "private static void AppendSnapshotAudioSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotAudioSource, "private static void AppendSnapshotAudioSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotAudioSource, "builder.AppendLine(\"== Audio ==\");");
        AssertContains(ssctlSnapshotRuntimeSource, "private static void AppendSnapshotVideoPipelineSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotRuntimeSource, "builder.AppendLine(\"== Video Pipeline ==\");");
        AssertDoesNotContain(ssctlSnapshotCoreSectionsSource, "private static void AppendSnapshotRecordingSection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(ssctlSnapshotCoreSectionsSource, "RecordingIntegrityStatus");
        AssertContains(ssctlSnapshotRecordingSource, "private static void AppendSnapshotRecordingSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotRecordingSource, "builder.AppendLine(\"== Recording ==\");");
        AssertContains(ssctlSnapshotRecordingSource, "RecordingIntegrityStatus");
        AssertContains(ssctlSnapshotDiagnosticLanesSource, "private static void AppendSnapshotDiagnosticLanesSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotDiagnosticLanesSource, "builder.AppendLine(\"== Diagnostics ==\");");
        AssertDoesNotContain(ssctlSnapshotCoreSectionsSource, "private static void AppendSnapshotPerformanceSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotProcessResourcesSource, "private static void AppendSnapshotPerformanceSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotProcessResourcesSource, "builder.AppendLine(\"== Performance ==\");");
        AssertDoesNotContain(ssctlSnapshotRuntimeSource, "private static void AppendSnapshotCaptureCadenceSection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(ssctlSnapshotRuntimeSource, "private static void AppendSnapshotAvSyncSection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(ssctlSnapshotRuntimeSource, "private static void AppendSnapshotPreviewSection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(ssctlSnapshotRuntimeSource, "private static void AppendSnapshotSourceSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotCaptureCadenceSource, "private static void AppendSnapshotCaptureCadenceSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotCaptureCadenceSource, "builder.AppendLine(\"== Capture Cadence ==\");");
        AssertDoesNotContain(ssctlSnapshotCaptureCadenceSource, "private static void AppendSnapshotAvSyncSection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(ssctlSnapshotCaptureCadenceSource, "private static void AppendSnapshotSourceSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotAvSyncSource, "private static void AppendSnapshotAvSyncSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotAvSyncSource, "var avSyncDrift = AutomationSnapshotFormatter.Get(snapshot, \"AvSyncCaptureDriftMs\", string.Empty);");
        AssertContains(ssctlSnapshotAvSyncSource, "builder.AppendLine(\"== AV Sync ==\");");
        AssertContains(ssctlSnapshotSourceSource, "private static void AppendSnapshotSourceSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotSourceSource, "builder.AppendLine(\"== Source ==\");");
        AssertContains(ssctlSnapshotFlashbackSource, "private static void AppendSnapshotFlashbackSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotFlashbackSource, "var flashbackActive = AutomationSnapshotFormatter.Get(snapshot, \"FlashbackActive\", \"false\");");
        AssertContains(ssctlSnapshotFlashbackSource, "AppendSnapshotFlashbackEncodingSection(builder, snapshot);");
        AssertContains(ssctlSnapshotFlashbackSource, "AppendSnapshotFlashbackPlaybackStatusSection(builder, snapshot);");
        AssertContains(ssctlSnapshotFlashbackSource, "AppendSnapshotFlashbackExportSection(builder, snapshot);");
        AssertContains(ssctlSnapshotFlashbackSource, "AppendSnapshotFlashbackPlaybackMetricsSection(builder, snapshot);");
        AssertDoesNotContain(ssctlSnapshotFlashbackSource, "private static void AppendSnapshotFlashbackEncodingSection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(ssctlSnapshotFlashbackSource, "Encoder: {encCodec}");
        AssertDoesNotContain(ssctlSnapshotFlashbackSource, "Flashback Queue Latency:");
        AssertDoesNotContain(ssctlSnapshotFlashbackSource, "Flashback GPU Queue:");
        AssertContains(ssctlSnapshotFlashbackEncodingSource, "private static void AppendSnapshotFlashbackEncodingSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotFlashbackEncodingSource, "AppendSnapshotFlashbackEncodingStatusSection(builder, snapshot);");
        AssertContains(ssctlSnapshotFlashbackEncodingSource, "AppendSnapshotFlashbackEncodingHealthSection(builder, snapshot);");
        AssertDoesNotContain(ssctlSnapshotFlashbackEncodingSource, "Encoder: {encCodec}");
        AssertDoesNotContain(ssctlSnapshotFlashbackEncodingSource, "Flashback Queue Latency:");
        AssertDoesNotContain(ssctlSnapshotFlashbackEncodingSource, "Flashback GPU Queue:");
        AssertContains(ssctlSnapshotFlashbackEncodingStatusSource, "private static void AppendSnapshotFlashbackEncodingStatusSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotFlashbackEncodingStatusSource, "Encoder: {encCodec}");
        AssertContains(ssctlSnapshotFlashbackEncodingStatusSource, "Temp Cache:");
        AssertContains(ssctlSnapshotFlashbackEncodingStatusSource, "Cleanup:");
        AssertDoesNotContain(ssctlSnapshotFlashbackEncodingStatusSource, "Flashback Queue Latency:");
        AssertDoesNotContain(ssctlSnapshotFlashbackEncodingStatusSource, "Flashback GPU Queue:");
        AssertDoesNotContain(ssctlSnapshotFlashbackEncodingStatusSource, "Flashback Failure:");
        AssertContains(ssctlSnapshotFlashbackEncodingHealthSource, "private static void AppendSnapshotFlashbackEncodingHealthSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotFlashbackEncodingHealthSource, "Flashback Queue Latency:");
        AssertContains(ssctlSnapshotFlashbackEncodingHealthSource, "Flashback Backpressure:");
        AssertContains(ssctlSnapshotFlashbackEncodingHealthSource, "Flashback Failure:");
        AssertContains(ssctlSnapshotFlashbackEncodingHealthSource, "Flashback GPU Queue:");
        AssertDoesNotContain(ssctlSnapshotFlashbackEncodingHealthSource, "Encoder: {encCodec}");
        AssertDoesNotContain(ssctlSnapshotFlashbackSource, "Export: active=");
        AssertContains(ssctlSnapshotFlashbackExportSource, "private static void AppendSnapshotFlashbackExportSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotFlashbackExportSource, "Export: active=");
        AssertContains(ssctlSnapshotFlashbackExportSource, "FlashbackExportThroughputBytesPerSec");
        AssertContains(ssctlSnapshotFlashbackExportSource, "forceRotateFallbacks=");
        AssertDoesNotContain(ssctlSnapshotFlashbackSource, "private static void AppendSnapshotFlashbackPlaybackStatusSection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(ssctlSnapshotFlashbackSource, "private static void AppendSnapshotFlashbackPlaybackMetricsSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotFlashbackPlaybackCommandsSource, "private static void AppendSnapshotFlashbackPlaybackStatusSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotFlashbackPlaybackCommandsSource, "Playback Commands:");
        AssertDoesNotContain(ssctlSnapshotFlashbackPlaybackCommandsSource, "Playback Decode:");
        AssertDoesNotContain(ssctlSnapshotFlashbackPlaybackCommandsSource, "A/V Drift:");
        AssertContains(ssctlSnapshotFlashbackPlaybackPerformanceSource, "private static void AppendSnapshotFlashbackPlaybackMetricsSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotFlashbackPlaybackPerformanceSource, "Playback Decode:");
        AssertContains(ssctlSnapshotFlashbackPlaybackPerformanceSource, "A/V Drift:");
        AssertDoesNotContain(ssctlSnapshotFlashbackPlaybackPerformanceSource, "Playback Commands:");
        AssertDoesNotContain(ssctlSnapshotCoreSectionsSource, "private static void AppendSnapshotMemorySection(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(ssctlSnapshotCoreSectionsSource, "ProcessCpuPercent");
        AssertContains(ssctlSnapshotProcessResourcesSource, "private static void AppendSnapshotMemorySection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotProcessResourcesSource, "builder.AppendLine(\"== Memory & GC ==\");");
        AssertContains(ssctlSnapshotProcessResourcesSource, "ProcessCpuPercent");
        AssertContains(ssctlSnapshotMjpegSource, "private static void AppendSnapshotMjpegTimingSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotMjpegSource, "var mjpegDecodeSamples = AutomationSnapshotFormatter.Get(snapshot, \"MjpegDecodeSampleCount\", \"0\");");
        AssertContains(ssctlSnapshotMjpegSource, "AppendSnapshotMjpegDecodeTimingLines(builder, snapshot, mjpegDecodeSamples);");
        AssertContains(ssctlSnapshotMjpegSource, "AppendSnapshotMjpegPipelineTimingLines(builder, snapshot, mjpegDecoderCount);");
        AssertContains(ssctlSnapshotMjpegSource, "AppendSnapshotMjpegPreviewJitterSection(builder, snapshot);");
        AssertContains(ssctlSnapshotMjpegSource, "AppendSnapshotMjpegPerDecoderTimingLines(builder, snapshot);");
        AssertDoesNotContain(ssctlSnapshotMjpegSource, "Decode: avg=");
        AssertDoesNotContain(ssctlSnapshotMjpegSource, "Compressed Queue:");
        AssertDoesNotContain(ssctlSnapshotMjpegSource, "Decoder[");
        AssertDoesNotContain(ssctlSnapshotMjpegSource, "Preview Jitter Latency:");
        AssertContains(ssctlSnapshotMjpegDecodeSource, "private static void AppendSnapshotMjpegDecodeTimingLines(StringBuilder builder, JsonElement snapshot, string mjpegDecodeSamples)");
        AssertContains(ssctlSnapshotMjpegDecodeSource, "private static void AppendSnapshotMjpegPerDecoderTimingLines(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotMjpegDecodeSource, "Decode: avg=");
        AssertContains(ssctlSnapshotMjpegDecodeSource, "Decoder[{AutomationSnapshotFormatter.Get(worker, \"WorkerIndex\", \"?\")}]");
        AssertDoesNotContain(ssctlSnapshotMjpegDecodeSource, "Compressed Queue:");
        AssertContains(ssctlSnapshotMjpegPipelineSource, "private static void AppendSnapshotMjpegPipelineTimingLines(StringBuilder builder, JsonElement snapshot, string mjpegDecoderCount)");
        AssertContains(ssctlSnapshotMjpegPipelineSource, "Compressed Queue:");
        AssertContains(ssctlSnapshotMjpegPipelineSource, "MJPEG Drop Reasons:");
        AssertContains(ssctlSnapshotMjpegPipelineSource, "Pipeline: avg=");
        AssertDoesNotContain(ssctlSnapshotMjpegPipelineSource, "Decoder[{AutomationSnapshotFormatter.Get(worker");
        AssertContains(ssctlSnapshotMjpegPreviewJitterSource, "private static void AppendSnapshotMjpegPreviewJitterSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotMjpegPreviewJitterSource, "Preview Jitter Latency:");
        AssertContains(ssctlSnapshotMjpegPreviewJitterSource, "Preview Jitter Underflow:");
        AssertContains(ssctlSnapshotPreviewSource, "private static void AppendSnapshotPreviewSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotPreviewSource, "var rendererMode = AutomationSnapshotFormatter.Get(snapshot, \"PreviewRendererMode\");");
        AssertContains(ssctlSnapshotPreviewSource, "AppendSnapshotPreviewD3DSection(builder, snapshot);");
        AssertDoesNotContain(ssctlSnapshotPreviewSource, "D3D CPU timing:");
        AssertContains(ssctlSnapshotPreviewD3DSource, "private static void AppendSnapshotPreviewD3DSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotPreviewD3DSource, "private static bool IsSnapshotPreviewD3DRendererMode(string rendererMode)");
        AssertContains(ssctlSnapshotPreviewD3DSource, "AppendSnapshotPreviewD3DCpuTiming(builder, snapshot);");
        AssertContains(ssctlSnapshotPreviewD3DSource, "AppendSnapshotPreviewD3DPipelineLatency(builder, snapshot);");
        AssertContains(ssctlSnapshotPreviewD3DSource, "AppendSnapshotPreviewD3DFrameLatencyWait(builder, snapshot);");
        AssertContains(ssctlSnapshotPreviewD3DSource, "AppendSnapshotPreviewD3DFrameStats(builder, snapshot);");
        AssertContains(ssctlSnapshotPreviewD3DSource, "AppendSnapshotPreviewD3DFrameOwnership(builder, snapshot);");
        AssertContains(ssctlSnapshotPreviewD3DSource, "AppendSnapshotPreviewSlowFrameDiagnostics(builder, snapshot);");
        AssertOccursBefore(ssctlSnapshotPreviewD3DSource, "AppendSnapshotPreviewD3DCpuTiming(builder, snapshot);", "AppendSnapshotPreviewD3DPipelineLatency(builder, snapshot);");
        AssertOccursBefore(ssctlSnapshotPreviewD3DSource, "AppendSnapshotPreviewD3DPipelineLatency(builder, snapshot);", "AppendSnapshotPreviewD3DFrameLatencyWait(builder, snapshot);");
        AssertOccursBefore(ssctlSnapshotPreviewD3DSource, "AppendSnapshotPreviewD3DFrameLatencyWait(builder, snapshot);", "AppendSnapshotPreviewD3DFrameStats(builder, snapshot);");
        AssertOccursBefore(ssctlSnapshotPreviewD3DSource, "AppendSnapshotPreviewD3DFrameStats(builder, snapshot);", "AppendSnapshotPreviewD3DFrameOwnership(builder, snapshot);");
        AssertOccursBefore(ssctlSnapshotPreviewD3DSource, "AppendSnapshotPreviewD3DFrameOwnership(builder, snapshot);", "AppendSnapshotPreviewSlowFrameDiagnostics(builder, snapshot);");
        AssertDoesNotContain(ssctlSnapshotPreviewD3DSource, "private static void AppendSnapshotPreviewD3DCpuTiming(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(ssctlSnapshotPreviewD3DSource, "D3D CPU timing:");
        AssertDoesNotContain(ssctlSnapshotPreviewD3DSource, "private static void AppendSnapshotPreviewD3DFrameStats(StringBuilder builder, JsonElement snapshot)");
        AssertDoesNotContain(ssctlSnapshotPreviewD3DSource, "D3D DXGI stats:");
        AssertContains(ssctlSnapshotPreviewD3DTimingSource, "private static void AppendSnapshotPreviewD3DCpuTiming(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotPreviewD3DTimingSource, "D3D CPU timing:");
        AssertContains(ssctlSnapshotPreviewD3DTimingSource, "private static void AppendSnapshotPreviewD3DPipelineLatency(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotPreviewD3DTimingSource, "D3D pipeline latency:");
        AssertContains(ssctlSnapshotPreviewD3DTimingSource, "private static void AppendSnapshotPreviewD3DFrameLatencyWait(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotPreviewD3DTimingSource, "D3D frame-latency wait:");
        AssertContains(ssctlSnapshotPreviewD3DFrameFlowSource, "private static void AppendSnapshotPreviewD3DFrameOwnership(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotPreviewD3DFrameFlowSource, "D3D Ownership:");
        AssertContains(ssctlSnapshotPreviewD3DFrameFlowSource, "private static void AppendSnapshotPreviewD3DFrameStats(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotPreviewD3DFrameFlowSource, "D3D DXGI stats:");
        AssertContains(ssctlSnapshotPreviewD3DSource, "private static void AppendSnapshotPreviewSlowFrameDiagnostics(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotPreviewD3DSource, "AutomationSnapshotFormatter.AppendPreviewSlowFrameDiagnostics(builder, snapshot);");
        AssertContains(ssctlSnapshotThreadHealthSource, "private static void AppendSnapshotThreadHealthSection(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotThreadHealthSource, "builder.AppendLine(\"== Thread Health ==\");");
        AssertContains(ssctlSnapshotThreadHealthSource, "AppendSnapshotSourceReaderThreadHealthLine(builder, snapshot);");
        AssertContains(ssctlSnapshotThreadHealthSource, "AppendSnapshotWasapiCaptureThreadHealthLine(builder, snapshot);");
        AssertContains(ssctlSnapshotThreadHealthSource, "AppendSnapshotWasapiPlaybackThreadHealthLine(builder, snapshot);");
        AssertDoesNotContain(ssctlSnapshotThreadHealthSource, "SourceReaderFrameChannelDepth");
        AssertDoesNotContain(ssctlSnapshotThreadHealthSource, "WasapiCaptureCallbackSevereGapCount");
        AssertDoesNotContain(ssctlSnapshotThreadHealthSource, "WasapiPlaybackQueueDropCount");
        AssertContains(ssctlSnapshotThreadHealthSourceReaderSource, "private static void AppendSnapshotSourceReaderThreadHealthLine(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotThreadHealthSourceReaderSource, "SourceReaderFrameChannelDepth");
        AssertContains(ssctlSnapshotThreadHealthWasapiCaptureSource, "private static void AppendSnapshotWasapiCaptureThreadHealthLine(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotThreadHealthWasapiCaptureSource, "WasapiCaptureCallbackSevereGapCount");
        AssertContains(ssctlSnapshotThreadHealthWasapiPlaybackSource, "private static void AppendSnapshotWasapiPlaybackThreadHealthLine(StringBuilder builder, JsonElement snapshot)");
        AssertContains(ssctlSnapshotThreadHealthWasapiPlaybackSource, "WasapiPlaybackQueueDropCount");
        AssertContains(ssctlSnapshotSourceSource, "var sourceFrameRate = AutomationSnapshotFormatter.Get(snapshot, \"DetectedSourceFrameRate\", string.Empty);");
        AssertContains(ReadRepoFile("tools/ssctl/Formatters.Diagnostics.cs"), "public static string FormatDiagnostics");
        AssertContains(ReadRepoFile("tools/ssctl/Formatters.Options.cs"), "public static string FormatOptions");
        var ssctlTimelineRootSource = ReadRepoFile("tools/ssctl/Formatters.Timeline.cs");
        var ssctlTimelineRowsSource = ReadRepoFile("tools/ssctl/Formatters.Timeline.Rows.cs");
        var ssctlTimelineRowsModelSource = ReadRepoFile("tools/ssctl/Formatters.Timeline.Rows.Model.cs");
        var ssctlTimelineRenderingSource = ReadRepoFile("tools/ssctl/Formatters.Timeline.Rendering.cs");
        var ssctlTimelineSummariesSource = ReadRepoFile("tools/ssctl/Formatters.Timeline.Summaries.cs");
        AssertContains(ssctlTimelineRootSource, "public static string FormatTimeline");
        AssertContains(ssctlTimelineRootSource, "var entries = ReadTimelineRows(data);");
        AssertContains(ssctlTimelineRootSource, "return RenderTimeline(entries);");
        AssertDoesNotContain(ssctlTimelineRootSource, "private sealed class TimelineRow");
        AssertDoesNotContain(ssctlTimelineRootSource, "new StringBuilder()");
        AssertDoesNotContain(ssctlTimelineRootSource, "== Trend Summary");
        AssertDoesNotContain(ssctlTimelineRowsSource, "private sealed class TimelineRow");
        AssertContains(ssctlTimelineRowsModelSource, "private sealed class TimelineRow");
        AssertContains(ssctlTimelineRowsSource, "AutomationSnapshotFormatter.GetDouble(item, \"CaptureFps\")");
        AssertContains(ssctlTimelineRenderingSource, "private static string RenderTimeline(IReadOnlyList<TimelineRow> entries)");
        AssertContains(ssctlTimelineRenderingSource, "Performance Timeline ({entries.Count} samples)");
        AssertContains(ssctlTimelineRenderingSource, "AppendTimelineTrendSummary(builder, entries);");
        AssertContains(ssctlTimelineSummariesSource, "private static void AppendTimelineTrendSummary(StringBuilder builder, IReadOnlyList<TimelineRow> entries)");
        AssertContains(ssctlTimelineSummariesSource, "== Trend Summary (first vs last sample) ==");
        AssertContains(ReadRepoFile("tools/ssctl/Formatters.Memory.cs"), "public static string FormatMemory");
        AssertContains(ssctlFormatterCommonSource, "public static string FormatResult");
        AssertContains(ssctlFormatterSource, "CaptureCommandOldestPendingCommandAgeMs");
        AssertContains(ssctlFormatterSource, "CaptureCommandMaxQueueLatencyMs");
        AssertContains(ssctlFormatterSource, "CaptureCommandCommandsCoalesced");
        AssertContains(ssctlFormatterSource, "CaptureCommandLastOutcome");
        AssertContains(ssctlFormatterSource, "CaptureCommandLastCorrelationId");
        AssertContains(ssctlFormatterSource, "PreviewD3DInputUploadCpuP99Ms");
        AssertContains(ssctlFormatterSource, "PreviewD3DTotalFrameCpuMaxMs");
        AssertContains(ssctlFormatterSource, "ProcessCpuPercent");

        return Task.CompletedTask;
    }
}
