using System.Threading.Tasks;

static partial class Program
{
    internal static Task CaptureOptionBindings_LiveInController()
    {
        var mainWindowText = ReadMainWindowCompositionSource();
        var bindingsText = ReadRepoFile("Sussudio/MainWindow.Bindings.cs").Replace("\r\n", "\n");
        var captureOptionBindingsText = ReadRepoFile("Sussudio/MainWindow.CaptureOptionBindings.cs").Replace("\r\n", "\n");
        var propertyChangedText = ReadRepoFile("Sussudio/MainWindow.PropertyChanged.cs").Replace("\r\n", "\n");
        var controllerRootText = ReadRepoFile("Sussudio/Controllers/Capture/CaptureOptionBindingController.cs").Replace("\r\n", "\n");
        var controllerBindingsText = ReadRepoFile("Sussudio/Controllers/Capture/CaptureOptionBindingController.Bindings.cs").Replace("\r\n", "\n");
        var controllerPropertyChangesText = ReadRepoFile("Sussudio/Controllers/Capture/CaptureOptionBindingController.PropertyChanges.cs").Replace("\r\n", "\n");
        var controllerText = string.Join("\n", controllerRootText, controllerBindingsText, controllerPropertyChangesText);
        var agentMapText = ReadRepoFile("docs/architecture/AGENT_MAP.md").Replace("\r\n", "\n");
        var cleanupPlanText = ReadRepoFile("docs/architecture/cleanup-plan.md").Replace("\r\n", "\n");
        var selectionBindingFamilyText = string.Join(
            "\n",
            ReadRepoFile("Sussudio/Controllers/Capture/CaptureSelectionBindingController.cs").Replace("\r\n", "\n"),
            ReadRepoFile("Sussudio/Controllers/Capture/CaptureSelectionBindingController.RecordingSelection.cs").Replace("\r\n", "\n"));
        var captureOptionBindingsWithoutVideoFormat = captureOptionBindingsText.Replace("VideoFormatComboBox.SelectionChanged +=", string.Empty);
        var captureOptionPropertyChangedMethod = ExtractMemberCode(captureOptionBindingsText, "TryHandleCaptureOptionPropertyChanged");

        AssertContains(captureOptionBindingsText, "private CaptureOptionBindingController _captureOptionBindingController = null!;");
        AssertContains(captureOptionBindingsText, "private void InitializeCaptureOptionBindingController()");
        AssertContains(captureOptionBindingsText, "ResolutionComboBox = ResolutionComboBox,");
        AssertContains(captureOptionBindingsText, "VideoFormatComboBox = VideoFormatComboBox,");
        AssertContains(captureOptionBindingsText, "TrueHdrPreviewToggle = TrueHdrPreviewToggle,");
        AssertContains(captureOptionBindingsText, "ApplyInitialDecoderCountSelection = ApplyInitialDecoderCountSelection,");
        AssertContains(captureOptionBindingsText, "ApplyAudioClipVisibility = ApplyAudioClipVisibility,");
        AssertContains(captureOptionBindingsText, "RefreshHdrHintText = RefreshHdrHintText,");
        AssertContains(captureOptionBindingsText, "UpdateFpsTelemetryTooltip = UpdateFpsTelemetryTooltip,");
        AssertContains(captureOptionBindingsText, "UpdateVideoContentOverlays = UpdateVideoContentOverlays,");
        AssertContains(captureOptionBindingsText, "SetHdrPassthroughEnabled = enabled => _previewRendererHostController.SetHdrPassthroughEnabled(enabled),");
        AssertContains(captureOptionBindingsText, "EnsureSplitEncodeModeSelection = EnsureSplitEncodeModeSelection");
        AssertContains(captureOptionBindingsText, "private void InitializeCaptureOptionCollections()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.InitializeCollections();");
        AssertContains(captureOptionBindingsText, "private void ApplyInitialCaptureOptionSelections()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.ApplyInitialSelections();");
        AssertContains(captureOptionBindingsText, "private void EnsureInitialCaptureOptionSelections()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.EnsureInitialSelections();");
        AssertContains(captureOptionBindingsText, "private void AttachCaptureModeSelectionBindings()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.AttachCaptureModeSelectionBindings();");
        AssertContains(captureOptionBindingsText, "private void HandleCustomBitratePropertyChanged()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.HandleCustomBitratePropertyChanged();");
        AssertContains(captureOptionBindingsText, "private void HandleHdrEnabledChanged()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.HandleHdrEnabledChanged();");
        AssertContains(captureOptionBindingsText, "private void HandleTrueHdrPreviewEnabledChanged()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.HandleTrueHdrPreviewEnabledChanged();");
        AssertContains(captureOptionBindingsText, "private bool TryHandleCaptureOptionPropertyChanged(string propertyName)");
        AssertContains(captureOptionPropertyChangedMethod, "=> _captureOptionBindingController.TryHandlePropertyChanged(propertyName);");
        AssertContains(captureOptionBindingsText, "private void AttachRecordingOptionBindings()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.AttachRecordingOptionBindings();");
        AssertContains(mainWindowText, "InitializeCaptureOptionBindingController();");

        AssertContains(controllerRootText, "internal sealed class CaptureOptionBindingControllerContext");
        AssertContains(controllerRootText, "internal sealed partial class CaptureOptionBindingController");
        AssertContains(controllerRootText, "private readonly CaptureOptionBindingControllerContext _context;");
        AssertContains(controllerRootText, "public CaptureOptionBindingController(CaptureOptionBindingControllerContext context)");
        AssertDoesNotContain(controllerRootText, "public void InitializeCollections()");
        AssertContains(controllerBindingsText, "public void InitializeCollections()");
        AssertContains(controllerBindingsText, "_context.VideoFormatComboBox.ItemsSource = _context.ViewModel.AvailableVideoFormats;");
        AssertContains(controllerBindingsText, "for (var i = 1; i <= 8; i++)");
        AssertContains(controllerBindingsText, "_context.DecoderCountComboBox.Items.Add(i);");
        AssertContains(controllerBindingsText, "public void ApplyInitialSelections()");
        AssertContains(controllerBindingsText, "_context.FormatComboBox.SelectedItem = _context.ViewModel.SelectedRecordingFormat;");
        AssertContains(controllerBindingsText, "_context.CustomBitrateNumberBox.Value = _context.ViewModel.CustomBitrateMbps;");
        AssertContains(controllerBindingsText, "_context.TrueHdrPreviewToggle.IsChecked = _context.ViewModel.IsTrueHdrPreviewEnabled;");
        AssertContains(controllerBindingsText, "_context.ApplyInitialDecoderCountSelection();");
        AssertContains(controllerBindingsText, "_context.ApplyBitrateVisibility();");
        AssertContains(controllerBindingsText, "_context.ApplyHdrToggleEnabledState();");
        AssertContains(controllerBindingsText, "public void EnsureInitialSelections()");
        AssertContains(controllerBindingsText, "_context.EnsureSplitEncodeModeSelection();");
        AssertContains(controllerBindingsText, "_context.UpdateDecoderCountVisibility();");
        AssertContains(controllerBindingsText, "public void AttachCaptureModeSelectionBindings()");
        AssertContains(controllerBindingsText, "_context.ResolutionComboBox.SelectionChanged +=");
        AssertContains(controllerBindingsText, "_context.FrameRateComboBox.SelectionChanged +=");
        AssertContains(controllerBindingsText, "!string.Equals(resolution.Value, _context.ViewModel.SelectedResolution, StringComparison.OrdinalIgnoreCase)");
        AssertContains(controllerBindingsText, "if (CaptureComboBoxSelectionNormalizer.IsAutoFrameRateOption(frameRate))");
        AssertContains(controllerBindingsText, "if (!_context.ViewModel.IsAutoFrameRateSelected)");
        AssertContains(controllerBindingsText, "else if (!CaptureComboBoxSelectionNormalizer.IsFrameRateMatch(frameRate.Value, _context.ViewModel.SelectedFrameRate))");
        AssertContains(controllerBindingsText, "public void AttachRecordingOptionBindings()");
        AssertContains(controllerBindingsText, "AttachStringSelection(_context.FormatComboBox, value => _context.ViewModel.SelectedRecordingFormat = value);");
        AssertContains(controllerBindingsText, "AttachStringSelection(_context.QualityComboBox, value => _context.ViewModel.SelectedQuality = value);");
        AssertContains(controllerBindingsText, "AttachStringSelection(_context.PresetComboBox, value => _context.ViewModel.SelectedPreset = value);");
        AssertContains(controllerBindingsText, "AttachStringSelection(_context.SplitEncodeComboBox, value => _context.ViewModel.SelectedSplitEncodeMode = value);");
        AssertContains(controllerBindingsText, "_context.VideoFormatComboBox.SelectionChanged +=");
        AssertContains(controllerBindingsText, "_context.CustomBitrateNumberBox.ValueChanged +=");
        AssertContains(controllerBindingsText, "_context.HdrToggle.Click +=");
        AssertContains(controllerBindingsText, "_context.TrueHdrPreviewToggle.Click +=");
        AssertContains(controllerPropertyChangesText, "public bool TryHandlePropertyChanged(string propertyName)");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.AudioClipping):");
        AssertContains(controllerPropertyChangesText, "_context.ApplyAudioClipVisibility();");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.IsHdrAvailable):");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.SourceIsHdr):");
        AssertContains(controllerPropertyChangesText, "_context.ApplyHdrToggleEnabledState();");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.IsHdrEnabled):");
        AssertContains(controllerPropertyChangesText, "HandleHdrEnabledChanged();");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.IsTrueHdrPreviewEnabled):");
        AssertContains(controllerPropertyChangesText, "HandleTrueHdrPreviewEnabledChanged();");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.HdrResolutionSupportHint):");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.HdrReadinessReason):");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.HdrRuntimeState):");
        AssertContains(controllerPropertyChangesText, "_context.RefreshHdrHintText();");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.SourceTelemetrySummaryText):");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.SourceTargetSummaryText):");
        AssertContains(controllerPropertyChangesText, "_context.UpdateFpsTelemetryTooltip();");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.SourceWidth):");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.SourceHeight):");
        AssertContains(controllerPropertyChangesText, "_context.UpdateVideoContentOverlays();");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.IsCustomBitrateVisible):");
        AssertContains(controllerPropertyChangesText, "_context.ApplyBitrateVisibility();");
        AssertContains(controllerPropertyChangesText, "case nameof(MainViewModel.CustomBitrateMbps):");
        AssertContains(controllerPropertyChangesText, "public void HandleCustomBitratePropertyChanged()");
        AssertContains(controllerPropertyChangesText, "public void HandleHdrEnabledChanged()");
        AssertContains(controllerPropertyChangesText, "public void HandleTrueHdrPreviewEnabledChanged()");
        AssertContains(controllerBindingsText, "private void AttachHdrToggleBindings()");
        AssertContains(controllerBindingsText, "private static void AttachStringSelection(ComboBox comboBox, Action<string> setVmProp)");
        AssertDoesNotContain(controllerText, "private static bool IsFrameRateMatch(double a, double b, double tolerance = 0.01)");
        AssertDoesNotContain(controllerText, "private static bool IsAutoFrameRateOption(FrameRateOption option)");

        AssertContains(bindingsText, "InitializeCaptureOptionCollections();");
        AssertContains(bindingsText, "ApplyInitialCaptureOptionSelections();");
        AssertContains(bindingsText, "EnsureInitialCaptureOptionSelections();");
        AssertContains(bindingsText, "AttachCaptureModeSelectionBindings();");
        AssertContains(bindingsText, "AttachRecordingOptionBindings();");
        AssertOccursBefore(bindingsText, "InitializeCaptureOptionCollections();", "ApplyInitialCaptureOptionSelections();");
        AssertOccursBefore(bindingsText, "ApplyInitialCaptureOptionSelections();", "AttachRecordingOptionBindings();");
        AssertOccursBefore(bindingsText, "EnsureInitialCaptureOptionSelections();", "AttachCaptureModeSelectionBindings();");
        AssertOccursBefore(bindingsText, "AttachCaptureModeSelectionBindings();", "AttachRecordingOptionBindings();");
        AssertDoesNotContain(selectionBindingFamilyText, "public void AttachRecordingStringSelectionBindings()");
        AssertDoesNotContain(selectionBindingFamilyText, "AttachStringSelection(_context.FormatComboBox, value => _context.ViewModel.SelectedRecordingFormat = value);");
        AssertDoesNotContain(selectionBindingFamilyText, "private static void AttachStringSelection(ComboBox comboBox, Action<string> setVmProp)");

        AssertContains(agentMapText, "`Sussudio/Controllers/Capture/CaptureOptionBindingController.cs` owns the");
        AssertContains(agentMapText, "`Sussudio/Controllers/Capture/CaptureOptionBindingController.Bindings.cs`");
        AssertContains(agentMapText, "owns setup and UI event attachment: initialization, resolution/frame-rate");
        AssertContains(agentMapText, "`Sussudio/Controllers/Capture/CaptureOptionBindingController.PropertyChanges.cs`");
        AssertContains(agentMapText, "owns capture-option/source-signal property-change routing");
        AssertContains(agentMapText, "`Sussudio/MainWindow.CaptureOptionBindings.cs` is the XAML-facing adapter");
        AssertContains(agentMapText, "option binding adapter context");
        AssertContains(agentMapText, "selection, recording option event bindings, show-all binding");
        AssertContains(agentMapText, "bindings, show-all binding, HDR/");
        AssertContains(agentMapText, "delegated presentation callbacks for option");
        AssertContains(agentMapText, "affordances, telemetry tooltips, and source overlay refreshes");
        AssertDoesNotContain(agentMapText, "CaptureOptionBindingController.Context.cs");
        AssertContains(cleanupPlanText, "`Sussudio/Controllers/Capture/CaptureOptionBindingController.cs` keeps the");
        AssertContains(cleanupPlanText, "`CaptureOptionBindingController.Bindings.cs`");
        AssertContains(cleanupPlanText, "`CaptureOptionBindingController.PropertyChanges.cs`");
        AssertContains(cleanupPlanText, "capture-option binding adapter context");
        AssertContains(cleanupPlanText, "owns video-format and initial decoder projection, initial selection");
        AssertContains(cleanupPlanText, "resolution/frame-rate selection handlers, recording option event bindings for");
        AssertContains(cleanupPlanText, "format, quality, preset, split-encode, video format, and custom bitrate");
        AssertContains(cleanupPlanText, "owns capture-option/source-");
        AssertContains(cleanupPlanText, "signal property-change routing, custom-bitrate property-change value");
        AssertContains(cleanupPlanText, "presentation callback routing for option affordances,");
        AssertContains(cleanupPlanText, "telemetry tooltips, and source overlay refreshes");
        AssertContains(cleanupPlanText, "`Sussudio/MainWindow.CaptureOptionBindings.cs` now owns the XAML-facing");
        AssertDoesNotContain(cleanupPlanText, "CaptureOptionBindingController.Context.cs");

        AssertDoesNotContain(captureOptionBindingsText, "VideoFormatComboBox.ItemsSource = ViewModel.AvailableVideoFormats;");
        AssertDoesNotContain(captureOptionBindingsText, "ResolutionComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "FrameRateComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "ViewModel.SelectedFrameRate =");
        AssertDoesNotContain(captureOptionBindingsWithoutVideoFormat, "FormatComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "VideoFormatComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "CustomBitrateNumberBox.ValueChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "HdrToggle.Click +=");
        AssertDoesNotContain(captureOptionBindingsText, "TrueHdrPreviewToggle.Click +=");
        AssertDoesNotContain(captureOptionBindingsText, "ViewModel.SelectedRecordingFormat =");
        AssertDoesNotContain(captureOptionBindingsText, "QualityComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "PresetComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "SplitEncodeComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionPropertyChangedMethod, "HandleCustomBitratePropertyChanged();");
        AssertDoesNotContain(captureOptionPropertyChangedMethod, "HandleHdrEnabledChanged();");
        AssertDoesNotContain(captureOptionPropertyChangedMethod, "HandleTrueHdrPreviewEnabledChanged();");
        AssertDoesNotContain(captureOptionPropertyChangedMethod, "HandleShowAllCaptureOptionsChanged();");
        AssertDoesNotContain(captureOptionPropertyChangedMethod, "HdrToggle.IsChecked = ViewModel.IsHdrEnabled;");
        AssertDoesNotContain(captureOptionPropertyChangedMethod, "TrueHdrPreviewToggle.IsChecked = ViewModel.IsTrueHdrPreviewEnabled;");
        AssertDoesNotContain(captureOptionPropertyChangedMethod, "_previewRendererHostController.SetHdrPassthroughEnabled(ViewModel.IsTrueHdrPreviewEnabled);");
        AssertDoesNotContain(captureOptionPropertyChangedMethod, "ShowAllCaptureOptionsToggle.IsChecked = ViewModel.ShowAllCaptureOptions;");
        AssertDoesNotContain(propertyChangedText, "CustomBitrateNumberBox.Value");
        AssertDoesNotContain(propertyChangedText, "Math.Abs(CustomBitrateNumberBox.Value - ViewModel.CustomBitrateMbps) > 0.01");
        AssertContains(propertyChangedText, "TryHandleCaptureOption = TryHandleCaptureOptionPropertyChanged,");
        AssertDoesNotContain(bindingsText, "ResolutionComboBox.SelectionChanged +=");
        AssertDoesNotContain(bindingsText, "FrameRateComboBox.SelectionChanged +=");
        AssertDoesNotContain(bindingsText, "FormatComboBox.SelectionChanged +=");
        AssertDoesNotContain(bindingsText, "CustomBitrateNumberBox.ValueChanged +=");
        AssertDoesNotContain(bindingsText, "HdrToggle.Click +=");
        AssertDoesNotContain(bindingsText, "ShowAllCaptureOptionsToggle.Click +=");
        AssertDoesNotContain(bindingsText, "ShowAllCaptureOptionsToggle.IsChecked = ViewModel.ShowAllCaptureOptions;");

        return Task.CompletedTask;
    }
}
