static partial class Program
{
    private static void AssertDiagnosticsRefreshFlashbackRecordingAndStorageAlertCoverage(
        AutomationDiagnosticsHubSourceFamily diagnostics,
        AutomationDiagnosticsHubCountersSourceFamily counters)
    {
        AssertContains(diagnostics.SourceFamilyText, "\"flashback-export-stalled\"");
        AssertContains(diagnostics.SourceFamilyText, "DiagnosticsCategory.Flashback");
        AssertContains(diagnostics.SourceFamilyText, "health.FlashbackExportActive");
        AssertContains(diagnostics.SourceFamilyText, "Math.Max(0, snapshot.FlashbackExportLastProgressAgeMs)");
        AssertContains(diagnostics.SourceFamilyText, "Math.Max(0, health.FlashbackExportLastProgressAgeMs)");
        AssertContains(diagnostics.SourceFamilyText, "elapsedMs={health.FlashbackExportElapsedMs}");
        AssertContains(diagnostics.SourceFamilyText, "throughputBps={health.FlashbackExportThroughputBytesPerSec:0.##}");
        AssertContains(diagnostics.SourceFamilyText, "kind={exportFailureKind}");
        AssertContains(diagnostics.SourceFamilyText, "private const int FlashbackExportStallThresholdMs = 30000;");
        AssertContains(diagnostics.FlashbackRecordingAlertsExportText, "exportLastProgressAgeMs >= FlashbackExportStallThresholdMs");
        AssertContains(diagnostics.SourceFamilyText, "\"Flashback export progress is stalled.\"");
        AssertContains(diagnostics.SourceFamilyText, "$\"{lanes.Export} progressAgeMs={exportLastProgressAgeMs}\"");
        AssertContains(diagnostics.SourceFamilyText, "private long _lastFlashbackExportCompletionEventId;");
        AssertContains(diagnostics.SourceFamilyText, "ObserveFlashbackExportCompletion(snapshot);");
        AssertContains(diagnostics.SourceFamilyText, "private void ObserveFlashbackExportCompletion(AutomationSnapshot snapshot)");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.FlashbackExportCompletedUtcUnixMs <= 0");
        AssertContains(diagnostics.SourceFamilyText, "Interlocked.CompareExchange(\n                ref _lastFlashbackExportCompletionEventId");
        AssertContains(diagnostics.SourceFamilyText, "status.Equals(\"Succeeded\", StringComparison.OrdinalIgnoreCase)");
        AssertContains(diagnostics.SourceFamilyText, "status.Equals(\"Cancelled\", StringComparison.OrdinalIgnoreCase)");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.FlashbackExportFailureKind");
        AssertContains(diagnostics.SourceFamilyText, "FlashbackBackendSettingsStale = flashbackRecordingFlattening.Backend.SettingsStale,");
        AssertContains(diagnostics.SourceFamilyText, "SettingsStale = flashbackRecording.BackendSettingsStale,");
        AssertContains(diagnostics.SourceFamilyText, "BackendSettingsStale = health.FlashbackBackendSettingsStale,");
        AssertContains(diagnostics.SourceFamilyText, "backendStale={health.FlashbackBackendSettingsStale}");
        AssertContains(diagnostics.SourceFamilyText, "kind={failureKind}");
        AssertContains(diagnostics.SourceFamilyText, "Flashback export completed: status={status}");
        AssertContains(diagnostics.SourceFamilyText, "private const long FlashbackTempDriveLowFreeBytes = 5L * 1024L * 1024L * 1024L;");
        AssertContains(diagnostics.SourceFamilyText, "private const long FlashbackRecordingBackpressureWarningMs = 100;");
        AssertContains(diagnostics.SourceFamilyText, "private const double FlashbackRecordingQueueDepthWarningRatio = 0.75;");
        AssertContains(diagnostics.SourceFamilyText, "private const double FlashbackAudioQueueDepthWarningRatio = 0.90;");
        AssertContains(diagnostics.SourceFamilyText, "private const long FlashbackRecordingQueueAgeWarningMs = 500;");
        AssertContains(diagnostics.FlashbackRecordingAlertsStorageText, "\"flashback-temp-cache-pressure\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsStorageText, "snapshot.FlashbackStartupCacheOverBudget");
        AssertContains(diagnostics.FlashbackRecordingAlertsStorageText, "snapshot.FlashbackTempDriveFreeBytes < FlashbackTempDriveLowFreeBytes");
        AssertContains(diagnostics.SourceFamilyText, "\"flashback_storage\"");
        AssertContains(diagnostics.SourceFamilyText, "\"Flashback temp storage is under pressure.\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsEncoderText, "\"flashback-encoding-failed\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsEncoderText, "snapshot.FlashbackEncodingFailed");
        AssertContains(diagnostics.FlashbackRecordingAlertsEncoderText, "Flashback encoder failed: type={snapshot.FlashbackEncodingFailureType ?? \"Unknown\"}");
        AssertContains(diagnostics.FlashbackRecordingAlertsDegradationText, "\"flashback-recording-degraded\"");
        AssertContains(counters.FlashbackRecordingText, "private FlashbackRecordingRecentCounters UpdateFlashbackRecordingRecentCounters(");
        AssertContains(counters.FlashbackRecordingText, "Interlocked.Exchange(ref _lastFlashbackVideoSequenceGaps, sequenceGaps)");
        AssertContains(counters.FlashbackRecordingText, "Interlocked.Exchange(ref _lastFlashbackGpuFramesDropped, gpuFramesDropped)");
        AssertContains(counters.FlashbackRecordingText, "Interlocked.Exchange(ref _lastFlashbackVideoBackpressureEvents, backpressureEvents)");
        AssertDoesNotContain(counters.FlashbackRecordingText, "private D3DRendererRecentCounters UpdateD3DRendererRecentCounters(");
        AssertDoesNotContain(counters.FlashbackRecordingText, "private MjpegRecentCounters UpdateMjpegRecentCounters(");
        AssertContains(diagnostics.SourceFamilyText, "var recentFlashbackRecording = UpdateFlashbackRecordingRecentCounters(health, nowTick);");
        AssertContains(diagnostics.SourceFamilyText, "UpdateAlerts(snapshot, recentFlashbackRecording);");
        AssertContains(diagnostics.SourceFamilyText, "private void UpdateAlerts(AutomationSnapshot snapshot, FlashbackRecordingRecentCounters flashbackRecordingRecent)");
        AssertContains(diagnostics.SourceFamilyText, "var flashbackRecordingQueueBacklog =");
        AssertContains(diagnostics.SourceFamilyText, "var flashbackAudioQueueBacklog =");
        AssertContains(diagnostics.SourceFamilyText, "IsFlashbackRecordingQueueBackedUp(");
        AssertContains(diagnostics.SourceFamilyText, "IsFlashbackAudioQueueBackedUp(");
        AssertContains(diagnostics.SourceFamilyText, "flashbackRecordingRecentForceRotateGap");
        AssertContains(diagnostics.SourceFamilyText, "IsFlashbackForceRotateRejectReason(snapshot.FlashbackVideoQueueLastRejectReason)");
        AssertContains(diagnostics.SourceFamilyText, "flashbackRecordingRecent.SequenceGaps > 0");
        AssertContains(diagnostics.FlashbackRecordingAlertsDegradationText, "(flashbackRecordingRecent.SequenceGaps > 0 && !flashbackRecordingRecentForceRotateGap)");
        AssertContains(diagnostics.FlashbackRecordingAlertsDegradationText, "flashbackRecordingRecent.GpuFramesDropped > 0");
        AssertContains(diagnostics.FlashbackRecordingAlertsDegradationText, "flashbackRecordingRecentBackpressure");
        AssertContains(diagnostics.FlashbackRecordingAlertsDegradationText, "flashbackRecordingQueueBacklog");
        AssertContains(diagnostics.FlashbackRecordingAlertsDegradationText, "flashbackAudioQueueBacklog");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "snapshot.FlashbackVideoBackpressureLastWaitMs >= FlashbackRecordingBackpressureWarningMs");
        AssertContains(diagnostics.FlashbackRecordingAlertsDegradationText, "Flashback recording path degraded:");
        AssertContains(diagnostics.FlashbackRecordingAlertsExportText, "\"flashback-export-rotation-gap\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsExportText, "Flashback export rotation skipped live-edge frames:");
        AssertContains(diagnostics.SourceFamilyText, "forceRotate={snapshot.FlashbackForceRotateActive}");
        AssertContains(diagnostics.SourceFamilyText, "requested={snapshot.FlashbackForceRotateRequested} draining={snapshot.FlashbackForceRotateDraining}");
        AssertContains(diagnostics.SourceFamilyText, "FatalCleanupInProgress = flashbackRecordingFlattening.FatalCleanupInProgress");
        AssertContains(diagnostics.SourceFamilyText, "FatalCleanupInProgress = flashbackRecording.FatalCleanupInProgress");
        AssertContains(diagnostics.SourceFamilyText, "FatalCleanupInProgress = health.FatalCleanupInProgress");
        AssertContains(diagnostics.SourceFamilyText, "FlashbackCleanupInProgress = flashbackRecordingFlattening.CleanupInProgress");
        AssertContains(diagnostics.SourceFamilyText, "CleanupInProgress = flashbackRecording.CleanupInProgress");
        AssertContains(diagnostics.SourceFamilyText, "CleanupInProgress = health.FlashbackCleanupInProgress");
        AssertContains(diagnostics.SourceFamilyText, "recentBackpressureEvents={flashbackRecordingRecent.BackpressureEvents}");
        AssertContains(diagnostics.SourceFamilyText, "private static bool IsFlashbackRecordingQueueBackedUp(");
        AssertContains(diagnostics.SourceFamilyText, "queueDepth >= Math.Ceiling(queueCapacity * FlashbackRecordingQueueDepthWarningRatio)");
        AssertContains(diagnostics.SourceFamilyText, "oldestFrameAgeMs >= FlashbackRecordingQueueAgeWarningMs");
        AssertContains(diagnostics.SourceFamilyText, "private static bool IsFlashbackAudioQueueBackedUp(int queueDepth, int queueCapacity)");
        AssertContains(diagnostics.SourceFamilyText, "queueDepth >= Math.Ceiling(queueCapacity * FlashbackAudioQueueDepthWarningRatio)");
        AssertContains(diagnostics.SourceFamilyText, "private static bool IsFlashbackForceRotateRejectReason(string? reason)");
        AssertContains(diagnostics.SourceFamilyText, "string.Equals(reason, \"force_rotate_queue_guard\"");
        AssertContains(diagnostics.SourceFamilyText, "flashback recording active={health.FlashbackActive}");
        AssertContains(diagnostics.SourceFamilyText, "fatalCleanup={health.FatalCleanupInProgress} flashbackCleanup={health.FlashbackCleanupInProgress}");
        AssertContains(diagnostics.SourceFamilyText, "var recordingIntegrityIncomplete =");
        AssertContains(diagnostics.SourceFamilyText, "string.Equals(captureRuntime.RecordingIntegrityStatus, \"Incomplete\", StringComparison.OrdinalIgnoreCase)");
        AssertContains(diagnostics.SourceFamilyText, "(recordingIntegrityIncomplete && !isRecording)");
        AssertContains(diagnostics.SourceFamilyText, "var flashbackRecordingDegraded =");
        AssertContains(diagnostics.SourceFamilyText, "recentFlashbackRecording.EncoderDroppedFrames > 0");
        AssertContains(diagnostics.SourceFamilyText, "recentFlashbackRecording.BackpressureEvents > 0");
        AssertContains(diagnostics.SourceFamilyText, "health.FlashbackVideoBackpressureLastWaitMs >= FlashbackRecordingBackpressureWarningMs");
        AssertContains(diagnostics.SourceFamilyText, "var flashbackBackendSettingsUnexpectedlyStale =");
        AssertContains(diagnostics.SourceFamilyText, "health.FlashbackBackendSettingsStale &&\n            !isRecording");
        AssertContains(diagnostics.SourceFamilyText, "\"Flashback backend settings differ from requested settings.\"");
        AssertContains(diagnostics.SourceFamilyText, "health.FlashbackVideoQueueDepth,\n                 health.FlashbackVideoQueueCapacity,\n                 health.FlashbackVideoQueueOldestFrameAgeMs");
        AssertContains(diagnostics.SourceFamilyText, "forceRotate={health.FlashbackForceRotateActive}");
        AssertContains(diagnostics.SourceFamilyText, "queueRejects={health.FlashbackVideoQueueRejectedFrames}");
        AssertContains(diagnostics.SourceFamilyText, "audioQueue={health.FlashbackAudioQueueDepth}/{health.FlashbackAudioQueueCapacity}");
        AssertContains(diagnostics.SourceFamilyText, "lastReject={health.FlashbackVideoQueueLastRejectReason ?? \"None\"}");
        AssertContains(diagnostics.SourceFamilyText, "flashbackExportRotationGap");
        AssertContains(diagnostics.SourceFamilyText, "\"Flashback export rotation skipped live-edge frames.\"");
        AssertContains(diagnostics.SourceFamilyText, "requested={health.FlashbackForceRotateRequested} draining={health.FlashbackForceRotateDraining}");
        AssertContains(diagnostics.SourceFamilyText, "\"flashback_recording\"");
        AssertContains(diagnostics.SourceFamilyText, "\"Flashback encoder has failed.\"");
        AssertContains(diagnostics.SourceFamilyText, "\"Flashback recording path is dropping or backing up.\"");
        AssertContains(diagnostics.SourceFamilyText, "\"flashback_export\"");
        AssertContains(diagnostics.SourceFamilyText, "var flashbackForceRotateRejectWithoutDamage =");
        AssertContains(diagnostics.SourceFamilyText, "!flashbackForceRotateRejectWithoutDamage &&\n              recentFlashbackRecording.SequenceGaps > 0");
        AssertContains(diagnostics.SourceFamilyText, "health.FlashbackExportActive ||\n             health.FlashbackForceRotateActive ||\n             health.FlashbackForceRotateRequested ||\n             health.FlashbackForceRotateDraining");
    }
}
