static partial class Program
{
    private static void AssertDiagnosticsSnapshotStatusProjectionOwnership(AutomationDiagnosticsHubSourceFamily diagnostics)
    {
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var snapshotStatus = BuildSnapshotStatusProjection(viewModelSnapshot, captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionSnapshotStatusText, "private SnapshotStatusProjection BuildSnapshotStatusProjection(");
        AssertContains(diagnostics.SnapshotProjectionSnapshotStatusText, "VerificationInProgress = Volatile.Read(ref _verificationInProgress) != 0,");
        AssertContains(diagnostics.SnapshotProjectionSnapshotStatusText, "SessionState = captureRuntime.SessionState,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "TimestampUtc = DateTimeOffset.UtcNow,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "VerificationInProgress = Volatile.Read(ref _verificationInProgress) != 0,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "SessionState = captureRuntime.SessionState,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "StatusText = viewModelSnapshot.StatusText,");
    }

    private static void AssertDiagnosticsRefreshSnapshotProjectionOwnership(AutomationDiagnosticsHubSourceFamily diagnostics)
    {
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var snapshotEvaluation = BuildSnapshotEvaluationProjection(performance, diagnostic, previewPacingClassification);");
        AssertContains(diagnostics.SnapshotProjectionSnapshotEvaluationText, "private SnapshotEvaluationProjection BuildSnapshotEvaluationProjection(");
        AssertContains(diagnostics.SnapshotProjectionSnapshotEvaluationText, "PerformanceScore = performance.Score,");
        AssertContains(diagnostics.SnapshotProjectionSnapshotEvaluationText, "DiagnosticHealthStatus = diagnostic.HealthStatus,");
        AssertContains(diagnostics.SnapshotProjectionSnapshotEvaluationText, "PreviewPacingLikelySlowStage = previewPacingClassification.LikelySlowStage,");
        AssertContains(diagnostics.SnapshotProjectionSnapshotEvaluationText, "PerformanceThresholdCaptureDropPercent = _perfectionCaptureDropPercentThreshold,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "PerformanceScore = performance.Score,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "PreviewPacingLikelySlowStage = previewPacingClassification.LikelySlowStage");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "PerformanceThresholdCaptureDropPercent = _perfectionCaptureDropPercentThreshold,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var audioAndIngest = BuildAudioAndIngestProjection(viewModelSnapshot, captureRuntime, audioSignal);");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var audioDrops = BuildAudioDropsProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionAudioText, "private static AudioDropsProjection BuildAudioDropsProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionAudioText, "QueueDropsRealtime = health.AudioDropsQueueSaturated + health.AudioDropsBacklogEviction,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "AudioQueueDropsRealtime = audioDrops.QueueDropsRealtime,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "AudioDropsQueueSaturated = health.AudioDropsQueueSaturated,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "AudioQueueDropsRealtime = health.AudioDropsQueueSaturated + health.AudioDropsBacklogEviction,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var captureFormat = BuildCaptureFormatProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var sourceTelemetry = BuildSourceTelemetryProjection(viewModelSnapshot, captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var sourceFlattening = BuildSourceFlattenedProjection(sourceSignal, sourceTelemetry);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "DetectedSourceFrameRate = sourceFlattening.DetectedSourceFrameRate,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "SourceTelemetryAvailability = sourceFlattening.SourceTelemetryAvailability,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningSourceText, "DetectedSourceFrameRate = sourceSignal.DetectedFrameRate,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningSourceText, "SourceTelemetryAvailability = sourceTelemetry.SourceTelemetryAvailability,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "DetectedSourceFrameRate = sourceSignal.DetectedFrameRate,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "SourceTelemetryAvailability = sourceTelemetry.SourceTelemetryAvailability,");
        AssertDiagnosticsPreviewRuntimeProjectionOwnership(diagnostics);
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var previewD3D = BuildPreviewD3DProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "private static PreviewD3DProjection BuildPreviewD3DProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "var cpuTiming = BuildPreviewD3DCpuTimingProjection(previewRuntime);");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "CpuTiming = cpuTiming,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DCpuTimingText, "private static PreviewD3DCpuTimingProjection BuildPreviewD3DCpuTimingProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DCpuTimingText, "InputUploadP99Ms = previewRuntime.D3DInputUploadCpuP99Ms,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionPreviewD3DCpuTimingText, "PipelineLatencyMaxMs = previewRuntime.D3DPipelineLatencyMaxMs");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "var pipelineLatency = BuildPreviewD3DPipelineLatencyProjection(previewRuntime);");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "PipelineLatency = pipelineLatency,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DPipelineLatencyText, "private static PreviewD3DPipelineLatencyProjection BuildPreviewD3DPipelineLatencyProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DPipelineLatencyText, "SampleCount = previewRuntime.D3DPipelineLatencySampleCount,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DPipelineLatencyText, "MaxMs = previewRuntime.D3DPipelineLatencyMaxMs");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "var frameFlow = BuildPreviewD3DFrameFlowProjection(previewRuntime);");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "FrameFlow = frameFlow");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameFlowText, "private static PreviewD3DFrameFlowProjection BuildPreviewD3DFrameFlowProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameFlowText, "LastRenderedPipelineLatencyMs = previewRuntime.D3DLastRenderedPipelineLatencyMs,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameFlowText, "RecentSlowFrames = previewRuntime.D3DRecentSlowFrames");
        AssertDoesNotContain(diagnostics.SnapshotProjectionPreviewD3DText, "private static PreviewD3DFrameFlowProjection BuildPreviewD3DFrameFlowProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "var frameLatencyWait = BuildPreviewD3DFrameLatencyWaitProjection(previewRuntime);");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "var frameStats = BuildPreviewD3DFrameStatsProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "FrameLatencyWait = frameLatencyWait,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameLatencyWaitText, "private static PreviewD3DFrameLatencyWaitProjection BuildPreviewD3DFrameLatencyWaitProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameLatencyWaitText, "TimeoutCount = previewRuntime.D3DFrameLatencyWaitTimeoutCount,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionPreviewD3DText, "private static PreviewD3DFrameLatencyWaitProjection BuildPreviewD3DFrameLatencyWaitProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var previewD3DFlattening = BuildPreviewD3DFlattenedProjection(previewD3D);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "PreviewD3DInputUploadCpuP99Ms = previewD3DFlattening.InputUploadCpuP99Ms,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "PreviewD3DRecentSlowFrames = previewD3DFlattening.RecentSlowFrames,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningPreviewD3DText, "private static PreviewD3DFlattenedProjection BuildPreviewD3DFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningPreviewD3DText, "InputUploadCpuP99Ms = previewD3D.CpuTiming.InputUploadP99Ms,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningPreviewD3DText, "RecentSlowFrames = previewD3D.FrameFlow.RecentSlowFrames");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "PreviewD3DInputUploadCpuP99Ms = previewD3D.CpuTiming.InputUploadP99Ms,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "PreviewD3DRecentSlowFrames = previewD3D.FrameFlow.RecentSlowFrames,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "FrameStats = frameStats,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameStatsText, "private static PreviewD3DFrameStatsProjection BuildPreviewD3DFrameStatsProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameStatsText, "RecentMissedRefreshCount = recentD3DMissedRefreshes,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionPreviewD3DText, "private static PreviewD3DFrameStatsProjection BuildPreviewD3DFrameStatsProjection(");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "PreviewD3DFrameStatsRecentMissedRefreshCount = recentD3DMissedRefreshes,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var flashbackExport = BuildFlashbackExportProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackExportText, "private static FlashbackExportProjection BuildFlashbackExportProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionFlashbackExportText, "Active = health.FlashbackExportActive,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackExportText, "private static FlashbackExportLastResultProjection BuildFlashbackExportLastResultProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionFlashbackExportText, "LastExportId = health.LastExportId,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackExportText, "LastExportMessage = health.LastExportMessage");
        AssertContains(diagnostics.SnapshotProjectionFlashbackExportText, "private readonly record struct FlashbackExportLastResultProjection");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var flashbackExportFlattening = BuildFlashbackExportFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningFlashbackExportText, "Active = flashbackExport.Active,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningFlashbackExportText, "LastExportId = lastResult.LastExportId,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningFlashbackExportText, "LastExportMessage = lastResult.LastExportMessage");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "FlashbackExportActive = flashbackExportFlattening.Active,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "LastExportId = flashbackExportFlattening.LastExportId,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "FlashbackExportActive = health.FlashbackExportActive,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "FlashbackExportActive = flashbackExport.Active,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "LastExportId = flashbackExportLastResult.LastExportId,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var flashbackRecording = BuildFlashbackRecordingProjection(captureRuntime, health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "private static FlashbackRecordingProjection BuildFlashbackRecordingProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "var startupCache = BuildFlashbackRecordingStartupCacheProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "StartupCache = startupCache,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "private static FlashbackRecordingStartupCacheProjection BuildFlashbackRecordingStartupCacheProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "OverBudget = health.FlashbackStartupCacheOverBudget");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "var queues = BuildFlashbackRecordingQueuesProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "Queues = queues,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingQueuesText, "private static FlashbackRecordingQueuesProjection BuildFlashbackRecordingQueuesProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingQueuesText, "GpuQueueLastRejectReason = health.FlashbackGpuQueueLastRejectReason,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingQueuesText, "AudioQueueCapacity = health.FlashbackAudioQueueCapacity");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "FlashbackEncodingFailed = flashbackRecording.EncodingFailed,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "EncodingFailed = health.FlashbackEncodingFailed,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "ExportVerificationFormat = captureRuntime.FlashbackExportVerificationFormat ?? health.FlashbackExportVerificationFormat,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "FlashbackEncodingFailed = health.FlashbackEncodingFailed,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "FlashbackExportVerificationFormat = captureRuntime.FlashbackExportVerificationFormat ?? health.FlashbackExportVerificationFormat,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var flashbackPlayback = BuildFlashbackPlaybackProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "private static FlashbackPlaybackProjection BuildFlashbackPlaybackProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "var audioMaster = BuildFlashbackPlaybackAudioMasterProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "var decode = BuildFlashbackPlaybackDecodeProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "var commands = BuildFlashbackPlaybackCommandProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "AudioMaster = audioMaster,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "Commands = commands");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "TargetFps = health.FlashbackPlaybackTargetFps,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "private static FlashbackPlaybackAudioMasterProjection BuildFlashbackPlaybackAudioMasterProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "LastFallbackReason = health.FlashbackPlaybackAudioMasterLastFallbackReason,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "private static FlashbackPlaybackDecodeProjection BuildFlashbackPlaybackDecodeProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "MaxPhase = health.FlashbackPlaybackMaxDecodePhase,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "SeekForwardDecodeCapHits = health.FlashbackPlaybackSeekForwardDecodeCapHits,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "private static FlashbackPlaybackCommandProjection BuildFlashbackPlaybackCommandProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "LastFailure = health.FlashbackPlaybackLastCommandFailure");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "FlashbackPlaybackTargetFps = health.FlashbackPlaybackTargetFps,");
        AssertContains(diagnostics.SnapshotProjectionAudioText, "private static AudioAndIngestProjection BuildAudioAndIngestProjection(");
        AssertContains(diagnostics.SnapshotProjectionAudioText, "var audioSignalProjection = BuildAudioSignalProjection(viewModelSnapshot, audioSignal);");
        AssertContains(diagnostics.SnapshotProjectionAudioText, "var captureIngest = BuildCaptureIngestProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionAudioText, "var wasapiAudio = BuildWasapiAudioProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionAudioText, "private static AudioSignalProjection BuildAudioSignalProjection(");
        AssertContains(diagnostics.SnapshotProjectionAudioText, "Peak = viewModelSnapshot.AudioPeak,");
        AssertContains(diagnostics.SnapshotProjectionCaptureIngestText, "private static CaptureIngestProjection BuildCaptureIngestProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionCaptureIngestText, "SourceReaderReadOutstanding = captureRuntime.SourceReaderReadOutstanding,");
        AssertContains(diagnostics.SnapshotProjectionWasapiAudioText, "private static WasapiAudioProjection BuildWasapiAudioProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionWasapiAudioText, "CaptureAudioLevelEventsFired = captureRuntime.WasapiCaptureAudioLevelEventsFired,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "AudioPeak = viewModelSnapshot.AudioPeak,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var captureCommands = BuildCaptureCommandProjection(viewModelSnapshot);");
        AssertContains(diagnostics.SnapshotProjectionCaptureCommandsText, "private static CaptureCommandProjection BuildCaptureCommandProjection(ViewModelRuntimeSnapshot viewModelSnapshot)");
        AssertContains(diagnostics.SnapshotProjectionCaptureCommandsText, "CommandsEnqueued = viewModelSnapshot.CaptureCommandCommandsEnqueued,");
        AssertContains(diagnostics.SnapshotProjectionCaptureCommandsText, "LastError = viewModelSnapshot.CaptureCommandLastError");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "CaptureCommandCommandsEnqueued = viewModelSnapshot.CaptureCommandCommandsEnqueued,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "CaptureCommandLastError = viewModelSnapshot.CaptureCommandLastError,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var userSettings = BuildUserSettingsProjection(viewModelSnapshot);");
        AssertContains(diagnostics.SnapshotProjectionUserSettingsText, "private static UserSettingsProjection BuildUserSettingsProjection(ViewModelRuntimeSnapshot viewModelSnapshot)");
        AssertContains(diagnostics.SnapshotProjectionUserSettingsText, "SelectedFriendlyFrameRate = viewModelSnapshot.SelectedFriendlyFrameRate ?? Math.Round(viewModelSnapshot.SelectedFrameRate),");
        AssertContains(diagnostics.SnapshotProjectionUserSettingsText, "IsStatsVisible = viewModelSnapshot.IsStatsVisible");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var settingsFlattening = BuildSettingsFlattenedProjection(userSettings, recordingSettings);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "SelectedDeviceId = settingsFlattening.SelectedDeviceId,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "IsStatsVisible = settingsFlattening.IsStatsVisible,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningSettingsText, "SelectedDeviceId = userSettings.SelectedDeviceId,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningSettingsText, "IsStatsVisible = userSettings.IsStatsVisible");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "SelectedDeviceId = viewModelSnapshot.SelectedDeviceId,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "SelectedFriendlyFrameRate = viewModelSnapshot.SelectedFriendlyFrameRate ?? Math.Round(viewModelSnapshot.SelectedFrameRate),");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var recordingSettings = BuildRecordingSettingsProjection(userSettings);");
        AssertContains(diagnostics.SnapshotProjectionUserSettingsText, "private static RecordingSettingsProjection BuildRecordingSettingsProjection(UserSettingsProjection userSettings)");
        AssertContains(diagnostics.SnapshotProjectionUserSettingsText, "SelectedRecordingFormat = userSettings.SelectedRecordingFormat,");
        AssertContains(diagnostics.SnapshotProjectionUserSettingsText, "CustomBitrateMbps = userSettings.CustomBitrateMbps");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "SelectedRecordingFormat = settingsFlattening.SelectedRecordingFormat,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningSettingsText, "SelectedRecordingFormat = recordingSettings.SelectedRecordingFormat,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "SelectedRecordingFormat = userSettings.SelectedRecordingFormat,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "CustomBitrateMbps = userSettings.CustomBitrateMbps,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "SelectedDeviceId = userSettings.SelectedDeviceId,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "SelectedRecordingFormat = recordingSettings.SelectedRecordingFormat,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var hdrPipeline = BuildHdrPipelineProjection(viewModelSnapshot, captureRuntime, hdrTruthVerdict);");
        AssertContains(diagnostics.SnapshotProjectionHdrPipelineText, "private static HdrPipelineProjection BuildHdrPipelineProjection(");
        AssertContains(diagnostics.SnapshotProjectionHdrPipelineText, "HdrRuntimeState = PreferViewModelHdrText(viewModelSnapshot.HdrRuntimeState, captureRuntime.HdrRuntimeState),");
        AssertContains(diagnostics.SnapshotProjectionHdrPipelineText, "TelemetryAlignmentReason = captureRuntime.TelemetryAlignmentReason");
        AssertContains(diagnostics.SnapshotProjectionHdrPipelineText, "TruthVerdict = truthVerdict");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "HdrRuntimeState = !string.IsNullOrWhiteSpace(viewModelSnapshot.HdrRuntimeState)");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "TelemetryAlignmentReason = captureRuntime.TelemetryAlignmentReason,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "var hdrTruth = BuildHdrTruthProjection(hdrTruthVerdict);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var hdrPipelineFlattening = BuildHdrPipelineFlattenedProjection(hdrPipeline);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "HdrTruthVerdict = hdrPipelineFlattening.TruthVerdict,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "TelemetryAlignmentReason = hdrPipelineFlattening.TelemetryAlignmentReason,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningHdrPipelineText, "HdrRuntimeState = hdrPipeline.HdrRuntimeState,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningHdrPipelineText, "TelemetryAlignmentReason = hdrPipeline.TelemetryAlignmentReason,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningHdrPipelineText, "TruthVerdict = hdrPipeline.TruthVerdict");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "HdrTruthVerdict = hdrPipeline.TruthVerdict,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "TelemetryAlignmentReason = hdrPipeline.TelemetryAlignmentReason,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "HdrTruthVerdict = hdrTruthVerdict,");
        AssertContains(diagnostics.SnapshotProjectionCaptureFormatText, "private static CaptureFormatProjection BuildCaptureFormatProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionCaptureFormatText, "NegotiatedWidth = captureRuntime.NegotiatedWidth ?? captureRuntime.ActualWidth,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var captureFormatFlattening = BuildCaptureFormatFlattenedProjection(captureFormat);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "NegotiatedWidth = captureFormatFlattening.NegotiatedWidth,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningCaptureFormatText, "private static CaptureFormatFlattenedProjection BuildCaptureFormatFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningCaptureFormatText, "NegotiatedWidth = captureFormat.NegotiatedWidth,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningCaptureFormatText, "EncoderVideoCodec = captureFormat.EncoderVideoCodec,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "NegotiatedWidth = captureFormat.NegotiatedWidth,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "EncoderVideoCodec = captureFormat.EncoderVideoCodec,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "NegotiatedWidth = captureRuntime.NegotiatedWidth ?? captureRuntime.ActualWidth,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var captureTransport = BuildCaptureTransportProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionCaptureTransportText, "private static CaptureTransportProjection BuildCaptureTransportProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionCaptureTransportText, "FrameLedgerRecentEvents = captureRuntime.FrameLedgerRecentEvents");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var captureTransportFlattening = BuildCaptureTransportFlattenedProjection(captureTransport);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "MemoryPreference = captureTransportFlattening.MemoryPreference,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "FrameLedgerRecentEvents = captureTransportFlattening.FrameLedgerRecentEvents,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningCaptureTransportText, "MemoryPreference = captureTransport.MemoryPreference,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningCaptureTransportText, "FrameLedgerRecentEvents = captureTransport.FrameLedgerRecentEvents");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "MemoryPreference = captureRuntime.MemoryPreference,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "FrameLedgerRecentEvents = captureRuntime.FrameLedgerRecentEvents,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "MemoryPreference = captureTransport.MemoryPreference,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "FrameLedgerRecentEvents = captureTransport.FrameLedgerRecentEvents,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var captureCadence = BuildCaptureCadenceProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionCaptureCadenceText, "private static CaptureCadenceProjection BuildCaptureCadenceProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionCaptureCadenceText, "EstimatedDroppedFrames = health.CaptureCadenceEstimatedDroppedFrames,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var captureCadenceFlattening = BuildCaptureCadenceFlattenedProjection(captureCadence);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningCaptureCadenceText, "ExpectedFrameRate = captureCadence.ExpectedFrameRate,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningCaptureCadenceText, "EstimatedDroppedFrames = captureCadence.EstimatedDroppedFrames");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "CaptureCadenceEstimatedDroppedFrames = captureCadenceFlattening.EstimatedDroppedFrames,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "CaptureCadenceEstimatedDroppedFrames = health.CaptureCadenceEstimatedDroppedFrames,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "VisualCenterCadenceRecentChangeIntervalsMs = health.VisualCenterCadenceRecentChangeIntervalsMs,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "CaptureCadenceEstimatedDroppedFrames = captureCadence.EstimatedDroppedFrames,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var visualCadence = BuildVisualCadenceProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionVisualCadenceText, "private static VisualCadenceProjection BuildVisualCadenceProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionVisualCadenceText, "CenterRecentChangeIntervalsMs = health.VisualCenterCadenceRecentChangeIntervalsMs");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var visualCadenceFlattening = BuildVisualCadenceFlattenedProjection(visualCadence);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningVisualCadenceText, "MotionConfidence = visualCadence.MotionConfidence,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningVisualCadenceText, "CenterRecentChangeIntervalsMs = visualCadence.CenterRecentChangeIntervalsMs");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "VisualCenterCadenceRecentChangeIntervalsMs = visualCadenceFlattening.CenterRecentChangeIntervalsMs,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCaptureCadenceText, "VisualCenterRecentChangeIntervalsMs = health.VisualCenterCadenceRecentChangeIntervalsMs");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "VisualCenterCadenceRecentChangeIntervalsMs = visualCadence.CenterRecentChangeIntervalsMs,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var mjpeg = BuildMjpegProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "private static MjpegProjection BuildMjpegProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "var timing = BuildMjpegTimingProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "Timing = timing,");
        AssertContains(diagnostics.SnapshotProjectionMjpegTimingText, "private static MjpegTimingProjection BuildMjpegTimingProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionMjpegTimingText, "DecodeSampleCount = health.MjpegDecodeSampleCount,");
        AssertContains(diagnostics.SnapshotProjectionMjpegTimingText, "PerDecoder = health.MjpegPerDecoder is { Length: > 0 } perDecoder");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "var previewJitter = BuildMjpegPreviewJitterProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "var packetHash = BuildMjpegPacketHashProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "PreviewJitter = previewJitter,");
        AssertContains(diagnostics.SnapshotProjectionMjpegPreviewJitterText, "private static MjpegPreviewJitterProjection BuildMjpegPreviewJitterProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionMjpegPreviewJitterText, "LastDropReason = health.MjpegPreviewJitterLastDropReason,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var mjpegPreviewJitterFlattening = BuildMjpegPreviewJitterFlattenedProjection(mjpeg.PreviewJitter);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegPreviewJitterText, "Enabled = previewJitter.Enabled,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegPreviewJitterText, "LastDropReason = previewJitter.LastDropReason,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegPreviewJitterText, "ScheduleLateCount = previewJitter.ScheduleLateCount");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "MjpegPreviewJitterLastDropReason = mjpegPreviewJitterFlattening.LastDropReason,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "MjpegPreviewJitterLastDropReason = mjpeg.PreviewJitter.LastDropReason,");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "PacketHash = packetHash,");
        AssertContains(diagnostics.SnapshotProjectionMjpegPacketHashText, "private static MjpegPacketHashProjection BuildMjpegPacketHashProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionMjpegPacketHashText, "Pattern = health.MjpegPacketHashPattern,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var mjpegPacketHashFlattening = BuildMjpegPacketHashFlattenedProjection(mjpeg.PacketHash);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegPacketHashText, "SampleCount = packetHash.SampleCount,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegPacketHashText, "Pattern = packetHash.Pattern,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegPacketHashText, "RecentDuplicateFlags = packetHash.RecentDuplicateFlags");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "MjpegPacketHashPattern = mjpegPacketHashFlattening.Pattern,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "MjpegPacketHashPattern = mjpeg.PacketHash.Pattern,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var mjpegTimingFlattening = BuildMjpegTimingFlattenedProjection(mjpeg.Timing);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegTimingText, "DecodeSampleCount = timing.DecodeSampleCount,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegTimingText, "PipelineMaxMs = timing.PipelineMaxMs,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegTimingText, "PerDecoder = timing.PerDecoder");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "MjpegDecodeSampleCount = mjpegTimingFlattening.DecodeSampleCount,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "MjpegPerDecoder = mjpegTimingFlattening.PerDecoder,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "MjpegDecodeSampleCount = mjpeg.Timing.DecodeSampleCount,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "MjpegPerDecoder = mjpeg.Timing.PerDecoder,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "MjpegPacketHashPattern = health.MjpegPacketHashPattern,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "MjpegPerDecoder = health.MjpegPerDecoder is { Length: > 0 } perDecoder");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var recordingIntegrity = BuildRecordingIntegrityProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionRecordingIntegrityText, "private static RecordingIntegrityProjection BuildRecordingIntegrityProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionRecordingIntegrityText, "Status = captureRuntime.RecordingIntegrityStatus,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var recordingIntegrityFlattening = BuildRecordingIntegrityFlattenedProjection(recordingIntegrity);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningRecordingIntegrityText, "Status = recordingIntegrity.Status,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningRecordingIntegrityText, "AudioFramesWrittenToSink = recordingIntegrity.AudioFramesWrittenToSink,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningRecordingIntegrityText, "EncoderAvSyncDriftMs = recordingIntegrity.EncoderAvSyncDriftMs,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "RecordingIntegrityStatus = recordingIntegrityFlattening.Status,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "RecordingIntegrityReason = recordingIntegrityFlattening.Reason,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "RecordingIntegrityStatus = captureRuntime.RecordingIntegrityStatus,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "RecordingIntegrityStatus = recordingIntegrity.Status,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "RecordingIntegrityReason = recordingIntegrity.Reason,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var recordingBackend = BuildRecordingBackendProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionRecordingOutputText, "private static RecordingBackendProjection BuildRecordingBackendProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionRecordingOutputText, "MuxResult = ResolveMuxResult(captureRuntime.MuxSucceeded)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "var recordingOutputFlattening = BuildRecordingOutputFlattenedProjection(recordingBackend, recordingOutput);");
        AssertContains(diagnostics.SnapshotProjectionFlatteningRecordingOutputText, "Backend = recordingBackend.Backend,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningRecordingOutputText, "MuxResult = recordingBackend.MuxResult,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "RecordingBackend = recordingOutputFlattening.Backend,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "RecordingBackend = captureRuntime.RecordingBackend,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "MuxResult = captureRuntime.MuxSucceeded.HasValue");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "RecordingBackend = recordingBackend.Backend,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "MuxResult = recordingBackend.MuxResult,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var recordingPipeline = BuildRecordingPipelineProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionRecordingPipelineText, "private static RecordingPipelineProjection BuildRecordingPipelineProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionRecordingPipelineText, "RecordingVideoQueueCapacity = health.RecordingVideoQueueCapacity,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "RecordingVideoQueueCapacity = health.RecordingVideoQueueCapacity,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var recordingOutput = BuildRecordingOutputProjection(");
        AssertContains(diagnostics.SnapshotProjectionRecordingOutputText, "private static RecordingOutputProjection BuildRecordingOutputProjection(");
        AssertContains(diagnostics.SnapshotProjectionRecordingOutputText, "RecordingVideoBytes = recordingStats.VideoBytes,");
        AssertContains(diagnostics.SnapshotProjectionRecordingOutputText, "LastOutputExists = lastOutput.Exists,");
        AssertContains(diagnostics.SnapshotProjectionRecordingOutputText, "LastVerification = lastVerification");
        AssertContains(diagnostics.SnapshotProjectionFlatteningRecordingOutputText, "RecordingVideoBytes = recordingOutput.RecordingVideoBytes,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningRecordingOutputText, "LastOutputExists = recordingOutput.LastOutputExists,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningRecordingOutputText, "LastVerification = recordingOutput.LastVerification");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "RecordingVideoBytes = recordingOutputFlattening.RecordingVideoBytes,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "LastVerification = recordingOutputFlattening.LastVerification,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "RecordingVideoBytes = recordingStats.VideoBytes,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "LastOutputExists = lastOutput.Exists,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "LastVerification = lastVerification,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "RecordingVideoBytes = recordingOutput.RecordingVideoBytes,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionFlatteningText, "LastVerification = recordingOutput.LastVerification,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var sourceSignal = BuildSourceSignalProjection(viewModelSnapshot, captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionSourceSignalText, "private static SourceSignalProjection BuildSourceSignalProjection(");
        AssertContains(diagnostics.SnapshotProjectionSourceSignalText, "FrameRateOrigin = ResolveSourceFrameRateOrigin(viewModelSnapshot.SourceFrameRateOrigin, captureRuntime.SourceFrameRateOrigin),");
        AssertContains(diagnostics.SnapshotProjectionSourceSignalText, "RawTimingHex = captureRuntime.SourceRawTimingHex");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "DetectedSourceFrameRate = viewModelSnapshot.DetectedSourceFrameRate ?? captureRuntime.DetectedSourceFrameRate,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "SourceRawTimingHex = captureRuntime.SourceRawTimingHex,");
        AssertContains(diagnostics.SnapshotProjectionSourceTelemetryText, "private static SourceTelemetryProjection BuildSourceTelemetryProjection(");
        AssertContains(diagnostics.SnapshotProjectionSourceTelemetryText, "PreferKnownTelemetryValue(");
        AssertContains(diagnostics.SnapshotProjectionSourceTelemetryText, "SourceTelemetryAgeSeconds = TelemetryAgeHelper.ComputeAgeSeconds(");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "SourceTelemetryAvailability = !string.IsNullOrWhiteSpace(viewModelSnapshot.SourceTelemetryAvailability)");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var processResourceProjection = BuildProcessResourceProjection(processResources);");
        AssertContains(diagnostics.SnapshotProjectionProcessResourcesText, "private static ProcessResourceProjection BuildProcessResourceProjection(ProcessResourceSnapshot processResources)");
        AssertContains(diagnostics.SnapshotProjectionProcessResourcesText, "MemoryWorkingSetMb = processResources.MemoryWorkingSetMb,");
        AssertContains(diagnostics.SnapshotProjectionProcessResourcesText, "ThreadPoolIoMax = processResources.ThreadPoolIoMax");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "MemoryWorkingSetMb = processResources.MemoryWorkingSetMb,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "ThreadPoolIoMax = processResources.ThreadPoolIoMax,");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "var avSync = BuildAvSyncProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionAvSyncText, "private static AvSyncProjection BuildAvSyncProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionAvSyncText, "CaptureDriftMs = captureRuntime.AvSyncCaptureDriftMs,");
        AssertContains(diagnostics.SnapshotProjectionAvSyncText, "EncoderCorrectionSamples = captureRuntime.AvSyncEncoderCorrectionSamples");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "AvSyncCaptureDriftMs = captureRuntime.AvSyncCaptureDriftMs,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionCompositionText, "AvSyncEncoderCorrectionSamples = captureRuntime.AvSyncEncoderCorrectionSamples,");
    }
}
