using System.Threading.Tasks;

static partial class Program
{
    internal static Task PreviewRuntimeD3DProjection_OwnsPolicyGroups()
    {
        var previewRuntimeD3DFrameCounterPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DFrameCounterPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DRendererStatePolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DRendererStatePolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DDisplayCadencePolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DDisplayCadencePolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DRenderCpuTimingPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DRenderCpuTimingPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DPipelineLatencyPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DPipelineLatencyPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DFrameOwnershipPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DFrameOwnershipPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DFrameStatisticsPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DFrameStatisticsPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DFrameLatencyWaitPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DFrameLatencyWaitPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionRendererStateText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.RendererState.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionDisplayCadenceText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.DisplayCadence.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionRenderCpuTimingText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.RenderCpuTiming.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionPipelineLatencyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.PipelineLatency.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionFrameOwnershipText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.FrameOwnership.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionFrameStatisticsText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.FrameStatistics.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionFrameLatencyWaitText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.FrameLatencyWait.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionBuilderText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.Builder.cs").Replace("\r\n", "\n");
        var agentMapText = ReadRepoFile("docs/architecture/AGENT_MAP.md").Replace("\r\n", "\n");
        var cleanupPlanText = ReadRepoFile("docs/architecture/cleanup-plan.md").Replace("\r\n", "\n");

        AssertContains(previewRuntimeD3DProjectionText, "internal sealed partial class PreviewRuntimeD3DProjection");
        AssertContains(previewRuntimeD3DProjectionText, "public bool GpuActive { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionText, "public long D3DFramesDropped { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionText, "private void ApplyFrameCounters(PreviewRuntimeD3DFrameCounters frameCounters)");
        AssertContains(previewRuntimeD3DProjectionText, "FramesArrived = frameCounters.FramesArrived;");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "DisplayCadenceRecentIntervalsMs");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "D3DInputUploadCpuAvgMs");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "D3DLastSubmittedPreviewPresentId");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "D3DFrameStatsPresentCount");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "D3DFrameLatencyWaitEnabled");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "GpuPlaybackState");
        AssertContains(previewRuntimeD3DProjectionRendererStateText, "internal sealed partial class PreviewRuntimeD3DProjection");
        AssertContains(previewRuntimeD3DProjectionRendererStateText, "public string RendererMode { get; private set; } = \"None\";");
        AssertContains(previewRuntimeD3DProjectionRendererStateText, "public PreviewSlowFrameDiagnostic[] D3DRecentSlowFrames { get; private set; } = Array.Empty<PreviewSlowFrameDiagnostic>();");
        AssertContains(previewRuntimeD3DProjectionRendererStateText, "public string GpuPlaybackState { get; private set; } = \"None\";");
        AssertContains(previewRuntimeD3DProjectionRendererStateText, "private void ApplyRendererState(PreviewRuntimeD3DRendererState rendererState)");
        AssertContains(previewRuntimeD3DProjectionRendererStateText, "GpuPlaybackState = rendererState.GpuPlaybackState;");
        AssertContains(previewRuntimeD3DProjectionDisplayCadenceText, "public double[] DisplayCadenceRecentIntervalsMs { get; private set; } = Array.Empty<double>();");
        AssertContains(previewRuntimeD3DProjectionDisplayCadenceText, "private void ApplyDisplayCadence(PreviewRuntimeD3DDisplayCadence displayCadence)");
        AssertContains(previewRuntimeD3DProjectionDisplayCadenceText, "DisplayCadenceRecentIntervalsMs = displayCadence.RecentIntervalsMs;");
        AssertContains(previewRuntimeD3DProjectionRenderCpuTimingText, "public double D3DInputUploadCpuAvgMs { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionRenderCpuTimingText, "private void ApplyRenderCpuTiming(PreviewRuntimeD3DRenderCpuTiming renderCpuTiming)");
        AssertContains(previewRuntimeD3DProjectionRenderCpuTimingText, "D3DInputUploadCpuAvgMs = renderCpuTiming.InputUploadAverageMs;");
        AssertContains(previewRuntimeD3DProjectionPipelineLatencyText, "public double EstimatedPipelineLatencyMs { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionPipelineLatencyText, "private void ApplyPipelineLatency(PreviewRuntimeD3DPipelineLatency pipelineLatency)");
        AssertContains(previewRuntimeD3DProjectionPipelineLatencyText, "EstimatedPipelineLatencyMs = pipelineLatency.EstimatedPipelineLatencyMs;");
        AssertContains(previewRuntimeD3DProjectionFrameOwnershipText, "public long D3DLastSubmittedPreviewPresentId { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionFrameOwnershipText, "private void ApplyFrameOwnership(PreviewRuntimeD3DFrameOwnership frameOwnership)");
        AssertContains(previewRuntimeD3DProjectionFrameOwnershipText, "D3DLastSubmittedSourceSequenceNumber = frameOwnership.LastSubmittedSourceSequenceNumber;");
        AssertContains(previewRuntimeD3DProjectionFrameStatisticsText, "public long D3DFrameStatsPresentCount { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionFrameStatisticsText, "private void ApplyFrameStatistics(PreviewRuntimeD3DFrameStatistics frameStatistics)");
        AssertContains(previewRuntimeD3DProjectionFrameStatisticsText, "D3DFrameStatsPresentCount = frameStatistics.PresentCount;");
        AssertContains(previewRuntimeD3DProjectionFrameLatencyWaitText, "public bool D3DFrameLatencyWaitEnabled { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionFrameLatencyWaitText, "private void ApplyFrameLatencyWait(PreviewRuntimeD3DFrameLatencyWait frameLatencyWait)");
        AssertContains(previewRuntimeD3DProjectionFrameLatencyWaitText, "D3DFrameLatencyWaitEnabled = frameLatencyWait.Enabled;");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "internal sealed partial class PreviewRuntimeD3DProjection");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "public static PreviewRuntimeD3DProjection Build(PreviewRuntimeSnapshotInput input)");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var frameCounters = PreviewRuntimeD3DFrameCounterPolicy.Evaluate(input);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var d3d = input.D3DRenderer;");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var rendererState = PreviewRuntimeD3DRendererStatePolicy.Evaluate(d3d, input.IsPreviewing);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var displayCadence = PreviewRuntimeD3DDisplayCadencePolicy.Evaluate(d3d, input.PreviewMinPresentationIntervalMs);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var renderCpuTiming = PreviewRuntimeD3DRenderCpuTimingPolicy.Evaluate(d3d);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var pipelineLatency = PreviewRuntimeD3DPipelineLatencyPolicy.Evaluate(d3d);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var frameOwnership = PreviewRuntimeD3DFrameOwnershipPolicy.Evaluate(d3d);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var frameStatistics = PreviewRuntimeD3DFrameStatisticsPolicy.Evaluate(d3d);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var frameLatencyWait = PreviewRuntimeD3DFrameLatencyWaitPolicy.Evaluate(d3d);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var projection = new PreviewRuntimeD3DProjection();");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyFrameCounters(frameCounters);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyRendererState(rendererState);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyDisplayCadence(displayCadence);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyRenderCpuTiming(renderCpuTiming);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyPipelineLatency(pipelineLatency);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyFrameLatencyWait(frameLatencyWait);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyFrameStatistics(frameStatistics);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyFrameOwnership(frameOwnership);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "return projection;");

        AssertContains(previewRuntimeD3DFrameCounterPolicyText, "internal static class PreviewRuntimeD3DFrameCounterPolicy");
        AssertContains(previewRuntimeD3DFrameCounterPolicyText, "public static PreviewRuntimeD3DFrameCounters Evaluate(PreviewRuntimeSnapshotInput input)");
        AssertContains(previewRuntimeD3DFrameCounterPolicyText, "FramesArrived: gpuActive ? d3dFramesSubmitted : input.FramesArrived,");
        AssertContains(previewRuntimeD3DRendererStatePolicyText, "internal static class PreviewRuntimeD3DRendererStatePolicy");
        AssertContains(previewRuntimeD3DRendererStatePolicyText, "public static PreviewRuntimeD3DRendererState Evaluate(D3D11PreviewRenderer? d3d, bool isPreviewing)");
        AssertContains(previewRuntimeD3DRendererStatePolicyText, "RendererMode: d3d?.RendererMode ?? (isPreviewing ? \"CpuSoftwareBitmap\" : \"None\"),");
        AssertContains(previewRuntimeD3DRendererStatePolicyText, "RecentSlowFrames: d3d?.GetRecentSlowFrameDiagnostics() ?? Array.Empty<PreviewSlowFrameDiagnostic>(),");
        AssertContains(previewRuntimeD3DDisplayCadencePolicyText, "internal static class PreviewRuntimeD3DDisplayCadencePolicy");
        AssertContains(previewRuntimeD3DDisplayCadencePolicyText, "public static PreviewRuntimeD3DDisplayCadence Evaluate(");
        AssertContains(previewRuntimeD3DDisplayCadencePolicyText, "RecentIntervalsMs: displayCadence?.RecentIntervalsMs ?? Array.Empty<double>(),");
        AssertContains(previewRuntimeD3DRenderCpuTimingPolicyText, "internal static class PreviewRuntimeD3DRenderCpuTimingPolicy");
        AssertContains(previewRuntimeD3DRenderCpuTimingPolicyText, "public static PreviewRuntimeD3DRenderCpuTiming Evaluate(D3D11PreviewRenderer? d3d)");
        AssertContains(previewRuntimeD3DRenderCpuTimingPolicyText, "SampleCount: renderCpuTiming?.TotalFrame.SampleCount ?? 0,");
        AssertContains(previewRuntimeD3DPipelineLatencyPolicyText, "internal static class PreviewRuntimeD3DPipelineLatencyPolicy");
        AssertContains(previewRuntimeD3DPipelineLatencyPolicyText, "public static PreviewRuntimeD3DPipelineLatency Evaluate(D3D11PreviewRenderer? d3d)");
        AssertContains(previewRuntimeD3DPipelineLatencyPolicyText, "EstimatedPipelineLatencyMs: pipelineLatency?.AverageMs ?? 0);");
        AssertContains(previewRuntimeD3DFrameStatisticsPolicyText, "internal static class PreviewRuntimeD3DFrameStatisticsPolicy");
        AssertContains(previewRuntimeD3DFrameStatisticsPolicyText, "public static PreviewRuntimeD3DFrameStatistics Evaluate(D3D11PreviewRenderer? d3d)");
        AssertContains(previewRuntimeD3DFrameStatisticsPolicyText, "PresentCount: frameStats?.PresentCount ?? -1,");
        AssertContains(previewRuntimeD3DFrameLatencyWaitPolicyText, "internal static class PreviewRuntimeD3DFrameLatencyWaitPolicy");
        AssertContains(previewRuntimeD3DFrameLatencyWaitPolicyText, "public static PreviewRuntimeD3DFrameLatencyWait Evaluate(D3D11PreviewRenderer? d3d)");
        AssertContains(previewRuntimeD3DFrameLatencyWaitPolicyText, "SampleCount: frameLatencyWait?.Timing.SampleCount ?? 0,");
        AssertContains(previewRuntimeD3DFrameOwnershipPolicyText, "internal static class PreviewRuntimeD3DFrameOwnershipPolicy");
        AssertContains(previewRuntimeD3DFrameOwnershipPolicyText, "public static PreviewRuntimeD3DFrameOwnership Evaluate(D3D11PreviewRenderer? d3d)");
        AssertContains(previewRuntimeD3DFrameOwnershipPolicyText, "LastSubmittedSourceSequenceNumber: frameOwnership?.LastSubmittedSourceSequenceNumber ?? -1,");
        AssertContains(previewRuntimeD3DFrameOwnershipPolicyText, "LastDroppedSourceSequenceNumber: frameOwnership?.LastDroppedSourceSequenceNumber ?? -1,");

        AssertContains(agentMapText, "PreviewRuntimeD3DFrameCounterPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DRendererStatePolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DDisplayCadencePolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DRenderCpuTimingPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DPipelineLatencyPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DFrameOwnershipPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DFrameStatisticsPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DFrameLatencyWaitPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.RendererState.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.DisplayCadence.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.RenderCpuTiming.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.PipelineLatency.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.FrameOwnership.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.FrameStatistics.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.FrameLatencyWait.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DFrameCounterPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DRendererStatePolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DDisplayCadencePolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DRenderCpuTimingPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DPipelineLatencyPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DFrameOwnershipPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DFrameStatisticsPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DFrameLatencyWaitPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.RendererState.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.DisplayCadence.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.RenderCpuTiming.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.PipelineLatency.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.FrameOwnership.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.FrameStatistics.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.FrameLatencyWait.cs");

        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "FramesArrived = frameCounters.FramesArrived,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DFramesSubmitted = frameCounters.D3DFramesSubmitted,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var framesArrived = gpuActive ? d3dFramesSubmitted : input.FramesArrived;");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "RendererMode = rendererState.RendererMode,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DRecentSlowFrames = rendererState.RecentSlowFrames,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "GpuPlaybackState = rendererState.GpuPlaybackState,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "RendererMode = d3d?.RendererMode ?? (input.IsPreviewing ? \"CpuSoftwareBitmap\" : \"None\"),");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "d3d?.GetRecentSlowFrameDiagnostics() ?? Array.Empty<PreviewSlowFrameDiagnostic>()");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "GpuPlaybackState = d3d == null ? \"None\" : (d3d.IsRendering ? \"Rendering\" : \"Idle\"),");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "DisplayCadenceObservedFps = displayCadence.ObservedFps,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "DisplayCadenceRecentIntervalsMs = displayCadence.RecentIntervalsMs,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var rendererCadence = d3d?.GetPresentCadenceMetrics(input.PreviewMinPresentationIntervalMs);");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "rendererCadence?.RecentIntervalsMs ?? Array.Empty<double>()");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DInputUploadCpuAvgMs = renderCpuTiming.InputUploadAverageMs,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var d3dRenderCpuTiming = d3d?.GetRenderCpuTimingMetrics();");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "d3dRenderCpuTiming?.TotalFrame.SampleCount ?? 0");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DPipelineLatencyAvgMs = pipelineLatency.AverageMs,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "EstimatedPipelineLatencyMs = pipelineLatency.EstimatedPipelineLatencyMs,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var d3dPipelineLatency = d3d?.GetPipelineLatencyMetrics();");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "d3dPipelineLatency?.AverageMs ?? 0");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DLastSubmittedSourceSequenceNumber = frameOwnership.LastSubmittedSourceSequenceNumber,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DFrameStatsPresentCount = frameStatistics.PresentCount,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DFrameLatencyWaitEnabled = frameLatencyWait.Enabled,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var d3dFrameOwnership = d3d?.GetFrameOwnershipMetrics();");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "d3dFrameOwnership?.LastSubmittedSourceSequenceNumber ?? -1");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var d3dFrameStats = d3d?.GetDxgiFrameStatisticsMetrics();");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "d3dFrameStats?.PresentCount ?? -1");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var d3dFrameLatencyWait = d3d?.GetFrameLatencyWaitMetrics();");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "d3dFrameLatencyWait?.Timing.SampleCount ?? 0");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DRecentSlowFrames = rendererState.RecentSlowFrames,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "EstimatedPipelineLatencyMs = pipelineLatency.EstimatedPipelineLatencyMs,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "GpuPlaybackState = rendererState.GpuPlaybackState,");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "public static PreviewRuntimeD3DProjection Build(PreviewRuntimeSnapshotInput input)");

        return Task.CompletedTask;
    }
}
