static partial class Program
{
    private static void AssertDiagnosticsRefreshSnapshotProjectionOwnership(AutomationDiagnosticsHubSourceFamily diagnostics)
    {
        AssertContains(diagnostics.SnapshotProjectionText, "var snapshotEvaluation = BuildSnapshotEvaluationProjection(performance, diagnostic, previewPacingClassification);");
        AssertContains(diagnostics.SnapshotProjectionSnapshotEvaluationText, "private SnapshotEvaluationProjection BuildSnapshotEvaluationProjection(");
        AssertContains(diagnostics.SnapshotProjectionSnapshotEvaluationText, "PerformanceScore = performance.Score,");
        AssertContains(diagnostics.SnapshotProjectionSnapshotEvaluationText, "DiagnosticHealthStatus = diagnostic.HealthStatus,");
        AssertContains(diagnostics.SnapshotProjectionSnapshotEvaluationText, "PreviewPacingLikelySlowStage = previewPacingClassification.LikelySlowStage,");
        AssertContains(diagnostics.SnapshotProjectionSnapshotEvaluationText, "PerformanceThresholdCaptureDropPercent = _perfectionCaptureDropPercentThreshold,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "PerformanceScore = performance.Score,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "PreviewPacingLikelySlowStage = previewPacingClassification.LikelySlowStage");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "PerformanceThresholdCaptureDropPercent = _perfectionCaptureDropPercentThreshold,");
        AssertContains(diagnostics.SnapshotProjectionText, "var audioAndIngest = BuildAudioAndIngestProjection(viewModelSnapshot, captureRuntime, audioSignal);");
        AssertContains(diagnostics.SnapshotProjectionText, "var audioDrops = BuildAudioDropsProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionAudioDropsText, "private static AudioDropsProjection BuildAudioDropsProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionAudioDropsText, "QueueDropsRealtime = health.AudioDropsQueueSaturated + health.AudioDropsBacklogEviction,");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "AudioQueueDropsRealtime = audioDrops.QueueDropsRealtime,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "AudioDropsQueueSaturated = health.AudioDropsQueueSaturated,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "AudioQueueDropsRealtime = health.AudioDropsQueueSaturated + health.AudioDropsBacklogEviction,");
        AssertContains(diagnostics.SnapshotProjectionText, "var captureFormat = BuildCaptureFormatProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionText, "var sourceTelemetry = BuildSourceTelemetryProjection(viewModelSnapshot, captureRuntime);");
        AssertDiagnosticsPreviewRuntimeProjectionOwnership(diagnostics);
        AssertContains(diagnostics.SnapshotProjectionText, "var previewD3D = BuildPreviewD3DProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "private static PreviewD3DProjection BuildPreviewD3DProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "var cpuTiming = BuildPreviewD3DCpuTimingProjection(previewRuntime);");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "CpuTiming = cpuTiming,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DCpuTimingText, "private static PreviewD3DCpuTimingProjection BuildPreviewD3DCpuTimingProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DCpuTimingText, "InputUploadP99Ms = previewRuntime.D3DInputUploadCpuP99Ms,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DCpuTimingText, "PipelineLatencyMaxMs = previewRuntime.D3DPipelineLatencyMaxMs");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "var frameFlow = BuildPreviewD3DFrameFlowProjection(previewRuntime);");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "FrameFlow = frameFlow");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameFlowText, "private static PreviewD3DFrameFlowProjection BuildPreviewD3DFrameFlowProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameFlowText, "LastRenderedPipelineLatencyMs = previewRuntime.D3DLastRenderedPipelineLatencyMs,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameFlowText, "RecentSlowFrames = previewRuntime.D3DRecentSlowFrames");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "var frameLatencyWait = BuildPreviewD3DFrameLatencyWaitProjection(previewRuntime);");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "var frameStats = BuildPreviewD3DFrameStatsProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "FrameLatencyWait = frameLatencyWait,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameLatencyWaitText, "private static PreviewD3DFrameLatencyWaitProjection BuildPreviewD3DFrameLatencyWaitProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameLatencyWaitText, "TimeoutCount = previewRuntime.D3DFrameLatencyWaitTimeoutCount,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DText, "FrameStats = frameStats,");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameStatsText, "private static PreviewD3DFrameStatsProjection BuildPreviewD3DFrameStatsProjection(");
        AssertContains(diagnostics.SnapshotProjectionPreviewD3DFrameStatsText, "RecentMissedRefreshCount = recentD3DMissedRefreshes,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "PreviewD3DFrameStatsRecentMissedRefreshCount = recentD3DMissedRefreshes,");
        AssertContains(diagnostics.SnapshotProjectionText, "var flashbackExport = BuildFlashbackExportProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackExportText, "private static FlashbackExportProjection BuildFlashbackExportProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionFlashbackExportText, "Active = health.FlashbackExportActive,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "FlashbackExportActive = health.FlashbackExportActive,");
        AssertContains(diagnostics.SnapshotProjectionText, "var flashbackRecording = BuildFlashbackRecordingProjection(captureRuntime, health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "private static FlashbackRecordingProjection BuildFlashbackRecordingProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "var startupCache = BuildFlashbackRecordingStartupCacheProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "StartupCache = startupCache,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingStartupCacheText, "private static FlashbackRecordingStartupCacheProjection BuildFlashbackRecordingStartupCacheProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingStartupCacheText, "OverBudget = health.FlashbackStartupCacheOverBudget");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "var queues = BuildFlashbackRecordingQueuesProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "Queues = queues,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingQueuesText, "private static FlashbackRecordingQueuesProjection BuildFlashbackRecordingQueuesProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingQueuesText, "GpuQueueLastRejectReason = health.FlashbackGpuQueueLastRejectReason,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingQueuesText, "AudioQueueCapacity = health.FlashbackAudioQueueCapacity");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "FlashbackEncodingFailed = flashbackRecording.EncodingFailed,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "EncodingFailed = health.FlashbackEncodingFailed,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackRecordingText, "ExportVerificationFormat = captureRuntime.FlashbackExportVerificationFormat ?? health.FlashbackExportVerificationFormat,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "FlashbackEncodingFailed = health.FlashbackEncodingFailed,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "FlashbackExportVerificationFormat = captureRuntime.FlashbackExportVerificationFormat ?? health.FlashbackExportVerificationFormat,");
        AssertContains(diagnostics.SnapshotProjectionText, "var flashbackPlayback = BuildFlashbackPlaybackProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "private static FlashbackPlaybackProjection BuildFlashbackPlaybackProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "var audioMaster = BuildFlashbackPlaybackAudioMasterProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "var decode = BuildFlashbackPlaybackDecodeProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "var commands = BuildFlashbackPlaybackCommandProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "AudioMaster = audioMaster,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "Commands = commands");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackText, "TargetFps = health.FlashbackPlaybackTargetFps,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackAudioMasterText, "private static FlashbackPlaybackAudioMasterProjection BuildFlashbackPlaybackAudioMasterProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackAudioMasterText, "LastFallbackReason = health.FlashbackPlaybackAudioMasterLastFallbackReason,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackDecodeText, "private static FlashbackPlaybackDecodeProjection BuildFlashbackPlaybackDecodeProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackDecodeText, "MaxPhase = health.FlashbackPlaybackMaxDecodePhase,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackDecodeText, "SeekForwardDecodeCapHits = health.FlashbackPlaybackSeekForwardDecodeCapHits,");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackCommandsText, "private static FlashbackPlaybackCommandProjection BuildFlashbackPlaybackCommandProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionFlashbackPlaybackCommandsText, "LastFailure = health.FlashbackPlaybackLastCommandFailure");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "FlashbackPlaybackTargetFps = health.FlashbackPlaybackTargetFps,");
        AssertContains(diagnostics.SnapshotProjectionAudioText, "private static AudioAndIngestProjection BuildAudioAndIngestProjection(");
        AssertContains(diagnostics.SnapshotProjectionAudioText, "var audioSignalProjection = BuildAudioSignalProjection(viewModelSnapshot, audioSignal);");
        AssertContains(diagnostics.SnapshotProjectionAudioText, "var captureIngest = BuildCaptureIngestProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionAudioText, "var wasapiAudio = BuildWasapiAudioProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionAudioSignalText, "private static AudioSignalProjection BuildAudioSignalProjection(");
        AssertContains(diagnostics.SnapshotProjectionAudioSignalText, "Peak = viewModelSnapshot.AudioPeak,");
        AssertContains(diagnostics.SnapshotProjectionCaptureIngestText, "private static CaptureIngestProjection BuildCaptureIngestProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionCaptureIngestText, "SourceReaderReadOutstanding = captureRuntime.SourceReaderReadOutstanding,");
        AssertContains(diagnostics.SnapshotProjectionWasapiAudioText, "private static WasapiAudioProjection BuildWasapiAudioProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionWasapiAudioText, "CaptureAudioLevelEventsFired = captureRuntime.WasapiCaptureAudioLevelEventsFired,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "AudioPeak = viewModelSnapshot.AudioPeak,");
        AssertContains(diagnostics.SnapshotProjectionText, "var captureCommands = BuildCaptureCommandProjection(viewModelSnapshot);");
        AssertContains(diagnostics.SnapshotProjectionCaptureCommandsText, "private static CaptureCommandProjection BuildCaptureCommandProjection(ViewModelRuntimeSnapshot viewModelSnapshot)");
        AssertContains(diagnostics.SnapshotProjectionCaptureCommandsText, "CommandsEnqueued = viewModelSnapshot.CaptureCommandCommandsEnqueued,");
        AssertContains(diagnostics.SnapshotProjectionCaptureCommandsText, "LastError = viewModelSnapshot.CaptureCommandLastError");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "CaptureCommandCommandsEnqueued = viewModelSnapshot.CaptureCommandCommandsEnqueued,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "CaptureCommandLastError = viewModelSnapshot.CaptureCommandLastError,");
        AssertContains(diagnostics.SnapshotProjectionText, "var userSettings = BuildUserSettingsProjection(viewModelSnapshot);");
        AssertContains(diagnostics.SnapshotProjectionUserSettingsText, "private static UserSettingsProjection BuildUserSettingsProjection(ViewModelRuntimeSnapshot viewModelSnapshot)");
        AssertContains(diagnostics.SnapshotProjectionUserSettingsText, "SelectedFriendlyFrameRate = viewModelSnapshot.SelectedFriendlyFrameRate ?? Math.Round(viewModelSnapshot.SelectedFrameRate),");
        AssertContains(diagnostics.SnapshotProjectionUserSettingsText, "IsStatsVisible = viewModelSnapshot.IsStatsVisible");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "SelectedDeviceId = viewModelSnapshot.SelectedDeviceId,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "SelectedFriendlyFrameRate = viewModelSnapshot.SelectedFriendlyFrameRate ?? Math.Round(viewModelSnapshot.SelectedFrameRate),");
        AssertContains(diagnostics.SnapshotProjectionText, "var recordingSettings = BuildRecordingSettingsProjection(userSettings);");
        AssertContains(diagnostics.SnapshotProjectionRecordingSettingsText, "private static RecordingSettingsProjection BuildRecordingSettingsProjection(UserSettingsProjection userSettings)");
        AssertContains(diagnostics.SnapshotProjectionRecordingSettingsText, "SelectedRecordingFormat = userSettings.SelectedRecordingFormat,");
        AssertContains(diagnostics.SnapshotProjectionRecordingSettingsText, "CustomBitrateMbps = userSettings.CustomBitrateMbps");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "SelectedRecordingFormat = userSettings.SelectedRecordingFormat,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "CustomBitrateMbps = userSettings.CustomBitrateMbps,");
        AssertContains(diagnostics.SnapshotProjectionText, "var hdrPipeline = BuildHdrPipelineProjection(viewModelSnapshot, captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionHdrPipelineText, "private static HdrPipelineProjection BuildHdrPipelineProjection(");
        AssertContains(diagnostics.SnapshotProjectionHdrPipelineText, "HdrRuntimeState = PreferViewModelHdrText(viewModelSnapshot.HdrRuntimeState, captureRuntime.HdrRuntimeState),");
        AssertContains(diagnostics.SnapshotProjectionHdrPipelineText, "TelemetryAlignmentReason = captureRuntime.TelemetryAlignmentReason");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "HdrRuntimeState = !string.IsNullOrWhiteSpace(viewModelSnapshot.HdrRuntimeState)");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "TelemetryAlignmentReason = captureRuntime.TelemetryAlignmentReason,");
        AssertContains(diagnostics.SnapshotProjectionText, "var hdrTruth = BuildHdrTruthProjection(hdrTruthVerdict);");
        AssertContains(diagnostics.SnapshotProjectionHdrTruthText, "private static HdrTruthProjection BuildHdrTruthProjection(HdrTruthVerdict verdict)");
        AssertContains(diagnostics.SnapshotProjectionHdrTruthText, "Verdict = verdict");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "HdrTruthVerdict = hdrTruth.Verdict,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "HdrTruthVerdict = hdrTruthVerdict,");
        AssertContains(diagnostics.SnapshotProjectionCaptureFormatText, "private static CaptureFormatProjection BuildCaptureFormatProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionCaptureFormatText, "NegotiatedWidth = captureRuntime.NegotiatedWidth ?? captureRuntime.ActualWidth,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "NegotiatedWidth = captureRuntime.NegotiatedWidth ?? captureRuntime.ActualWidth,");
        AssertContains(diagnostics.SnapshotProjectionText, "var captureTransport = BuildCaptureTransportProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionCaptureTransportText, "private static CaptureTransportProjection BuildCaptureTransportProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionCaptureTransportText, "FrameLedgerRecentEvents = captureRuntime.FrameLedgerRecentEvents");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "MemoryPreference = captureRuntime.MemoryPreference,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "FrameLedgerRecentEvents = captureRuntime.FrameLedgerRecentEvents,");
        AssertContains(diagnostics.SnapshotProjectionText, "var captureCadence = BuildCaptureCadenceProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionCaptureCadenceText, "private static CaptureCadenceProjection BuildCaptureCadenceProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionCaptureCadenceText, "EstimatedDroppedFrames = health.CaptureCadenceEstimatedDroppedFrames,");
        AssertContains(diagnostics.SnapshotProjectionCaptureCadenceText, "VisualCenterRecentChangeIntervalsMs = health.VisualCenterCadenceRecentChangeIntervalsMs");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "CaptureCadenceEstimatedDroppedFrames = health.CaptureCadenceEstimatedDroppedFrames,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "VisualCenterCadenceRecentChangeIntervalsMs = health.VisualCenterCadenceRecentChangeIntervalsMs,");
        AssertContains(diagnostics.SnapshotProjectionText, "var mjpeg = BuildMjpegProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "private static MjpegProjection BuildMjpegProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "var timing = BuildMjpegTimingProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "Timing = timing,");
        AssertContains(diagnostics.SnapshotProjectionMjpegTimingText, "private static MjpegTimingProjection BuildMjpegTimingProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionMjpegTimingText, "DecodeSampleCount = health.MjpegDecodeSampleCount,");
        AssertContains(diagnostics.SnapshotProjectionMjpegTimingText, "PerDecoder = health.MjpegPerDecoder is { Length: > 0 } perDecoder");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "var previewJitter = BuildMjpegPreviewJitterProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "var packetHash = BuildMjpegPacketHashProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "PreviewJitter = previewJitter,");
        AssertContains(diagnostics.SnapshotProjectionMjpegPreviewJitterText, "private static MjpegPreviewJitterProjection BuildMjpegPreviewJitterProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionMjpegPreviewJitterText, "LastDropReason = health.MjpegPreviewJitterLastDropReason,");
        AssertContains(diagnostics.SnapshotProjectionMjpegText, "PacketHash = packetHash,");
        AssertContains(diagnostics.SnapshotProjectionMjpegPacketHashText, "private static MjpegPacketHashProjection BuildMjpegPacketHashProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionMjpegPacketHashText, "Pattern = health.MjpegPacketHashPattern,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "MjpegPacketHashPattern = health.MjpegPacketHashPattern,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "MjpegPerDecoder = health.MjpegPerDecoder is { Length: > 0 } perDecoder");
        AssertContains(diagnostics.SnapshotProjectionText, "var recordingIntegrity = BuildRecordingIntegrityProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionRecordingIntegrityText, "private static RecordingIntegrityProjection BuildRecordingIntegrityProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionRecordingIntegrityText, "Status = captureRuntime.RecordingIntegrityStatus,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "RecordingIntegrityStatus = captureRuntime.RecordingIntegrityStatus,");
        AssertContains(diagnostics.SnapshotProjectionText, "var recordingBackend = BuildRecordingBackendProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionRecordingBackendText, "private static RecordingBackendProjection BuildRecordingBackendProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionRecordingBackendText, "MuxResult = ResolveMuxResult(captureRuntime.MuxSucceeded)");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "RecordingBackend = captureRuntime.RecordingBackend,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "MuxResult = captureRuntime.MuxSucceeded.HasValue");
        AssertContains(diagnostics.SnapshotProjectionText, "var recordingPipeline = BuildRecordingPipelineProjection(health);");
        AssertContains(diagnostics.SnapshotProjectionRecordingPipelineText, "private static RecordingPipelineProjection BuildRecordingPipelineProjection(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SnapshotProjectionRecordingPipelineText, "RecordingVideoQueueCapacity = health.RecordingVideoQueueCapacity,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "RecordingVideoQueueCapacity = health.RecordingVideoQueueCapacity,");
        AssertContains(diagnostics.SnapshotProjectionText, "var recordingOutput = BuildRecordingOutputProjection(");
        AssertContains(diagnostics.SnapshotProjectionRecordingOutputText, "private static RecordingOutputProjection BuildRecordingOutputProjection(");
        AssertContains(diagnostics.SnapshotProjectionRecordingOutputText, "RecordingVideoBytes = recordingStats.VideoBytes,");
        AssertContains(diagnostics.SnapshotProjectionRecordingOutputText, "LastOutputExists = lastOutput.Exists,");
        AssertContains(diagnostics.SnapshotProjectionRecordingOutputText, "LastVerification = lastVerification");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "RecordingVideoBytes = recordingStats.VideoBytes,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "LastOutputExists = lastOutput.Exists,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "LastVerification = lastVerification,");
        AssertContains(diagnostics.SnapshotProjectionText, "var sourceSignal = BuildSourceSignalProjection(viewModelSnapshot, captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionSourceSignalText, "private static SourceSignalProjection BuildSourceSignalProjection(");
        AssertContains(diagnostics.SnapshotProjectionSourceSignalText, "FrameRateOrigin = ResolveSourceFrameRateOrigin(viewModelSnapshot.SourceFrameRateOrigin, captureRuntime.SourceFrameRateOrigin),");
        AssertContains(diagnostics.SnapshotProjectionSourceSignalText, "RawTimingHex = captureRuntime.SourceRawTimingHex");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "DetectedSourceFrameRate = viewModelSnapshot.DetectedSourceFrameRate ?? captureRuntime.DetectedSourceFrameRate,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "SourceRawTimingHex = captureRuntime.SourceRawTimingHex,");
        AssertContains(diagnostics.SnapshotProjectionSourceTelemetryText, "private static SourceTelemetryProjection BuildSourceTelemetryProjection(");
        AssertContains(diagnostics.SnapshotProjectionSourceTelemetryText, "PreferKnownTelemetryValue(");
        AssertContains(diagnostics.SnapshotProjectionSourceTelemetryText, "SourceTelemetryAgeSeconds = TelemetryAgeHelper.ComputeAgeSeconds(");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "SourceTelemetryAvailability = !string.IsNullOrWhiteSpace(viewModelSnapshot.SourceTelemetryAvailability)");
        AssertContains(diagnostics.SnapshotProjectionText, "var processResourceProjection = BuildProcessResourceProjection(processResources);");
        AssertContains(diagnostics.SnapshotProjectionProcessResourcesText, "private static ProcessResourceProjection BuildProcessResourceProjection(ProcessResourceSnapshot processResources)");
        AssertContains(diagnostics.SnapshotProjectionProcessResourcesText, "MemoryWorkingSetMb = processResources.MemoryWorkingSetMb,");
        AssertContains(diagnostics.SnapshotProjectionProcessResourcesText, "ThreadPoolIoMax = processResources.ThreadPoolIoMax");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "MemoryWorkingSetMb = processResources.MemoryWorkingSetMb,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "ThreadPoolIoMax = processResources.ThreadPoolIoMax,");
        AssertContains(diagnostics.SnapshotProjectionText, "var avSync = BuildAvSyncProjection(captureRuntime);");
        AssertContains(diagnostics.SnapshotProjectionAvSyncText, "private static AvSyncProjection BuildAvSyncProjection(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.SnapshotProjectionAvSyncText, "CaptureDriftMs = captureRuntime.AvSyncCaptureDriftMs,");
        AssertContains(diagnostics.SnapshotProjectionAvSyncText, "EncoderCorrectionSamples = captureRuntime.AvSyncEncoderCorrectionSamples");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "AvSyncCaptureDriftMs = captureRuntime.AvSyncCaptureDriftMs,");
        AssertDoesNotContain(diagnostics.SnapshotProjectionText, "AvSyncEncoderCorrectionSamples = captureRuntime.AvSyncEncoderCorrectionSamples,");
    }
}
