static partial class Program
{
    private static void AssertDiagnosticsAlertEventOwnership(AutomationDiagnosticsHubSourceFamily diagnostics)
    {
        AssertContains(diagnostics.AlertsText, "private void UpdateAlerts(AutomationSnapshot snapshot, FlashbackRecordingRecentCounters flashbackRecordingRecent)");
        AssertDoesNotContain(diagnostics.AlertsText, "private void AddEventThrottled(");
        AssertDoesNotContain(diagnostics.AlertsText, "public IReadOnlyList<DiagnosticsEvent> GetRecentEvents");
        AssertContains(diagnostics.EventsText, "private void ObserveFlashbackExportCompletion(AutomationSnapshot snapshot)");
        AssertContains(diagnostics.EventsText, "private void AddEventThrottled(");
        AssertContains(diagnostics.EventsText, "private void SetAlertState(");
        AssertContains(diagnostics.EventsText, "public IReadOnlyList<DiagnosticsEvent> GetRecentEvents");
        AssertContains(diagnostics.AlertsText, "UpdateSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsText, "private void UpdateSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsText, "UpdatePreviewSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsText, "UpdateAudioSignalAlerts(snapshot);");
        AssertContains(diagnostics.SignalAlertsText, "UpdateRecordingGrowthAlerts(snapshot);");
        AssertContains(diagnostics.SignalAlertsText, "UpdateCaptureSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsPreviewText, "private void UpdatePreviewSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-blank\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-stall\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-startup-timeout\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-startup-failed\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-cadence-slow\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-display-low-1pct\"");
        AssertContains(diagnostics.SignalAlertsAudioText, "private void UpdateAudioSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsAudioText, "\"audio-muted-suspect\"");
        AssertContains(diagnostics.SignalAlertsRecordingText, "private void UpdateRecordingGrowthAlerts(");
        AssertContains(diagnostics.SignalAlertsRecordingText, "\"recording-not-growing\"");
        AssertContains(diagnostics.SignalAlertsCaptureText, "private void UpdateCaptureSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsCaptureText, "\"capture-cadence-drop\"");
        AssertContains(diagnostics.SignalAlertsCaptureText, "\"capture-cadence-low-1pct\"");
        AssertDoesNotContain(diagnostics.SignalAlertsText, "\"preview-blank\"");
        AssertDoesNotContain(diagnostics.SignalAlertsText, "\"audio-muted-suspect\"");
        AssertDoesNotContain(diagnostics.SignalAlertsText, "\"recording-not-growing\"");
        AssertDoesNotContain(diagnostics.SignalAlertsText, "\"capture-cadence-drop\"");
        AssertDoesNotContain(diagnostics.AlertsText, "\"preview-blank\"");
        AssertContains(diagnostics.AlertsText, "UpdateFlashbackAlerts(snapshot, flashbackRecordingRecent);");
        AssertContains(diagnostics.FlashbackAlertsText, "private void UpdateFlashbackAlerts(");
        AssertContains(diagnostics.FlashbackAlertsText, "UpdateFlashbackRecordingAlerts(snapshot, flashbackRecordingRecent);");
        AssertContains(diagnostics.FlashbackAlertsText, "UpdateFlashbackPlaybackAlerts(snapshot, nowUnixMs);");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "private void UpdateFlashbackRecordingAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "UpdateFlashbackExportAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "UpdateFlashbackStorageAlerts(snapshot);");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "UpdateFlashbackEncoderAlerts(snapshot);");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "UpdateFlashbackRecordingDegradationAlert(");
        AssertContains(diagnostics.FlashbackRecordingAlertsExportText, "private void UpdateFlashbackExportAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsExportText, "\"flashback-export-stalled\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsExportText, "\"flashback-export-rotation-gap\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsStorageText, "private void UpdateFlashbackStorageAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsStorageText, "\"flashback-temp-cache-pressure\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsEncoderText, "private void UpdateFlashbackEncoderAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsEncoderText, "\"flashback-encoding-failed\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsDegradationText, "private void UpdateFlashbackRecordingDegradationAlert(");
        AssertContains(diagnostics.FlashbackRecordingAlertsDegradationText, "\"flashback-recording-degraded\"");
        AssertDoesNotContain(diagnostics.FlashbackRecordingAlertsText, "\"flashback-export-stalled\"");
        AssertDoesNotContain(diagnostics.FlashbackRecordingAlertsText, "\"flashback-temp-cache-pressure\"");
        AssertDoesNotContain(diagnostics.FlashbackRecordingAlertsText, "\"flashback-encoding-failed\"");
        AssertDoesNotContain(diagnostics.FlashbackRecordingAlertsText, "\"flashback-recording-degraded\"");
        AssertDoesNotContain(diagnostics.FlashbackRecordingAlertsText, "\"flashback-export-rotation-gap\"");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "private void UpdateFlashbackPlaybackAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "UpdateFlashbackPlaybackCommandAlerts(snapshot, nowUnixMs);");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "UpdateFlashbackPlaybackPerformanceAlerts(snapshot);");
        AssertContains(diagnostics.FlashbackPlaybackCommandAlertsText, "private void UpdateFlashbackPlaybackCommandAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackCommandAlertsText, "\"flashback-playback-command-stalled\"");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsText, "private void UpdateFlashbackPlaybackPerformanceAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsText, "UpdateFlashbackPlaybackCadenceAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsText, "UpdateFlashbackPlaybackAudioAlerts(snapshot, playbackActive);");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsText, "UpdateFlashbackPlaybackSubmitFailureAlert(snapshot);");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsCadenceText, "private void UpdateFlashbackPlaybackCadenceAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsCadenceText, "\"flashback-playback-slow\"");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsAudioText, "private void UpdateFlashbackPlaybackAudioAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsAudioText, "\"flashback-playback-audio-master-fallback\"");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsSubmissionText, "private void UpdateFlashbackPlaybackSubmitFailureAlert(");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsSubmissionText, "\"flashback-playback-submit-failures\"");
        AssertDoesNotContain(diagnostics.FlashbackPlaybackPerformanceAlertsText, "\"flashback-playback-slow\"");
        AssertDoesNotContain(diagnostics.FlashbackPlaybackPerformanceAlertsText, "\"flashback-playback-audio-master-fallback\"");
        AssertDoesNotContain(diagnostics.FlashbackPlaybackPerformanceAlertsText, "\"flashback-playback-submit-failures\"");
        AssertDoesNotContain(diagnostics.FlashbackAlertsText, "\"flashback-export-stalled\"");
        AssertDoesNotContain(diagnostics.FlashbackAlertsText, "\"flashback-playback-slow\"");
        AssertDoesNotContain(diagnostics.FlashbackPlaybackAlertsText, "\"flashback-playback-command-stalled\"");
        AssertDoesNotContain(diagnostics.FlashbackPlaybackAlertsText, "\"flashback-playback-slow\"");
        AssertDoesNotContain(diagnostics.AlertsText, "\"flashback-export-stalled\"");
        AssertDoesNotContain(diagnostics.HubText, "private void UpdateAlerts(AutomationSnapshot snapshot, FlashbackRecordingRecentCounters flashbackRecordingRecent)");
    }
}
