static partial class Program
{
    private static void AssertDiagnosticsRefreshCoreOwnership(AutomationDiagnosticsHubSourceFamily diagnostics)
    {
        AssertContains(diagnostics.EvaluationPolicyText, "private static string FormatPreviewSlowFrameAlertDetail");
        AssertDoesNotContain(diagnostics.EvaluationText, "private static string FormatPreviewSlowFrameAlertDetail");
        AssertContains(diagnostics.EvaluationText, "private PerformanceEvaluation EvaluatePerformance(");
        AssertContains(diagnostics.DiagnosticEvaluationText, "private static DiagnosticEvaluation BuildDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationText, "var lanes = BuildDiagnosticEvaluationLanes(");
        AssertContains(diagnostics.DiagnosticEvaluationText, "var flashbackDiagnostic = TryBuildFlashbackDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationText, "var realtimeDiagnostic = TryBuildRealtimeDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackText, "private static DiagnosticEvaluation? TryBuildFlashbackDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackText, "TryBuildFlashbackStorageDiagnosticEvaluation(health, lanes)");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackText, "TryBuildFlashbackRecordingDiagnosticEvaluation(health, isRecording, recentFlashbackRecording, lanes)");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackText, "TryBuildFlashbackExportDiagnosticEvaluation(health, lanes)");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackText, "TryBuildFlashbackPlaybackDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackStorageText, "private static DiagnosticEvaluation? TryBuildFlashbackStorageDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackStorageText, "\"flashback_storage\"");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "private static DiagnosticEvaluation? TryBuildFlashbackRecordingDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "BuildFlashbackRecordingDiagnosticConditions(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "TryBuildFlashbackEncoderFailureDiagnosticEvaluation(health, lanes)");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "TryBuildFlashbackExportRotationDiagnosticEvaluation(conditions, lanes)");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "TryBuildFlashbackBackendSettingsDiagnosticEvaluation(conditions, lanes)");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "TryBuildFlashbackRecordingDegradationDiagnosticEvaluation(conditions, lanes)");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingConditionsText, "private static FlashbackRecordingDiagnosticConditions BuildFlashbackRecordingDiagnosticConditions(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "private static DiagnosticEvaluation? TryBuildFlashbackEncoderFailureDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "\"Flashback encoder has failed.\"");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "private static DiagnosticEvaluation? TryBuildFlashbackExportRotationDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "\"flashback_export\"");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "private static DiagnosticEvaluation? TryBuildFlashbackBackendSettingsDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "\"Flashback backend settings differ from requested settings.\"");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "private static DiagnosticEvaluation? TryBuildFlashbackRecordingDegradationDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackRecordingText, "\"Flashback recording path is dropping or backing up.\"");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackExportText, "private static DiagnosticEvaluation? TryBuildFlashbackExportDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackExportText, "\"Flashback export progress is stalled.\"");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackExportText, "\"Flashback export is running.\"");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackPlaybackText, "private static DiagnosticEvaluation? TryBuildFlashbackPlaybackDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationFlashbackPlaybackText, "\"flashback_playback\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationFlashbackText, "\"flashback_storage\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationFlashbackText, "\"flashback_recording\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationFlashbackText, "\"flashback_playback\"");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeText, "private static DiagnosticEvaluation? TryBuildRealtimeDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeText, "TryBuildRealtimeStateDiagnosticEvaluation(health, isPreviewing, isRecording, lanes)");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeText, "TryBuildRealtimeRecordingDiagnosticEvaluation(captureRuntime, health, isRecording, lanes)");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeText, "TryBuildRealtimeSourceDiagnosticEvaluation(health, isPreviewing, visualCadenceHealthy, lanes)");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeText, "TryBuildRealtimeMjpegDiagnosticEvaluation(health, recentMjpeg, lanes)");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeText, "TryBuildRealtimePreviewDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeStateText, "private static DiagnosticEvaluation? TryBuildRealtimeStateDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeStateText, "\"diagnostic_unavailable\"");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeRecordingText, "private static DiagnosticEvaluation? TryBuildRealtimeRecordingDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeRecordingText, "\"recording\"");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeRecordingText, "\"audio\"");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeSourceText, "private static DiagnosticEvaluation? TryBuildRealtimeSourceDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeSourceText, "\"source_capture\"");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeMjpegText, "private static DiagnosticEvaluation? TryBuildRealtimeMjpegDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeMjpegText, "\"source_signal\"");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimeMjpegText, "\"mjpeg_decode\"");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimePreviewText, "private static DiagnosticEvaluation? TryBuildRealtimePreviewDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimePreviewText, "TryBuildRealtimePreviewSchedulerDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimePreviewText, "TryBuildRealtimePreviewRendererDiagnosticEvaluation(lanes)");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimePreviewText, "TryBuildRealtimePreviewPresentDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimePreviewSchedulerText, "private static DiagnosticEvaluation? TryBuildRealtimePreviewSchedulerDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimePreviewSchedulerText, "\"preview_scheduler\"");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimePreviewText, "private static DiagnosticEvaluation? TryBuildRealtimePreviewRendererDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimePreviewText, "\"renderer\"");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimePreviewPresentText, "private static DiagnosticEvaluation? TryBuildRealtimePreviewPresentDiagnosticEvaluation(");
        AssertContains(diagnostics.DiagnosticEvaluationRealtimePreviewPresentText, "\"present_display\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimePreviewText, "\"preview_scheduler\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimePreviewText, "\"present_display\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimeText, "\"source_capture\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimeText, "\"source_signal\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimeText, "\"mjpeg_decode\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimeText, "Recording integrity is the likely failure point.");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimeText, "\"preview_scheduler\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimeText, "\"renderer\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimeText, "\"present_display\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimeText, "Preview scheduler failed to submit frames.");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimeText, "Renderer pacing is the likely preview bottleneck.");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimeText, "Present/display cadence is the likely preview bottleneck.");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationRealtimeText, "Present/display 1% low is below target.");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationText, "\"flashback_storage\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationText, "\"source_capture\"");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationText, "var sourceTarget =");
        AssertContains(diagnostics.DiagnosticEvaluationLanesText, "private static DiagnosticEvaluationLanes BuildDiagnosticEvaluationLanes(");
        AssertContains(diagnostics.DiagnosticEvaluationLanesText, "BuildSourceLane(health)");
        AssertContains(diagnostics.DiagnosticEvaluationLanesText, "BuildPreviewLane(");
        AssertContains(diagnostics.DiagnosticEvaluationLanesText, "BuildRenderLane(previewRuntime, recentRenderer)");
        AssertContains(diagnostics.DiagnosticEvaluationLanesText, "BuildRecordingLane(captureRuntime)");
        AssertContains(diagnostics.DiagnosticEvaluationLanesText, "BuildAudioLane(captureRuntime)");
        AssertContains(diagnostics.DiagnosticEvaluationLanesText, "BuildFlashbackRecordingLane(health)");
        AssertContains(diagnostics.DiagnosticEvaluationLanesRealtimeSourceText, "private static string BuildSourceLane(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.DiagnosticEvaluationLanesRealtimeSourceText, "private static string BuildSourceSignalLane(");
        AssertContains(diagnostics.DiagnosticEvaluationLanesRealtimeMjpegText, "private static string BuildDecodeLane(");
        AssertContains(diagnostics.DiagnosticEvaluationLanesRealtimePreviewText, "private static string BuildPreviewLane(");
        AssertContains(diagnostics.DiagnosticEvaluationLanesRealtimePreviewText, "private static DiagnosticEvaluationRenderLane BuildRenderLane(");
        AssertContains(diagnostics.DiagnosticEvaluationLanesRealtimePreviewText, "private static string BuildPresentLane(");
        AssertContains(diagnostics.DiagnosticEvaluationLanesRealtimePreviewText, "private static string BuildVisualLane(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.DiagnosticEvaluationLanesRealtimePreviewText, "private readonly record struct DiagnosticEvaluationRenderLane(");
        AssertContains(diagnostics.DiagnosticEvaluationLanesRealtimeRecordingText, "private static string BuildRecordingLane(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.DiagnosticEvaluationLanesRealtimeRecordingText, "private static string BuildAudioLane(CaptureRuntimeSnapshot captureRuntime)");
        AssertContains(diagnostics.DiagnosticEvaluationLanesFlashbackText, "private static string BuildFlashbackRecordingLane(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.DiagnosticEvaluationLanesFlashbackText, "private static string BuildFlashbackExportLane(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.DiagnosticEvaluationLanesFlashbackText, "private static string BuildFlashbackTempCacheLane(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.DiagnosticEvaluationLanesFlashbackText, "private static string BuildFlashbackPlaybackCommandLane(");
        AssertContains(diagnostics.DiagnosticEvaluationLanesFlashbackText, "private static string BuildFlashbackPlaybackPerformanceLane(");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesRealtimeSourceText, "private static string BuildDecodeLane(");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesRealtimeSourceText, "private static string BuildPreviewLane(");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesRealtimeMjpegText, "private static string BuildSourceLane(CaptureHealthSnapshot health)");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesRealtimePreviewText, "private static string BuildRecordingLane(CaptureRuntimeSnapshot captureRuntime)");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesRealtimeRecordingText, "private static string BuildPresentLane(");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesRealtimePreviewText, "private static string BuildFlashbackRecordingLane(CaptureHealthSnapshot health)");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesFlashbackText, "private static string BuildSourceLane(CaptureHealthSnapshot health)");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesText, "var sourceTarget =");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesText, "var previewLastDropReason =");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesText, "var dxgiStats =");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesText, "recording integrity={captureRuntime.RecordingIntegrityStatus}");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesText, "audio integrity={captureRuntime.RecordingIntegrityAudioStatus}");
        AssertDoesNotContain(diagnostics.DiagnosticEvaluationLanesText, "var exportFailureKind =");
        AssertContains(diagnostics.DiagnosticEvaluationLanesText, "private readonly record struct DiagnosticEvaluationLanes(");
        AssertDoesNotContain(diagnostics.EvaluationText, "private static DiagnosticEvaluation BuildDiagnosticEvaluation(");
        AssertDoesNotContain(diagnostics.HubText, "private PerformanceEvaluation EvaluatePerformance(");
        AssertDoesNotContain(diagnostics.HubText, "private static DiagnosticEvaluation BuildDiagnosticEvaluation(");
        AssertContains(diagnostics.VerificationText, "public async Task<RecordingVerificationResult> VerifyLastRecordingAsync");
        AssertContains(diagnostics.VerificationText, "private static CaptureRuntimeSnapshot ApplyVerificationProfile(");
        AssertContains(diagnostics.VerificationText, "private bool ShouldAutoVerifySnapshot(");
        AssertContains(diagnostics.VerificationText, "private RecordingVerificationResult? CaptureLastVerificationForSnapshot(");
        AssertContains(diagnostics.VerificationText, "private void ScheduleAutoVerificationIfNeeded(");
        AssertDoesNotContain(diagnostics.HubText, "public async Task<RecordingVerificationResult> VerifyLastRecordingAsync");
        AssertContains(diagnostics.HubText, "private readonly IAutomationSnapshotQueryPort _snapshotQueryPort;");
        AssertContains(diagnostics.HubText, "IAutomationSnapshotQueryPort snapshotQueryPort,");
        AssertContains(diagnostics.HubText, "_snapshotQueryPort = snapshotQueryPort ?? throw new ArgumentNullException(nameof(snapshotQueryPort));");
        AssertDoesNotContain(diagnostics.HubText, "IAutomationViewModel viewModel,");
        AssertDoesNotContain(diagnostics.HubText, "private readonly IAutomationViewModel _viewModel;");
        AssertContains(diagnostics.SnapshotsText, "await _snapshotQueryPort\n            .GetViewModelRuntimeSnapshotAsync(cancellationToken)");
        AssertContains(diagnostics.SnapshotsText, "await _snapshotQueryPort\n            .GetCaptureRuntimeSnapshotAsync(cancellationToken)");
        AssertContains(diagnostics.VerificationText, "await _snapshotQueryPort\n                .GetCaptureRuntimeSnapshotAsync(cancellationToken)");
        AssertContains(diagnostics.PreviewPacingText, "private static PreviewPacingClassification ClassifyPreviewPacing(");
        AssertContains(diagnostics.SnapshotsText, "ClassifyPreviewPacing(");
        AssertDoesNotContain(diagnostics.SnapshotsText, "new PreviewPacingClassificationInput");
        AssertContains(diagnostics.LifecycleText, "public void Start()");
        AssertContains(diagnostics.LifecycleText, "private async Task RunLoopAsync(CancellationToken cancellationToken)");
        AssertDoesNotContain(diagnostics.HubText, "public void Start()");
        AssertContains(diagnostics.HdrText, "private static HdrTruthVerdict BuildHdrTruthVerdict(");
        AssertContains(diagnostics.HdrText, "private static PreviewHdrState BuildPreviewHdrState(");
        AssertContains(diagnostics.HdrText, "private readonly record struct PreviewHdrState(");
        AssertContains(diagnostics.HdrText, "private static bool IsHdrSubtype(string? subtype)");
        AssertDoesNotContain(diagnostics.HubText, "private static HdrTruthVerdict BuildHdrTruthVerdict(");
        AssertContains(diagnostics.SnapshotsText, "var previewHdrState = BuildPreviewHdrState(captureRuntime, viewModelSnapshot, previewRuntime);");
        AssertDoesNotContain(diagnostics.SnapshotsText, "var previewHdrInputDetected =");
        AssertContains(diagnostics.SnapshotsText, "private async Task<AutomationSnapshot> RefreshSnapshotCoreAsync");
        AssertContains(diagnostics.SnapshotProjectionText, "private AutomationSnapshot BuildAutomationSnapshot(");
        AssertContains(diagnostics.SnapshotProjectionText, "var projections = BuildAutomationSnapshotProjectionSet(");
        AssertContains(diagnostics.SnapshotProjectionText, "return BuildAutomationSnapshotFromProjections(projections);");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "private AutomationSnapshotProjectionSet BuildAutomationSnapshotProjectionSet(");
        AssertContains(diagnostics.SnapshotProjectionCompositionText, "private readonly record struct AutomationSnapshotProjectionSet(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "private static AutomationSnapshot BuildAutomationSnapshotFromProjections(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "AutomationSnapshotProjectionSet projections");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildSnapshotStatusFlattenedProjection(snapshotStatus)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningSnapshotStatusText, "private static SnapshotStatusFlattenedProjection BuildSnapshotStatusFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildSnapshotEvaluationFlattenedProjection(snapshotEvaluation)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningSnapshotEvaluationText, "private static SnapshotEvaluationFlattenedProjection BuildSnapshotEvaluationFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildCaptureFormatFlattenedProjection(captureFormat)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningCaptureFormatText, "private static CaptureFormatFlattenedProjection BuildCaptureFormatFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildCaptureTransportFlattenedProjection(captureTransport)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningCaptureTransportText, "private static CaptureTransportFlattenedProjection BuildCaptureTransportFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildCaptureCadenceFlattenedProjection(captureCadence)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningCaptureCadenceText, "private static CaptureCadenceFlattenedProjection BuildCaptureCadenceFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildVisualCadenceFlattenedProjection(visualCadence)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningVisualCadenceText, "private static VisualCadenceFlattenedProjection BuildVisualCadenceFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildMjpegFlattenedProjection(mjpeg)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegText, "private static MjpegFlattenedProjection BuildMjpegFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildMjpegTimingFlattenedProjection(mjpeg.Timing)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegTimingText, "private static MjpegTimingFlattenedProjection BuildMjpegTimingFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildMjpegPreviewJitterFlattenedProjection(mjpeg.PreviewJitter)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegPreviewJitterText, "private static MjpegPreviewJitterFlattenedProjection BuildMjpegPreviewJitterFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildMjpegPacketHashFlattenedProjection(mjpeg.PacketHash)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningMjpegPacketHashText, "private static MjpegPacketHashFlattenedProjection BuildMjpegPacketHashFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildSourceFlattenedProjection(sourceSignal, sourceTelemetry)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningSourceText, "private static SourceFlattenedProjection BuildSourceFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildSettingsFlattenedProjection(userSettings, recordingSettings)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningSettingsText, "private static SettingsFlattenedProjection BuildSettingsFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildHdrPipelineFlattenedProjection(hdrPipeline)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningHdrPipelineText, "private static HdrPipelineFlattenedProjection BuildHdrPipelineFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildPreviewRuntimeFlattenedProjection(previewSummary)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningPreviewRuntimeText, "private static PreviewRuntimeFlattenedProjection BuildPreviewRuntimeFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildPreviewD3DFlattenedProjection(previewD3D)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningPreviewD3DText, "private static PreviewD3DFlattenedProjection BuildPreviewD3DFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildFlashbackExportFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningFlashbackExportText, "private static FlashbackExportFlattenedProjection BuildFlashbackExportFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildFlashbackRecordingFlattenedProjection(flashbackRecording)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningFlashbackRecordingText, "private static FlashbackRecordingFlattenedProjection BuildFlashbackRecordingFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildFlashbackPlaybackFlattenedProjection(flashbackPlayback)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningFlashbackPlaybackText, "private static FlashbackPlaybackFlattenedProjection BuildFlashbackPlaybackFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildRecordingIntegrityFlattenedProjection(recordingIntegrity)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningRecordingIntegrityText, "private static RecordingIntegrityFlattenedProjection BuildRecordingIntegrityFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildRecordingPipelineFlattenedProjection(recordingPipeline)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningRecordingPipelineText, "private static RecordingPipelineFlattenedProjection BuildRecordingPipelineFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildRecordingOutputFlattenedProjection(recordingBackend, recordingOutput)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningRecordingOutputText, "private static RecordingOutputFlattenedProjection BuildRecordingOutputFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildProcessResourceFlattenedProjection(processResourceProjection)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningProcessResourcesText, "private static ProcessResourceFlattenedProjection BuildProcessResourceFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildAvSyncFlattenedProjection(avSync)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningAvSyncText, "private static AvSyncFlattenedProjection BuildAvSyncFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildAudioAndIngestFlattenedProjection(audioAndIngest)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningAudioAndIngestText, "private static AudioAndIngestFlattenedProjection BuildAudioAndIngestFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildAudioDropsFlattenedProjection(audioDrops)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningAudioDropsText, "private static AudioDropsFlattenedProjection BuildAudioDropsFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "BuildCaptureCommandFlattenedProjection(captureCommands)");
        AssertContains(diagnostics.SnapshotProjectionFlatteningCaptureCommandsText, "private static CaptureCommandFlattenedProjection BuildCaptureCommandFlattenedProjection(");
        AssertContains(diagnostics.SnapshotProjectionFlatteningText, "new AutomationSnapshot");
    }
}
