static partial class Program
{
    private static void AssertDiagnosticsRefreshFlashbackPlaybackAndPreviewAlertCoverage(
        AutomationDiagnosticsHubSourceFamily diagnostics,
        string countersText)
    {
        AssertContains(diagnostics.SourceFamilyText, "\"flashback-playback-command-stalled\"");
        AssertContains(diagnostics.SourceFamilyText, "private const int FlashbackPlaybackCommandStallThresholdMs = 1000;");
        AssertContains(diagnostics.SourceFamilyText, "\"flashback-playback-command-failed\"");
        AssertContains(diagnostics.SourceFamilyText, "private const int FlashbackPlaybackCommandFailureRecentMs = 30000;");
        AssertContains(diagnostics.SourceFamilyText, "playbackCommandFailureAgeMs <= FlashbackPlaybackCommandFailureRecentMs");
        AssertContains(diagnostics.SourceFamilyText, "Flashback playback command failed recently:");
        AssertContains(diagnostics.SourceFamilyText, "\"Flashback playback command failed recently.\"");
        AssertContains(diagnostics.SourceFamilyText, "private const double FlashbackPlaybackSlowFpsRatio = 0.75;");
        AssertContains(diagnostics.SourceFamilyText, "private const double CaptureOnePercentLowWarningRatio = 0.98;");
        AssertContains(diagnostics.SourceFamilyText, "private const double PreviewOnePercentLowWarningRatio = 0.98;");
        AssertContains(diagnostics.SourceFamilyText, "private const double FlashbackPlaybackOnePercentLowWarningRatio = 0.98;");
        AssertContains(diagnostics.SourceFamilyText, "private const int FlashbackPlaybackOnePercentLowMinimumFrames = 1200;");
        AssertContains(diagnostics.SourceFamilyText, "\"flashback-playback-slow\"");
        AssertContains(diagnostics.SourceFamilyText, "\"flashback-playback-target-below-selection\"");
        AssertContains(diagnostics.SourceFamilyText, "\"flashback-playback-present-capped\"");
        AssertContains(diagnostics.SourceFamilyText, "\"flashback-playback-frametime-degraded\"");
        AssertContains(diagnostics.SourceFamilyText, "\"flashback-playback-audio-master-fallback\"");
        AssertContains(diagnostics.SourceFamilyText, "\"flashback-playback-audio-queue-backlog\"");
        AssertContains(diagnostics.SourceFamilyText, "\"flashback-playback-submit-failures\"");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.FlashbackPlaybackSubmitFailures > 0");
        AssertContains(diagnostics.SourceFamilyText, "Flashback playback frame submission failed");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.FlashbackPlaybackPendingCommands > 0");
        AssertContains(diagnostics.SourceFamilyText, "FlashbackPlaybackCommandQueueCapacity");
        AssertContains(diagnostics.SourceFamilyText, "FlashbackPlaybackTargetFps = flashbackPlayback.TargetFps");
        AssertContains(diagnostics.SourceFamilyText, "TargetFps = health.FlashbackPlaybackTargetFps");
        AssertContains(diagnostics.SourceFamilyText, "FlashbackPlaybackTargetFps = snapshot.FlashbackPlaybackTargetFps");
        AssertContains(diagnostics.SourceFamilyText, "FlashbackPlaybackPtsCadenceMismatchCount = flashbackPlayback.PtsCadenceMismatchCount");
        AssertContains(diagnostics.SourceFamilyText, "PtsCadenceMismatchCount = health.FlashbackPlaybackPtsCadenceMismatchCount");
        AssertContains(diagnostics.SourceFamilyText, "ptsMismatch={snapshot.FlashbackPlaybackPtsCadenceMismatchCount}");
        AssertContains(diagnostics.SourceFamilyText, "private static double ResolveFlashbackPlaybackTargetFps(double flashbackPlaybackTargetFps, double fallbackFrameRate)");
        AssertContains(diagnostics.SourceFamilyText, "var playbackTargetFps = ResolveFlashbackPlaybackTargetFps(\n            snapshot.FlashbackPlaybackTargetFps,\n            snapshot.SelectedExactFrameRate.GetValueOrDefault(snapshot.SelectedFrameRate));");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.FlashbackPlaybackObservedFps < playbackTargetFps * FlashbackPlaybackSlowFpsRatio");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.FlashbackPlaybackTargetFps <= selectedCaptureFps * FlashbackPlaybackSlowFpsRatio");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.PreviewCadenceObservedFps <= snapshot.FlashbackPlaybackTargetFps * FlashbackPlaybackSlowFpsRatio");
        AssertContains(diagnostics.SourceFamilyText, "IsFlashbackPlaybackFrametimeDegraded(\n                snapshot.FlashbackPlaybackState");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.FlashbackPlaybackState,\n                playbackTargetFps,\n                snapshot.FlashbackPlaybackFrameCount");
        AssertContains(diagnostics.SourceFamilyText, "IsCaptureOnePercentLowDegraded(\n                snapshot.ExpectedCaptureFrameRate");
        AssertContains(diagnostics.SourceFamilyText, "IsPreviewOnePercentLowDegraded(\n                snapshot.PreviewCadenceExpectedIntervalMs");
        AssertContains(diagnostics.SourceFamilyText, "\"Source/capture 1% low is below target, but sampled visual cadence confirms source-rate output.\"");
        AssertContains(diagnostics.SourceFamilyText, "$\"{lanes.Source} | {lanes.Visual}\"");
        AssertContains(diagnostics.SourceFamilyText, "captureCadenceExpectedFrameRate: health.ExpectedFrameRate");
        AssertContains(diagnostics.SourceFamilyText, "captureCadenceOnePercentLowFps: health.CaptureCadenceOnePercentLowFps");
        AssertContains(diagnostics.SourceFamilyText, "previewCadenceExpectedIntervalMs: previewRuntime.DisplayCadenceExpectedIntervalMs");
        AssertContains(diagnostics.SourceFamilyText, "previewCadenceOnePercentLowFps: previewRuntime.DisplayCadenceOnePercentLowFps");
        AssertContains(diagnostics.SourceFamilyText, "reasons.Add($\"capture 1% low {captureCadenceOnePercentLowFps:0.##}fps\")");
        AssertContains(diagnostics.SourceFamilyText, "reasons.Add($\"preview 1% low {previewCadenceOnePercentLowFps:0.##}fps\")");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.FlashbackPlaybackOnePercentLowFps");
        AssertContains(diagnostics.SourceFamilyText, "frameCount >= FlashbackPlaybackOnePercentLowMinimumFrames");
        AssertContains(diagnostics.SourceFamilyText, "cadenceSampleCount >= FlashbackPlaybackOnePercentLowMinimumFrames");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.FlashbackPlaybackAudioMasterFallbacks >= snapshot.FlashbackPlaybackFrameCount * FlashbackPlaybackAudioMasterFallbackWarningRatio");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.WasapiPlaybackQueueDepth >= FlashbackPlaybackAudioQueueBacklogWarningDepth");
        AssertContains(diagnostics.SourceFamilyText, "Flashback playback is using wall-clock pacing instead of audio-master pacing");
        AssertContains(diagnostics.SourceFamilyText, "Flashback playback audio queue is backing up");
        AssertContains(diagnostics.SourceFamilyText, "Flashback playback is below target rate");
        AssertContains(diagnostics.SourceFamilyText, "Flashback playback target is below the selected capture rate");
        AssertContains(diagnostics.SourceFamilyText, "Flashback playback is targeting HFR but D3D present cadence is below target");
        AssertContains(diagnostics.SourceFamilyText, "Flashback playback frametime degraded");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.FlashbackPlaybackLastCommandQueuedUtcUnixMs > snapshot.FlashbackPlaybackLastCommandProcessedUtcUnixMs");
        AssertContains(diagnostics.SourceFamilyText, "snapshot.FlashbackPlaybackLastCommandFailureUtcUnixMs > 0");
        AssertContains(diagnostics.SourceFamilyText, "Flashback playback command queue has not drained");
        AssertContains(diagnostics.SourceFamilyText, "var playbackCommandFailure = string.IsNullOrWhiteSpace(snapshot.FlashbackPlaybackLastCommandFailure)");
        AssertContains(diagnostics.SourceFamilyText, "lastFailure={playbackCommandFailure} failureAgeMs={playbackCommandFailureAgeMs}");
        AssertContains(diagnostics.SourceFamilyText, "\"flashback_playback\"");
        AssertContains(diagnostics.SourceFamilyText, "\"Flashback playback command queue is stalled.\"");
        AssertContains(diagnostics.SourceFamilyText, "\"Flashback playback is below target rate.\"");
        AssertContains(diagnostics.SourceFamilyText, "\"Flashback playback frametime is below target.\"");
        AssertContains(diagnostics.SourceFamilyText, "\"Flashback playback frame submission failed.\"");
        AssertContains(diagnostics.SourceFamilyText, "queuedAge={playbackCommandQueueAgeMs}ms");
        AssertContains(diagnostics.SourceFamilyText, "var playbackCommandFailure = string.IsNullOrWhiteSpace(health.FlashbackPlaybackLastCommandFailure)");
        AssertContains(diagnostics.SourceFamilyText, "var playbackTargetFps = ResolveFlashbackPlaybackTargetFps(\n            health.FlashbackPlaybackTargetFps,\n            health.ExpectedFrameRate);");
        AssertContains(diagnostics.SourceFamilyText, "lastFailure={playbackCommandFailure} failureAgeMs={playbackCommandFailureAgeMs}");
        AssertContains(diagnostics.SourceFamilyText, "playback perf state={health.FlashbackPlaybackState}");
        AssertContains(diagnostics.SourceFamilyText, "fps={health.FlashbackPlaybackObservedFps:0.##}/{playbackTargetFps:0.##}");
        AssertContains(diagnostics.SourceFamilyText, "target={health.FlashbackPlaybackTargetFps:0.##}");
        AssertContains(diagnostics.SourceFamilyText, "encoder={FormatEncoderFrameRate(health)} source={(health.SourceFrameRateExact ?? 0):0.##} present={previewRuntime.DisplayCadenceObservedFps:0.##}");
        AssertContains(diagnostics.SourceFamilyText, "private static string FormatEncoderFrameRate(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SourceFamilyText, "ptsMismatch={health.FlashbackPlaybackPtsCadenceMismatchCount} ptsDelta={health.FlashbackPlaybackLastPtsCadenceDeltaMs:0.##}/{health.FlashbackPlaybackLastPtsCadenceExpectedMs:0.##}ms");
        AssertContains(diagnostics.SourceFamilyText, "1pctLow={health.FlashbackPlaybackOnePercentLowFps:0.##}fps");
        AssertContains(diagnostics.SourceFamilyText, "private const double FlashbackPlaybackAudioMasterFallbackWarningRatio = 0.50;");
        AssertContains(diagnostics.SourceFamilyText, "private const int FlashbackPlaybackAudioQueueBacklogWarningDepth = 24;");
        AssertContains(diagnostics.SourceFamilyText, "decodeP99={health.FlashbackPlaybackDecodeP99Ms:0.##}ms");
        AssertContains(diagnostics.SourceFamilyText, "decodePhase={health.FlashbackPlaybackMaxDecodePhase}");
        AssertContains(diagnostics.SourceFamilyText, "decodeSend={health.FlashbackPlaybackMaxDecodeSendMs:0.##}ms");
        AssertContains(diagnostics.SourceFamilyText, "decodeAudio={health.FlashbackPlaybackMaxDecodeAudioMs:0.##}ms");
        AssertContains(diagnostics.SourceFamilyText, "decodePhase={snapshot.FlashbackPlaybackMaxDecodePhase}");
        AssertContains(diagnostics.SourceFamilyText, "audioMasterDouble={health.FlashbackPlaybackAudioMasterDelayDoubles}");
        AssertContains(diagnostics.SourceFamilyText, "audioMasterDouble={snapshot.FlashbackPlaybackAudioMasterDelayDoubles}");
        AssertContains(diagnostics.SourceFamilyText, "health.FlashbackPlaybackSubmitFailures <= 0");
        AssertContains(diagnostics.SourceFamilyText, "UpdatePreviewJitterRecentCounters(health, nowTick)");
        AssertContains(diagnostics.SourceFamilyText, "UpdateD3DRendererRecentCounters(previewRuntime, nowTick)");
        AssertContains(countersText, "private PreviewJitterRecentCounters UpdatePreviewJitterRecentCounters(");
        AssertContains(countersText, "private long _lastPreviewJitterTotalDropped;");
        AssertContains(countersText, "Interlocked.Exchange(ref _lastPreviewJitterTotalDropped, totalDropped)");
        AssertContains(countersText, "private D3DRendererRecentCounters UpdateD3DRendererRecentCounters(");
        AssertContains(countersText, "private long _lastD3DFramesSubmitted;");
        AssertContains(countersText, "Interlocked.Exchange(ref _lastD3DFramesSubmitted, submitted)");
        AssertDoesNotContain(diagnostics.HubText, "private long _lastPreviewJitterTotalDropped;");
        AssertDoesNotContain(diagnostics.HubText, "private long _lastD3DFramesSubmitted;");
        AssertContains(diagnostics.SourceFamilyText, "recentSubmitted={recentRendererSubmitted} recentDropped={recentRenderer.Dropped}");
        AssertContains(diagnostics.SourceFamilyText, "var previewLastDropReason = string.IsNullOrWhiteSpace(health.MjpegPreviewJitterLastDropReason)");
        AssertContains(diagnostics.SourceFamilyText, "clearedDrops={health.MjpegPreviewJitterClearedDropCount}");
        AssertContains(diagnostics.SourceFamilyText, "resumeReprimes={health.MjpegPreviewJitterResumeReprimeCount} recentDeadlineDrops={recentPreviewDeadlineDrops} recentUnderflows={recentPreviewUnderflows} lastDropReason={previewLastDropReason}");
        AssertContains(diagnostics.SourceFamilyText, "UpdateD3DFrameStatsRecentCounters(previewRuntime, nowTick)");
        AssertContains(countersText, "private long UpdateD3DFrameLatencyWaitRecentCounters(");
        AssertContains(countersText, "Interlocked.Exchange(ref _lastD3DFrameLatencyWaitTimeouts, timeouts)");
        AssertContains(diagnostics.SourceFamilyText, "recentMissed={recentD3DMissedRefreshes} recentFail={recentD3DStatsFailures}");
        AssertContains(diagnostics.SourceFamilyText, "\"capture-cadence-low-1pct\"");
        AssertContains(diagnostics.SourceFamilyText, "\"Capture cadence 1% low is below target:");
        AssertContains(diagnostics.SourceFamilyText, "\"preview-display-low-1pct\"");
        AssertContains(diagnostics.SourceFamilyText, "previewOnePercentLowDegraded && !visualCadenceHealthy");
        AssertContains(diagnostics.SourceFamilyText, "\"Preview/display 1% low is below target:");
        AssertContains(diagnostics.SourceFamilyText, "FormatVisualCadenceAlertDetail(snapshot)");
        AssertContains(diagnostics.SourceFamilyText, "visualChanges={snapshot.VisualCadenceChangeObservedFps:0.##}fps");
        AssertContains(diagnostics.SourceFamilyText, "var previewSubmitFailed = string.Equals(");
        AssertContains(diagnostics.SourceFamilyText, "health.MjpegPreviewJitterLastDropReason,\n            \"submit-failed\"");
        AssertContains(diagnostics.SourceFamilyText, "if (!previewSubmitFailed &&\n            (recentPreviewDeadlineDrops <= 0 || visualCadenceHealthy) &&\n            recentPreviewUnderflows <= 3)");
        AssertContains(diagnostics.SourceFamilyText, "\"Preview scheduler failed to submit frames.\"");
        AssertContains(diagnostics.SourceFamilyText, "var presentCadenceOverBudget =\n            previewRuntime.DisplayCadenceExpectedIntervalMs > 0 &&\n            previewRuntime.DisplayCadenceP95IntervalMs > previewRuntime.DisplayCadenceExpectedIntervalMs * 1.5;");
        AssertContains(diagnostics.SourceFamilyText, "var previewSlowFrameDetail = FormatPreviewSlowFrameAlertDetail(snapshot);");
        AssertContains(diagnostics.SourceFamilyText, "latestSlowFrameReason={reason} over={frame.WorstOverBudgetMs:0.##}ms");
        AssertContains(diagnostics.SourceFamilyText, "pipeline={frame.PipelineLatencyMs:0.##}ms pending={frame.PendingFrameCount}");
        AssertContains(diagnostics.SourceFamilyText, "inputUpload={frame.InputUploadCpuMs:0.##}ms");
        AssertContains(diagnostics.SourceFamilyText, "renderSubmit={frame.RenderSubmitCpuMs:0.##}ms");
        AssertContains(diagnostics.SourceFamilyText, "var unsyncedPresentCallSlow =\n            previewRuntime.D3DPresentSyncInterval == 0 &&\n            previewRuntime.D3DPresentCallP95Ms > 4.0;");
        AssertContains(diagnostics.SourceFamilyText, "if (presentCadenceOverBudget ||\n            unsyncedPresentCallSlow)");
        AssertContains(diagnostics.SourceFamilyText, "if (!captureOnePercentLowDegraded)");
        AssertContains(diagnostics.SourceFamilyText, "\"Source/capture 1% low is below target.\"");
        AssertContains(diagnostics.SourceFamilyText, "if (!previewOnePercentLowDegraded)");
        AssertContains(diagnostics.SourceFamilyText, "var visualCadenceHealthy =\n            IsVisualCadenceHealthy(");
        AssertContains(diagnostics.SourceFamilyText, "Present/display 1% low is below target, but sampled visual cadence confirms source-rate output.");
        AssertContains(diagnostics.SourceFamilyText, "if (visualCadenceHealthy)\n        {\n            return new DiagnosticEvaluation(\n                \"Healthy\",");
        AssertContains(diagnostics.SourceFamilyText, "private static bool IsMjpegDuplicateCadenceDetected(CaptureHealthSnapshot health)");
        AssertContains(diagnostics.SourceFamilyText, "health.MjpegPacketHashDuplicateFramePercent < 20.0");
        AssertContains(diagnostics.SourceFamilyText, "health.MjpegPacketHashUniqueObservedFps <= health.ExpectedFrameRate * 0.75");
        AssertContains(diagnostics.SourceFamilyText, "health.VisualCadenceChangeObservedFps <= health.ExpectedFrameRate * 0.75");
        AssertContains(diagnostics.SourceFamilyText, "health.SourceFrameRateExact.Value <= health.ExpectedFrameRate * 0.75");
        AssertContains(diagnostics.SourceFamilyText, "var mjpegDuplicateCadenceDetected = IsMjpegDuplicateCadenceDetected(health);");
        AssertContains(diagnostics.SourceFamilyText, "\"source_signal\"");
        AssertContains(diagnostics.SourceFamilyText, "\"Captured HFR MJPEG cadence contains repeated source frames.\"");
        AssertContains(diagnostics.SourceFamilyText, "$\"{lanes.MjpegDuplicate} | {lanes.Visual} | {lanes.SourceSignal}\"");
        AssertContains(diagnostics.SourceFamilyText, "!visualCadenceHealthy &&\n            IsPreviewOnePercentLowDegraded(");
        AssertContains(diagnostics.SourceFamilyText, "private static bool IsVisualCadenceHealthy(");
        AssertContains(diagnostics.SourceFamilyText, "changeObservedFps >= targetFrameRate * PreviewOnePercentLowWarningRatio");
        AssertContains(diagnostics.SourceFamilyText, "repeatFramePercent <= 1.0");
        AssertContains(diagnostics.SourceFamilyText, "longestRepeatRun <= 1");
        AssertContains(diagnostics.SourceFamilyText, "\"Present/display 1% low is below target.\"");
        AssertContains(countersText, "private MjpegRecentCounters UpdateMjpegRecentCounters(");
        AssertContains(diagnostics.SourceFamilyText, "var recentMjpeg = UpdateMjpegRecentCounters(health, nowTick);");
        AssertContains(diagnostics.SourceFamilyText, "recentDropped={recentMjpeg.TotalDropped} recentFailures={recentMjpeg.Failures}");
        AssertContains(diagnostics.SourceFamilyText, "recentMjpeg.TotalDropped <= 0");
        AssertContains(diagnostics.SourceFamilyText, "if (recentRendererSubmitted < DiagnosticThresholds.RendererDropWarningMinSamples ||\n            recentRendererDropPercent <= DiagnosticThresholds.RendererDropWarningPercent)");
        AssertDoesNotContain(diagnostics.SourceFamilyText, "rendererDropPercent > DiagnosticThresholds.RendererDropWarningPercent) ||\n            previewRuntime.DisplayCadenceSlowFramePercent > 1.0");
    }
}
