using System.Threading.Tasks;

static partial class Program
{
    private static Task PreviewRendererHostController_OwnsRuntimeState()
    {
        var mainWindowText = ReadRepoFile("Sussudio/MainWindow.xaml.cs").Replace("\r\n", "\n");
        var mainWindowFamilyText = string.Join(
                "\n",
                Directory.GetFiles(Path.Combine(GetRepoRoot(), "Sussudio"), "MainWindow*.cs")
                    .Select(File.ReadAllText))
            .Replace("\r\n", "\n");
        var previewRendererText = ReadRepoFile("Sussudio/MainWindow.PreviewRenderer.cs").Replace("\r\n", "\n");
        var previewRendererHostControllerText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRendererHostController.cs").Replace("\r\n", "\n");
        var previewRendererHostLifecycleText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRendererHostController.Lifecycle.cs").Replace("\r\n", "\n");
        var previewRendererHostD3dText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRendererHostController.D3D.cs").Replace("\r\n", "\n");
        var previewRendererHostReinitText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRendererHostController.Reinit.cs").Replace("\r\n", "\n");
        var previewRendererStartupPlanBuilderText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRendererStartupPlanBuilder.cs").Replace("\r\n", "\n");
        var previewRuntimeSnapshotText = ReadRepoFile("Sussudio/MainWindow.PreviewRuntimeSnapshot.cs").Replace("\r\n", "\n");
        var previewRuntimeSnapshotControllerText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeSnapshotController.cs").Replace("\r\n", "\n");
        var previewRuntimeSnapshotMapperText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeSnapshotMapper.cs").Replace("\r\n", "\n");
        var previewRuntimeSnapshotSurfaceProjectionPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeSnapshotSurfaceProjectionPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeSnapshotStartupProjectionPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeSnapshotStartupProjectionPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeSnapshotGpuPlaybackProjectionPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeSnapshotGpuPlaybackProjectionPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeSnapshotHealthInputFactoryText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeSnapshotHealthInputFactory.cs").Replace("\r\n", "\n");
        var previewRuntimeSnapshotHealthPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeSnapshotHealthPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DFrameCounterPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DFrameCounterPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DRendererStatePolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DRendererStatePolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DDisplayCadencePolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DDisplayCadencePolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DRenderCpuTimingPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DRenderCpuTimingPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DPipelineLatencyPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DPipelineLatencyPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DFrameOwnershipPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DFrameOwnershipPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DFrameStatisticsPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DFrameStatisticsPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DFrameLatencyWaitPolicyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DFrameLatencyWaitPolicy.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionRendererStateText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.RendererState.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionDisplayCadenceText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.DisplayCadence.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionRenderCpuTimingText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.RenderCpuTiming.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionPipelineLatencyText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.PipelineLatency.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionFrameOwnershipText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.FrameOwnership.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionFrameStatisticsText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.FrameStatistics.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionFrameLatencyWaitText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.FrameLatencyWait.cs").Replace("\r\n", "\n");
        var previewRuntimeD3DProjectionBuilderText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeD3DProjection.Builder.cs").Replace("\r\n", "\n");
        var statsSnapshotText = ReadRepoFile("Sussudio/MainWindow.StatsOverlay.cs").Replace("\r\n", "\n");
        var statsSnapshotProviderText = ReadRepoFile("Sussudio/Controllers/Stats/StatsSnapshotProvider.cs").Replace("\r\n", "\n");
        var previewRuntimeSnapshotInputText = ReadRepoFile("Sussudio/Controllers/Preview/Renderer/PreviewRuntimeSnapshotInput.cs").Replace("\r\n", "\n");
        var agentMapText = ReadRepoFile("docs/architecture/AGENT_MAP.md").Replace("\r\n", "\n");
        var cleanupPlanText = ReadRepoFile("docs/architecture/cleanup-plan.md").Replace("\r\n", "\n");

        AssertContains(previewRendererText, "private PreviewRendererHostController _previewRendererHostController = null!;");
        AssertContains(previewRendererText, "private void InitializePreviewRendererHostController()");
        AssertContains(previewRendererText, "GetPreviewSwapChainPanel = () => PreviewSwapChainPanel,");
        AssertContains(previewRendererText, "SetPreviewSwapChainPanel = panel => PreviewSwapChainPanel = panel,");
        AssertContains(previewRendererText, "PreviewContentGridSizeChangedHandler = OnPreviewContentGridSizeChanged,");
        AssertContains(previewRendererText, "PreviewSwapChainPanelSizeChangedHandler = OnPreviewSwapChainPanelSizeChanged,");
        AssertContains(previewRendererText, "ClearPreviewReinitAnimatingForShutdown = () =>");
        AssertContains(previewRendererText, "ConfirmPreviewFirstVisual = ConfirmPreviewFirstVisual,");
        AssertContains(previewRendererText, "MarkStartupFailed = reason => SetPreviewStartupState(PreviewStartupState.Failed, reason),");
        AssertContains(previewRendererText, "ConfigurePreviewStartupSignals = ConfigurePreviewStartupSignals,");
        AssertContains(previewRendererText, "private Task StartPreviewRendererAsync()");
        AssertContains(previewRendererText, "=> _previewRendererHostController.StartAsync();");
        AssertContains(previewRendererText, "private Task StopPreviewRendererAsync()");
        AssertContains(previewRendererText, "=> _previewRendererHostController.StopAsync();");
        AssertContains(previewRendererText, "private void StopPreviewForShutdown()");
        AssertContains(previewRendererText, "=> _previewRendererHostController.StopForShutdown();");
        AssertContains(mainWindowText, "InitializePreviewRendererHostController();");

        AssertContains(previewRendererHostControllerText, "internal sealed class PreviewRendererHostControllerContext");
        AssertContains(previewRendererHostControllerText, "internal sealed partial class PreviewRendererHostController");
        AssertContains(previewRendererHostLifecycleText, "internal sealed partial class PreviewRendererHostController");
        AssertContains(previewRendererHostD3dText, "internal sealed partial class PreviewRendererHostController");
        AssertContains(previewRendererHostReinitText, "internal sealed partial class PreviewRendererHostController");
        AssertContains(previewRendererHostControllerText, "private SoftwareBitmapSource? _previewSource;");
        AssertContains(previewRendererHostControllerText, "private D3D11PreviewRenderer? _d3dRenderer;");
        AssertContains(previewRendererHostControllerText, "private long _previewFramesArrived;");
        AssertContains(previewRendererHostControllerText, "private long _previewFramesDisplayed;");
        AssertContains(previewRendererHostControllerText, "private long _previewFramesDropped;");
        AssertContains(previewRendererHostControllerText, "private long _previewLastPresentedTick;");
        AssertContains(previewRendererHostControllerText, "private double _previewMinPresentationIntervalMs;");
        AssertContains(previewRendererHostControllerText, "private long _lastRendererStopTick;");
        AssertContains(previewRendererHostControllerText, "private long _rendererReinitUnsafeWindows;");
        AssertContains(previewRendererHostControllerText, "public D3D11PreviewRenderer? Renderer => _d3dRenderer;");
        AssertContains(previewRendererHostControllerText, "public bool HasD3DRenderer => _d3dRenderer != null;");
        AssertContains(previewRendererHostControllerText, "public bool IsCpuPreviewSourceAttached => _previewSource != null;");
        AssertContains(previewRendererHostControllerText, "public double PreviewMinPresentationIntervalMs => _previewMinPresentationIntervalMs;");
        AssertContains(previewRendererHostControllerText, "public long RendererReinitUnsafeWindows => Interlocked.Read(ref _rendererReinitUnsafeWindows);");
        AssertContains(previewRendererHostControllerText, "public int? PendingFrameCount => _d3dRenderer?.PendingFrameCount;");
        AssertContains(previewRendererHostLifecycleText, "public Task StartAsync()");
        AssertContains(previewRendererHostLifecycleText, "RecordPreviewRendererReinitUnsafeWindow(_d3dRenderer, _context.IsPreviewReinitAnimating());");
        AssertContains(previewRendererHostLifecycleText, "var startupPlan = BuildPreviewRendererStartupPlan();");
        AssertContains(previewRendererHostLifecycleText, "_previewMinPresentationIntervalMs = startupPlan.PreviewMinPresentationIntervalMs;");
        AssertContains(previewRendererHostLifecycleText, "private PreviewRendererStartupPlan BuildPreviewRendererStartupPlan()");
        AssertContains(previewRendererHostLifecycleText, "PreviewRendererStartupPlanBuilder.Build(");
        AssertContains(previewRendererHostLifecycleText, "private void CleanupPreviewResources()");
        AssertContains(previewRendererHostLifecycleText, "_d3dRenderer = null;");
        AssertContains(previewRendererHostLifecycleText, "public Task StopAsync()");
        AssertContains(previewRendererHostD3dText, "private void StartD3DRenderer(PreviewRendererStartupPlan startupPlan)");
        AssertContains(previewRendererHostD3dText, "renderer.SetExpectedFrameRate(rendererFps);");
        AssertContains(previewRendererHostD3dText, "renderer.Start(rendererWidth, rendererHeight, rendererFps, isHdr);");
        AssertContains(previewRendererHostD3dText, "_context.ViewModel.SetPreviewFrameSink(_d3dRenderer);");
        AssertContains(previewRendererHostD3dText, "PreviewStartupStrategy.D3D11VideoProcessor");
        AssertContains(previewRendererHostD3dText, "_context.MarkPreviewRendererAttached();");
        AssertContains(previewRendererHostD3dText, "private D3D11PreviewRenderer CreateFreshD3DPreviewRenderer(bool replaceSwapChainSurface)");
        AssertContains(previewRendererHostD3dText, "private void OnD3DRendererFirstFrameRendered()");
        AssertContains(previewRendererHostD3dText, "private void OnD3DRendererRenderThreadFailed(string reason)");
        AssertContains(previewRendererHostLifecycleText, "private void StartCpuRenderer()");
        AssertContains(previewRendererHostLifecycleText, "_context.ViewModel.SetPreviewFrameSink(null);");
        AssertContains(previewRendererHostLifecycleText, "_previewSource = new SoftwareBitmapSource();");
        AssertContains(previewRendererHostReinitText, "private void RecordPreviewRendererReinitUnsafeWindow(D3D11PreviewRenderer? previousRenderer, bool reinitAnimating)");
        AssertContains(previewRendererHostReinitText, "private void MarkPreviewRendererStopped()");
        AssertContains(previewRendererHostReinitText, "public Task StopRendererForReinitTeardownAsync()");
        AssertContains(previewRendererHostReinitText, "PREVIEW_REINIT_RENDERER_STOP: stopping render thread before pipeline teardown");
        AssertContains(previewRendererHostReinitText, "catch (TimeoutException ex)");
        AssertContains(previewRendererHostReinitText, "PREVIEW_REINIT_RENDERER_STOP_TIMEOUT: {ex.Message}; continuing reinit with orphan render thread expected to exit shortly.");
        AssertContains(previewRendererHostReinitText, "public void DisposeD3DPreviewRendererForReinit()");
        AssertContains(previewRendererHostReinitText, "renderer.RetireSharedDeviceReferenceForReinit();");
        AssertContains(previewRendererHostReinitText, "private void ReplacePreviewSwapChainPanelSurface()");
        AssertContains(previewRendererHostReinitText, "D3D11_RENDERER_REINIT_UNSAFE_WINDOW");
        AssertContains(previewRendererHostReinitText, "PREVIEW_REINIT_SWAPCHAIN_PANEL_REPLACED");
        AssertContains(agentMapText, "PreviewRendererHostController.Lifecycle.cs");
        AssertContains(agentMapText, "PreviewRendererHostController.D3D.cs");
        AssertContains(agentMapText, "PreviewRendererHostController.Reinit.cs");
        AssertContains(agentMapText, "PreviewRuntimeSnapshotInput.cs");
        AssertContains(agentMapText, "PreviewRuntimeSnapshotMapper.cs");
        AssertContains(agentMapText, "PreviewRuntimeSnapshotSurfaceProjectionPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeSnapshotStartupProjectionPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeSnapshotGpuPlaybackProjectionPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeSnapshotHealthInputFactory.cs");
        AssertContains(agentMapText, "PreviewRuntimeSnapshotHealthPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DFrameCounterPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DRendererStatePolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DDisplayCadencePolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DRenderCpuTimingPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DPipelineLatencyPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DFrameOwnershipPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DFrameStatisticsPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DFrameLatencyWaitPolicy.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.RendererState.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.DisplayCadence.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.RenderCpuTiming.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.PipelineLatency.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.FrameOwnership.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.FrameStatistics.cs");
        AssertContains(agentMapText, "PreviewRuntimeD3DProjection.FrameLatencyWait.cs");
        AssertContains(cleanupPlanText, "PreviewRendererHostController.Lifecycle.cs");
        AssertContains(cleanupPlanText, "PreviewRendererHostController.D3D.cs");
        AssertContains(cleanupPlanText, "PreviewRendererHostController.Reinit.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeSnapshotInput.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeSnapshotMapper.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeSnapshotSurfaceProjectionPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeSnapshotStartupProjectionPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeSnapshotGpuPlaybackProjectionPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeSnapshotHealthInputFactory.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeSnapshotHealthPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DFrameCounterPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DRendererStatePolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DDisplayCadencePolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DRenderCpuTimingPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DPipelineLatencyPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DFrameOwnershipPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DFrameStatisticsPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DFrameLatencyWaitPolicy.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.RendererState.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.DisplayCadence.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.RenderCpuTiming.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.PipelineLatency.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.FrameOwnership.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.FrameStatistics.cs");
        AssertContains(cleanupPlanText, "PreviewRuntimeD3DProjection.FrameLatencyWait.cs");
        AssertContains(previewRendererText, "=> _previewRendererHostController.RendererReinitUnsafeWindows;");
        AssertDoesNotContain(previewRendererText, "DisposeD3DPreviewRendererForReinit");

        AssertContains(previewRendererStartupPlanBuilderText, "internal sealed record PreviewRendererStartupPlan(");
        AssertContains(previewRendererStartupPlanBuilderText, "internal static class PreviewRendererStartupPlanBuilder");
        AssertContains(previewRendererStartupPlanBuilderText, "private const int DefaultWidth = 1920;");
        AssertContains(previewRendererStartupPlanBuilderText, "private const int DefaultHeight = 1080;");
        AssertContains(previewRendererStartupPlanBuilderText, "private const double DefaultFps = 60.0;");
        AssertContains(previewRendererStartupPlanBuilderText, "public static double ResolveExpectedIntervalMs(MediaFormat? selectedFormat)");
        AssertContains(previewRendererStartupPlanBuilderText, "public static PreviewRendererStartupPlan Build(");
        AssertContains(previewRendererStartupPlanBuilderText, "var negotiatedWidth = sourceProbe?.SessionActive == true ? sourceProbe.CurrentWidth : 0;");
        AssertContains(previewRendererStartupPlanBuilderText, "var rendererWidth = negotiatedWidth > 0 ? negotiatedWidth : settingsWidth;");
        AssertContains(previewRendererStartupPlanBuilderText, "var rendererFps = negotiatedFps > 0 ? negotiatedFps : settingsFps;");

        AssertContains(previewRuntimeSnapshotText, "private async Task<PreviewRuntimeSnapshot> GetPreviewRuntimeSnapshotAsync(CancellationToken cancellationToken = default)");
        AssertContains(previewRuntimeSnapshotText, "=> await WindowUiDispatchController.InvokeWithRetryAsync(");
        AssertContains(previewRuntimeSnapshotText, "GetPreviewRuntimeSnapshot,");
        AssertContains(previewRuntimeSnapshotText, "\"Failed to enqueue preview snapshot operation.\",");
        AssertContains(previewRuntimeSnapshotText, "cancellationToken).ConfigureAwait(false);");
        AssertContains(previewRuntimeSnapshotText, "private PreviewRuntimeSnapshot GetPreviewRuntimeSnapshot()");
        AssertContains(previewRuntimeSnapshotText, "return PreviewRuntimeSnapshotController.Build(new PreviewRuntimeSnapshotInput");
        AssertContains(previewRuntimeSnapshotText, "D3DRenderer = _previewRendererHostController.Renderer,");
        AssertContains(previewRuntimeSnapshotText, "PreviewSourceAttached = _previewRendererHostController.IsCpuPreviewSourceAttached,");
        AssertContains(previewRuntimeSnapshotText, "GpuElementVisible = PreviewSwapChainPanel.Visibility == Visibility.Visible,");
        AssertContains(previewRuntimeSnapshotText, "FramesArrived = _previewRendererHostController.FramesArrived,");
        AssertContains(previewRuntimeSnapshotText, "PreviewMinPresentationIntervalMs = _previewRendererHostController.PreviewMinPresentationIntervalMs,");
        AssertContains(previewRuntimeSnapshotText, "StartupState = CurrentPreviewStartupState.ToString(),");
        AssertContains(previewRuntimeSnapshotText, "GpuPositionEventCount = PreviewStartupGpuPositionEventCount");
        AssertContains(previewRuntimeSnapshotInputText, "internal sealed class PreviewRuntimeSnapshotInput");
        AssertContains(previewRuntimeSnapshotInputText, "public D3D11PreviewRenderer? D3DRenderer { get; init; }");
        AssertContains(previewRuntimeSnapshotInputText, "public PreviewStartupSignalFlags StartupRequiredSignals { get; init; }");
        AssertContains(previewRuntimeSnapshotInputText, "public long GpuPositionEventCount { get; init; }");
        AssertDoesNotContain(previewRuntimeSnapshotControllerText, "internal sealed class PreviewRuntimeSnapshotInput");
        AssertContains(previewRuntimeSnapshotControllerText, "internal static class PreviewRuntimeSnapshotController");
        AssertContains(previewRuntimeSnapshotControllerText, "public static PreviewRuntimeSnapshot Build(PreviewRuntimeSnapshotInput input)");
        AssertContains(previewRuntimeSnapshotControllerText, "var d3dProjection = PreviewRuntimeD3DProjection.Build(input);");
        AssertContains(previewRuntimeSnapshotControllerText, "var healthInput = PreviewRuntimeSnapshotHealthInputFactory.Build(");
        AssertContains(previewRuntimeSnapshotControllerText, "Environment.TickCount64,");
        AssertContains(previewRuntimeSnapshotControllerText, "var health = PreviewRuntimeSnapshotHealthPolicy.Evaluate(healthInput);");
        AssertContains(previewRuntimeSnapshotControllerText, "return PreviewRuntimeSnapshotMapper.Build(input, d3dProjection, health, DateTimeOffset.UtcNow);");
        AssertContains(previewRuntimeSnapshotMapperText, "internal static class PreviewRuntimeSnapshotMapper");
        AssertContains(previewRuntimeSnapshotMapperText, "public static PreviewRuntimeSnapshot Build(");
        AssertContains(previewRuntimeSnapshotMapperText, "var surface = PreviewRuntimeSnapshotSurfaceProjectionPolicy.Evaluate(input, d3dProjection, health);");
        AssertContains(previewRuntimeSnapshotMapperText, "var startup = PreviewRuntimeSnapshotStartupProjectionPolicy.Evaluate(input, health);");
        AssertContains(previewRuntimeSnapshotMapperText, "var gpuPlayback = PreviewRuntimeSnapshotGpuPlaybackProjectionPolicy.Evaluate(input, d3dProjection);");
        AssertContains(previewRuntimeSnapshotMapperText, "return new PreviewRuntimeSnapshot");
        AssertContains(previewRuntimeSnapshotMapperText, "TimestampUtc = timestampUtc,");
        AssertContains(previewRuntimeSnapshotMapperText, "IsPreviewing = surface.IsPreviewing,");
        AssertContains(previewRuntimeSnapshotMapperText, "FramesArrived = surface.FramesArrived,");
        AssertContains(previewRuntimeSnapshotMapperText, "StartupState = startup.State,");
        AssertContains(previewRuntimeSnapshotMapperText, "StartupElapsedMs = startup.ElapsedMs,");
        AssertContains(previewRuntimeSnapshotMapperText, "BlankSuspected = surface.BlankSuspected,");
        AssertContains(previewRuntimeSnapshotMapperText, "StallSuspected = surface.StallSuspected,");
        AssertContains(previewRuntimeSnapshotMapperText, "GpuPlaybackState = gpuPlayback.PlaybackState,");
        AssertContains(previewRuntimeSnapshotMapperText, "GpuPositionEventCount = gpuPlayback.PositionEventCount");
        AssertContains(previewRuntimeSnapshotSurfaceProjectionPolicyText, "internal static class PreviewRuntimeSnapshotSurfaceProjectionPolicy");
        AssertContains(previewRuntimeSnapshotSurfaceProjectionPolicyText, "public static PreviewRuntimeSnapshotSurfaceProjection Evaluate(");
        AssertContains(previewRuntimeSnapshotSurfaceProjectionPolicyText, "GpuActive: d3dProjection.GpuActive,");
        AssertContains(previewRuntimeSnapshotSurfaceProjectionPolicyText, "BlankSuspected: health.BlankSuspected,");
        AssertContains(previewRuntimeSnapshotStartupProjectionPolicyText, "internal static class PreviewRuntimeSnapshotStartupProjectionPolicy");
        AssertContains(previewRuntimeSnapshotStartupProjectionPolicyText, "public static PreviewRuntimeSnapshotStartupProjection Evaluate(");
        AssertContains(previewRuntimeSnapshotStartupProjectionPolicyText, "ElapsedMs: health.StartupElapsedMs,");
        AssertContains(previewRuntimeSnapshotStartupProjectionPolicyText, "RecoveryAttemptCount: input.StartupRecoveryAttemptCount,");
        AssertContains(previewRuntimeSnapshotGpuPlaybackProjectionPolicyText, "internal static class PreviewRuntimeSnapshotGpuPlaybackProjectionPolicy");
        AssertContains(previewRuntimeSnapshotGpuPlaybackProjectionPolicyText, "public static PreviewRuntimeSnapshotGpuPlaybackProjection Evaluate(");
        AssertContains(previewRuntimeSnapshotGpuPlaybackProjectionPolicyText, "PlaybackState: d3dProjection.GpuPlaybackState,");
        AssertContains(previewRuntimeSnapshotGpuPlaybackProjectionPolicyText, "PositionEventCount: input.GpuPositionEventCount);");
        AssertDoesNotContain(previewRuntimeSnapshotMapperText, "GpuActive = d3dProjection.GpuActive,");
        AssertDoesNotContain(previewRuntimeSnapshotMapperText, "FramesArrived = d3dProjection.FramesArrived,");
        AssertDoesNotContain(previewRuntimeSnapshotMapperText, "BlankSuspected = health.BlankSuspected,");
        AssertDoesNotContain(previewRuntimeSnapshotMapperText, "StallSuspected = health.StallSuspected,");
        AssertDoesNotContain(previewRuntimeSnapshotMapperText, "StartupElapsedMs = health.StartupElapsedMs,");
        AssertDoesNotContain(previewRuntimeSnapshotMapperText, "StartupRecoveryAttemptCount = input.StartupRecoveryAttemptCount,");
        AssertDoesNotContain(previewRuntimeSnapshotMapperText, "GpuPlaybackState = d3dProjection.GpuPlaybackState,");
        AssertDoesNotContain(previewRuntimeSnapshotMapperText, "GpuPositionEventCount = input.GpuPositionEventCount");
        AssertDoesNotContain(previewRuntimeSnapshotControllerText, "return new PreviewRuntimeSnapshot");
        AssertDoesNotContain(previewRuntimeSnapshotControllerText, "BlankSuspected = health.BlankSuspected,");
        AssertDoesNotContain(previewRuntimeSnapshotControllerText, "StallSuspected = health.StallSuspected,");
        AssertContains(previewRuntimeSnapshotHealthInputFactoryText, "internal static class PreviewRuntimeSnapshotHealthInputFactory");
        AssertContains(previewRuntimeSnapshotHealthInputFactoryText, "public static PreviewRuntimeSnapshotHealthInput Build(");
        AssertContains(previewRuntimeSnapshotHealthInputFactoryText, "RendererAttached = d3dProjection.RendererAttached,");
        AssertContains(previewRuntimeSnapshotHealthInputFactoryText, "CurrentTick = currentTick,");
        AssertContains(previewRuntimeSnapshotHealthInputFactoryText, "UtcNow = utcNow");
        AssertContains(previewRuntimeSnapshotHealthPolicyText, "internal static class PreviewRuntimeSnapshotHealthPolicy");
        AssertContains(previewRuntimeSnapshotHealthPolicyText, "public static PreviewRuntimeSnapshotHealth Evaluate(PreviewRuntimeSnapshotHealthInput input)");
        AssertContains(previewRuntimeSnapshotHealthPolicyText, "var startupTimedOut = input.IsPreviewing");
        AssertContains(previewRuntimeSnapshotHealthPolicyText, "input.FramesArrived > 30");
        AssertContains(previewRuntimeSnapshotHealthPolicyText, "input.CurrentTick - input.LastPresentedTick > 3000");
        AssertDoesNotContain(previewRuntimeSnapshotControllerText, "new PreviewRuntimeSnapshotHealthInput");
        AssertDoesNotContain(previewRuntimeSnapshotControllerText, "RendererAttached = d3dProjection.RendererAttached,");
        AssertDoesNotContain(previewRuntimeSnapshotControllerText, "var startupTimedOut = input.IsPreviewing");
        AssertDoesNotContain(previewRuntimeSnapshotControllerText, "input.LastPresentedTick > 0");
        AssertContains(previewRuntimeD3DProjectionText, "internal sealed partial class PreviewRuntimeD3DProjection");
        AssertContains(previewRuntimeD3DProjectionText, "public bool GpuActive { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionText, "public long D3DFramesDropped { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionText, "private void ApplyFrameCounters(PreviewRuntimeD3DFrameCounters frameCounters)");
        AssertContains(previewRuntimeD3DProjectionText, "FramesArrived = frameCounters.FramesArrived;");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "DisplayCadenceRecentIntervalsMs");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "D3DInputUploadCpuAvgMs");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "D3DLastSubmittedPreviewPresentId");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "D3DFrameStatsPresentCount");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "D3DFrameLatencyWaitEnabled");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "GpuPlaybackState");
        AssertContains(previewRuntimeD3DProjectionRendererStateText, "internal sealed partial class PreviewRuntimeD3DProjection");
        AssertContains(previewRuntimeD3DProjectionRendererStateText, "public string RendererMode { get; private set; } = \"None\";");
        AssertContains(previewRuntimeD3DProjectionRendererStateText, "public PreviewSlowFrameDiagnostic[] D3DRecentSlowFrames { get; private set; } = Array.Empty<PreviewSlowFrameDiagnostic>();");
        AssertContains(previewRuntimeD3DProjectionRendererStateText, "public string GpuPlaybackState { get; private set; } = \"None\";");
        AssertContains(previewRuntimeD3DProjectionRendererStateText, "private void ApplyRendererState(PreviewRuntimeD3DRendererState rendererState)");
        AssertContains(previewRuntimeD3DProjectionRendererStateText, "GpuPlaybackState = rendererState.GpuPlaybackState;");
        AssertContains(previewRuntimeD3DProjectionDisplayCadenceText, "public double[] DisplayCadenceRecentIntervalsMs { get; private set; } = Array.Empty<double>();");
        AssertContains(previewRuntimeD3DProjectionDisplayCadenceText, "private void ApplyDisplayCadence(PreviewRuntimeD3DDisplayCadence displayCadence)");
        AssertContains(previewRuntimeD3DProjectionDisplayCadenceText, "DisplayCadenceRecentIntervalsMs = displayCadence.RecentIntervalsMs;");
        AssertContains(previewRuntimeD3DProjectionRenderCpuTimingText, "public double D3DInputUploadCpuAvgMs { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionRenderCpuTimingText, "private void ApplyRenderCpuTiming(PreviewRuntimeD3DRenderCpuTiming renderCpuTiming)");
        AssertContains(previewRuntimeD3DProjectionRenderCpuTimingText, "D3DInputUploadCpuAvgMs = renderCpuTiming.InputUploadAverageMs;");
        AssertContains(previewRuntimeD3DProjectionPipelineLatencyText, "public double EstimatedPipelineLatencyMs { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionPipelineLatencyText, "private void ApplyPipelineLatency(PreviewRuntimeD3DPipelineLatency pipelineLatency)");
        AssertContains(previewRuntimeD3DProjectionPipelineLatencyText, "EstimatedPipelineLatencyMs = pipelineLatency.EstimatedPipelineLatencyMs;");
        AssertContains(previewRuntimeD3DProjectionFrameOwnershipText, "public long D3DLastSubmittedPreviewPresentId { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionFrameOwnershipText, "private void ApplyFrameOwnership(PreviewRuntimeD3DFrameOwnership frameOwnership)");
        AssertContains(previewRuntimeD3DProjectionFrameOwnershipText, "D3DLastSubmittedSourceSequenceNumber = frameOwnership.LastSubmittedSourceSequenceNumber;");
        AssertContains(previewRuntimeD3DProjectionFrameStatisticsText, "public long D3DFrameStatsPresentCount { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionFrameStatisticsText, "private void ApplyFrameStatistics(PreviewRuntimeD3DFrameStatistics frameStatistics)");
        AssertContains(previewRuntimeD3DProjectionFrameStatisticsText, "D3DFrameStatsPresentCount = frameStatistics.PresentCount;");
        AssertContains(previewRuntimeD3DProjectionFrameLatencyWaitText, "public bool D3DFrameLatencyWaitEnabled { get; private set; }");
        AssertContains(previewRuntimeD3DProjectionFrameLatencyWaitText, "private void ApplyFrameLatencyWait(PreviewRuntimeD3DFrameLatencyWait frameLatencyWait)");
        AssertContains(previewRuntimeD3DProjectionFrameLatencyWaitText, "D3DFrameLatencyWaitEnabled = frameLatencyWait.Enabled;");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "internal sealed partial class PreviewRuntimeD3DProjection");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "public static PreviewRuntimeD3DProjection Build(PreviewRuntimeSnapshotInput input)");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var frameCounters = PreviewRuntimeD3DFrameCounterPolicy.Evaluate(input);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var d3d = input.D3DRenderer;");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var rendererState = PreviewRuntimeD3DRendererStatePolicy.Evaluate(d3d, input.IsPreviewing);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var displayCadence = PreviewRuntimeD3DDisplayCadencePolicy.Evaluate(d3d, input.PreviewMinPresentationIntervalMs);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var renderCpuTiming = PreviewRuntimeD3DRenderCpuTimingPolicy.Evaluate(d3d);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var pipelineLatency = PreviewRuntimeD3DPipelineLatencyPolicy.Evaluate(d3d);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var frameOwnership = PreviewRuntimeD3DFrameOwnershipPolicy.Evaluate(d3d);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var frameStatistics = PreviewRuntimeD3DFrameStatisticsPolicy.Evaluate(d3d);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var frameLatencyWait = PreviewRuntimeD3DFrameLatencyWaitPolicy.Evaluate(d3d);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "var projection = new PreviewRuntimeD3DProjection();");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyFrameCounters(frameCounters);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyRendererState(rendererState);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyDisplayCadence(displayCadence);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyRenderCpuTiming(renderCpuTiming);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyPipelineLatency(pipelineLatency);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyFrameLatencyWait(frameLatencyWait);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyFrameStatistics(frameStatistics);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "projection.ApplyFrameOwnership(frameOwnership);");
        AssertContains(previewRuntimeD3DProjectionBuilderText, "return projection;");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "FramesArrived = frameCounters.FramesArrived,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DFramesSubmitted = frameCounters.D3DFramesSubmitted,");
        AssertContains(previewRuntimeD3DFrameCounterPolicyText, "internal static class PreviewRuntimeD3DFrameCounterPolicy");
        AssertContains(previewRuntimeD3DFrameCounterPolicyText, "public static PreviewRuntimeD3DFrameCounters Evaluate(PreviewRuntimeSnapshotInput input)");
        AssertContains(previewRuntimeD3DFrameCounterPolicyText, "FramesArrived: gpuActive ? d3dFramesSubmitted : input.FramesArrived,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var framesArrived = gpuActive ? d3dFramesSubmitted : input.FramesArrived;");
        AssertContains(previewRuntimeD3DRendererStatePolicyText, "internal static class PreviewRuntimeD3DRendererStatePolicy");
        AssertContains(previewRuntimeD3DRendererStatePolicyText, "public static PreviewRuntimeD3DRendererState Evaluate(D3D11PreviewRenderer? d3d, bool isPreviewing)");
        AssertContains(previewRuntimeD3DRendererStatePolicyText, "RendererMode: d3d?.RendererMode ?? (isPreviewing ? \"CpuSoftwareBitmap\" : \"None\"),");
        AssertContains(previewRuntimeD3DRendererStatePolicyText, "RecentSlowFrames: d3d?.GetRecentSlowFrameDiagnostics() ?? Array.Empty<PreviewSlowFrameDiagnostic>(),");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "RendererMode = rendererState.RendererMode,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DRecentSlowFrames = rendererState.RecentSlowFrames,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "GpuPlaybackState = rendererState.GpuPlaybackState,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "RendererMode = d3d?.RendererMode ?? (input.IsPreviewing ? \"CpuSoftwareBitmap\" : \"None\"),");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "d3d?.GetRecentSlowFrameDiagnostics() ?? Array.Empty<PreviewSlowFrameDiagnostic>()");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "GpuPlaybackState = d3d == null ? \"None\" : (d3d.IsRendering ? \"Rendering\" : \"Idle\"),");
        AssertContains(previewRuntimeD3DDisplayCadencePolicyText, "internal static class PreviewRuntimeD3DDisplayCadencePolicy");
        AssertContains(previewRuntimeD3DDisplayCadencePolicyText, "public static PreviewRuntimeD3DDisplayCadence Evaluate(");
        AssertContains(previewRuntimeD3DDisplayCadencePolicyText, "RecentIntervalsMs: displayCadence?.RecentIntervalsMs ?? Array.Empty<double>(),");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "DisplayCadenceObservedFps = displayCadence.ObservedFps,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "DisplayCadenceRecentIntervalsMs = displayCadence.RecentIntervalsMs,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var rendererCadence = d3d?.GetPresentCadenceMetrics(input.PreviewMinPresentationIntervalMs);");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "rendererCadence?.RecentIntervalsMs ?? Array.Empty<double>()");
        AssertContains(previewRuntimeD3DRenderCpuTimingPolicyText, "internal static class PreviewRuntimeD3DRenderCpuTimingPolicy");
        AssertContains(previewRuntimeD3DRenderCpuTimingPolicyText, "public static PreviewRuntimeD3DRenderCpuTiming Evaluate(D3D11PreviewRenderer? d3d)");
        AssertContains(previewRuntimeD3DRenderCpuTimingPolicyText, "SampleCount: renderCpuTiming?.TotalFrame.SampleCount ?? 0,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DInputUploadCpuAvgMs = renderCpuTiming.InputUploadAverageMs,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var d3dRenderCpuTiming = d3d?.GetRenderCpuTimingMetrics();");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "d3dRenderCpuTiming?.TotalFrame.SampleCount ?? 0");
        AssertContains(previewRuntimeD3DPipelineLatencyPolicyText, "internal static class PreviewRuntimeD3DPipelineLatencyPolicy");
        AssertContains(previewRuntimeD3DPipelineLatencyPolicyText, "public static PreviewRuntimeD3DPipelineLatency Evaluate(D3D11PreviewRenderer? d3d)");
        AssertContains(previewRuntimeD3DPipelineLatencyPolicyText, "EstimatedPipelineLatencyMs: pipelineLatency?.AverageMs ?? 0);");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DPipelineLatencyAvgMs = pipelineLatency.AverageMs,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "EstimatedPipelineLatencyMs = pipelineLatency.EstimatedPipelineLatencyMs,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var d3dPipelineLatency = d3d?.GetPipelineLatencyMetrics();");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "d3dPipelineLatency?.AverageMs ?? 0");
        AssertContains(previewRuntimeD3DFrameStatisticsPolicyText, "internal static class PreviewRuntimeD3DFrameStatisticsPolicy");
        AssertContains(previewRuntimeD3DFrameStatisticsPolicyText, "public static PreviewRuntimeD3DFrameStatistics Evaluate(D3D11PreviewRenderer? d3d)");
        AssertContains(previewRuntimeD3DFrameStatisticsPolicyText, "PresentCount: frameStats?.PresentCount ?? -1,");
        AssertContains(previewRuntimeD3DFrameLatencyWaitPolicyText, "internal static class PreviewRuntimeD3DFrameLatencyWaitPolicy");
        AssertContains(previewRuntimeD3DFrameLatencyWaitPolicyText, "public static PreviewRuntimeD3DFrameLatencyWait Evaluate(D3D11PreviewRenderer? d3d)");
        AssertContains(previewRuntimeD3DFrameLatencyWaitPolicyText, "SampleCount: frameLatencyWait?.Timing.SampleCount ?? 0,");
        AssertContains(previewRuntimeD3DFrameOwnershipPolicyText, "internal static class PreviewRuntimeD3DFrameOwnershipPolicy");
        AssertContains(previewRuntimeD3DFrameOwnershipPolicyText, "public static PreviewRuntimeD3DFrameOwnership Evaluate(D3D11PreviewRenderer? d3d)");
        AssertContains(previewRuntimeD3DFrameOwnershipPolicyText, "LastSubmittedSourceSequenceNumber: frameOwnership?.LastSubmittedSourceSequenceNumber ?? -1,");
        AssertContains(previewRuntimeD3DFrameOwnershipPolicyText, "LastDroppedSourceSequenceNumber: frameOwnership?.LastDroppedSourceSequenceNumber ?? -1,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DLastSubmittedSourceSequenceNumber = frameOwnership.LastSubmittedSourceSequenceNumber,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DFrameStatsPresentCount = frameStatistics.PresentCount,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DFrameLatencyWaitEnabled = frameLatencyWait.Enabled,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var d3dFrameOwnership = d3d?.GetFrameOwnershipMetrics();");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "d3dFrameOwnership?.LastSubmittedSourceSequenceNumber ?? -1");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var d3dFrameStats = d3d?.GetDxgiFrameStatisticsMetrics();");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "d3dFrameStats?.PresentCount ?? -1");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "var d3dFrameLatencyWait = d3d?.GetFrameLatencyWaitMetrics();");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "d3dFrameLatencyWait?.Timing.SampleCount ?? 0");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "D3DRecentSlowFrames = rendererState.RecentSlowFrames,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "EstimatedPipelineLatencyMs = pipelineLatency.EstimatedPipelineLatencyMs,");
        AssertDoesNotContain(previewRuntimeD3DProjectionBuilderText, "GpuPlaybackState = rendererState.GpuPlaybackState,");
        AssertDoesNotContain(previewRuntimeD3DProjectionText, "public static PreviewRuntimeD3DProjection Build(PreviewRuntimeSnapshotInput input)");

        AssertContains(statsSnapshotText, "GetRenderer = () => _previewRendererHostController.Renderer,");
        AssertContains(statsSnapshotText, "GetPreviewMinPresentationIntervalMs = () => _previewRendererHostController.PreviewMinPresentationIntervalMs");
        AssertContains(statsSnapshotProviderText, "BuildRenderMetrics(_context.GetRenderer(), _context.GetPreviewMinPresentationIntervalMs())");
        AssertContains(statsSnapshotProviderText, "GetPresentCadenceMetrics(previewMinPresentationIntervalMs)");

        AssertDoesNotContain(previewRendererText, "var sourceFps = ViewModel.SelectedFormat?.FrameRateExact ?? 0;");
        AssertDoesNotContain(previewRendererText, "var negotiatedWidth = sourceProbe.SessionActive ? sourceProbe.CurrentWidth : 0;");
        AssertDoesNotContain(previewRendererText, "var rendererWidth = negotiatedWidth > 0 ? negotiatedWidth : width;");
        AssertDoesNotContain(previewRuntimeSnapshotText, "TaskCompletionSource<PreviewRuntimeSnapshot>");
        AssertDoesNotContain(previewRuntimeSnapshotText, "return new PreviewRuntimeSnapshot");
        AssertDoesNotContain(previewRuntimeSnapshotText, "GetRenderCpuTimingMetrics()");
        AssertDoesNotContain(previewRuntimeSnapshotText, "GetFrameOwnershipMetrics()");
        AssertDoesNotContain(previewRuntimeSnapshotText, "GetDxgiFrameStatisticsMetrics()");
        AssertDoesNotContain(previewRuntimeSnapshotText, "GetFrameLatencyWaitMetrics()");
        AssertDoesNotContain(previewRuntimeSnapshotText, "GetPipelineLatencyMetrics()");
        AssertDoesNotContain(previewRuntimeSnapshotText, "_dispatcherQueue.TryEnqueue");
        AssertDoesNotContain(previewRuntimeSnapshotText, "const int maxAttempts = 3;");
        AssertDoesNotContain(previewRuntimeSnapshotText, "completion.TrySetResult(GetPreviewRuntimeSnapshot());");
        AssertDoesNotContain(previewRuntimeSnapshotText, "await Task.Delay(50, cancellationToken).ConfigureAwait(false);");
        AssertDoesNotContain(mainWindowFamilyText, "private SoftwareBitmapSource? _previewSource;");
        AssertDoesNotContain(mainWindowFamilyText, "private D3D11PreviewRenderer? _d3dRenderer;");
        AssertDoesNotContain(previewRendererHostControllerText, "private void StartD3DRenderer(PreviewRendererStartupPlan startupPlan)");
        AssertDoesNotContain(previewRendererHostControllerText, "private void StartCpuRenderer()");
        AssertDoesNotContain(previewRendererHostControllerText, "private void CleanupPreviewResources()");
        AssertDoesNotContain(previewRendererHostControllerText, "private void ReplacePreviewSwapChainPanelSurface()");
        AssertDoesNotContain(mainWindowFamilyText, "private long _previewFramesArrived;");
        AssertDoesNotContain(mainWindowFamilyText, "private long _previewFramesDisplayed;");
        AssertDoesNotContain(mainWindowFamilyText, "private long _previewFramesDropped;");
        AssertDoesNotContain(mainWindowFamilyText, "private long _previewLastPresentedTick;");
        AssertDoesNotContain(mainWindowFamilyText, "private long _lastRendererStopTick;");
        AssertDoesNotContain(mainWindowFamilyText, "private long _rendererReinitUnsafeWindows;");
        AssertDoesNotContain(mainWindowFamilyText, "private double _previewMinPresentationIntervalMs;");
        AssertDoesNotContain(mainWindowFamilyText, "new D3D11PreviewRenderer(");
        AssertDoesNotContain(mainWindowFamilyText, "RetireSharedDeviceReferenceForReinit();");
        AssertDoesNotContain(mainWindowText, "PreviewRendererStartupPlanBuilder.ResolveExpectedIntervalMs");
        AssertDoesNotContain(mainWindowText, "private double ResolvePreviewExpectedIntervalMs()");
        AssertDoesNotContain(previewRendererText, "private long _lastRendererStopTick;");
        AssertDoesNotContain(previewRendererText, "private long _rendererReinitUnsafeWindows;");
        AssertDoesNotContain(previewRendererText, "public long RendererReinitUnsafeWindows => Interlocked.Read(ref _rendererReinitUnsafeWindows);");
        AssertDoesNotContain(previewRendererText, "private void ReplacePreviewSwapChainPanelSurface()");
        AssertDoesNotContain(mainWindowText, "private async Task<PreviewRuntimeSnapshot> GetPreviewRuntimeSnapshotAsync");
        AssertDoesNotContain(previewRendererText, "private async Task<PreviewRuntimeSnapshot> GetPreviewRuntimeSnapshotAsync");
        AssertDoesNotContain(previewRendererText, "private PreviewRuntimeSnapshot GetPreviewRuntimeSnapshot()");
        AssertDoesNotContain(mainWindowText, "private static bool IsHdrSubtype");

        return Task.CompletedTask;
    }
}
