using System.Threading.Tasks;

static partial class Program
{
    private static Task CaptureOptionBindings_LiveInController()
    {
        var mainWindowText = ReadRepoFile("Sussudio/MainWindow.xaml.cs").Replace("\r\n", "\n");
        var bindingsText = ReadRepoFile("Sussudio/MainWindow.Bindings.cs").Replace("\r\n", "\n");
        var captureOptionBindingsText = ReadRepoFile("Sussudio/MainWindow.CaptureOptionBindings.cs").Replace("\r\n", "\n");
        var propertyChangedText = ReadRepoFile("Sussudio/MainWindow.PropertyChanged.cs").Replace("\r\n", "\n");
        var controllerText = ReadRepoFile("Sussudio/Controllers/Capture/CaptureOptionBindingController.cs").Replace("\r\n", "\n");
        var captureOptionPropertyChangedText = ReadRepoFile("Sussudio/MainWindow.PropertyChangedCaptureOptions.cs").Replace("\r\n", "\n");
        var agentMapText = ReadRepoFile("docs/architecture/AGENT_MAP.md").Replace("\r\n", "\n");
        var cleanupPlanText = ReadRepoFile("docs/architecture/cleanup-plan.md").Replace("\r\n", "\n");
        var selectionBindingFamilyText = string.Join(
            "\n",
            ReadRepoFile("Sussudio/Controllers/Capture/CaptureSelectionBindingController.cs").Replace("\r\n", "\n"),
            ReadRepoFile("Sussudio/Controllers/Capture/CaptureSelectionBindingController.RecordingSelection.cs").Replace("\r\n", "\n"));
        var captureOptionBindingsWithoutVideoFormat = captureOptionBindingsText.Replace("VideoFormatComboBox.SelectionChanged +=", string.Empty);

        AssertContains(captureOptionBindingsText, "private CaptureOptionBindingController _captureOptionBindingController = null!;");
        AssertContains(captureOptionBindingsText, "private void InitializeCaptureOptionBindingController()");
        AssertContains(captureOptionBindingsText, "ResolutionComboBox = ResolutionComboBox,");
        AssertContains(captureOptionBindingsText, "VideoFormatComboBox = VideoFormatComboBox,");
        AssertContains(captureOptionBindingsText, "TrueHdrPreviewToggle = TrueHdrPreviewToggle,");
        AssertContains(captureOptionBindingsText, "ShowAllCaptureOptionsToggle = ShowAllCaptureOptionsToggle,");
        AssertContains(captureOptionBindingsText, "ApplyInitialDecoderCountSelection = ApplyInitialDecoderCountSelection,");
        AssertContains(captureOptionBindingsText, "ApplyAudioClipVisibility = ApplyAudioClipVisibility,");
        AssertContains(captureOptionBindingsText, "RefreshHdrHintText = RefreshHdrHintText,");
        AssertContains(captureOptionBindingsText, "UpdateFpsTelemetryTooltip = UpdateFpsTelemetryTooltip,");
        AssertContains(captureOptionBindingsText, "UpdateVideoContentOverlays = UpdateVideoContentOverlays,");
        AssertContains(captureOptionBindingsText, "SetHdrPassthroughEnabled = enabled => _previewRendererHostController.SetHdrPassthroughEnabled(enabled),");
        AssertContains(captureOptionBindingsText, "EnsureSplitEncodeModeSelection = EnsureSplitEncodeModeSelection");
        AssertContains(captureOptionBindingsText, "private void InitializeCaptureOptionCollections()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.InitializeCollections();");
        AssertContains(captureOptionBindingsText, "private void ApplyInitialCaptureOptionSelections()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.ApplyInitialSelections();");
        AssertContains(captureOptionBindingsText, "private void EnsureInitialCaptureOptionSelections()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.EnsureInitialSelections();");
        AssertContains(captureOptionBindingsText, "private void AttachCaptureModeSelectionBindings()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.AttachCaptureModeSelectionBindings();");
        AssertContains(captureOptionBindingsText, "private void AttachShowAllCaptureOptionsBinding()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.AttachShowAllCaptureOptionsBinding();");
        AssertContains(captureOptionBindingsText, "private void HandleCustomBitratePropertyChanged()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.HandleCustomBitratePropertyChanged();");
        AssertContains(captureOptionBindingsText, "private void HandleHdrEnabledChanged()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.HandleHdrEnabledChanged();");
        AssertContains(captureOptionBindingsText, "private void HandleTrueHdrPreviewEnabledChanged()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.HandleTrueHdrPreviewEnabledChanged();");
        AssertContains(captureOptionBindingsText, "private void HandleShowAllCaptureOptionsChanged()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.HandleShowAllCaptureOptionsChanged();");
        AssertContains(captureOptionBindingsText, "private void AttachRecordingOptionBindings()");
        AssertContains(captureOptionBindingsText, "=> _captureOptionBindingController.AttachRecordingOptionBindings();");
        AssertContains(mainWindowText, "InitializeCaptureOptionBindingController();");

        AssertContains(controllerText, "internal sealed class CaptureOptionBindingControllerContext");
        AssertContains(controllerText, "internal sealed class CaptureOptionBindingController");
        AssertDoesNotContain(controllerText, "internal sealed partial class CaptureOptionBindingController");
        AssertContains(controllerText, "private readonly CaptureOptionBindingControllerContext _context;");
        AssertContains(controllerText, "public CaptureOptionBindingController(CaptureOptionBindingControllerContext context)");
        AssertContains(controllerText, "public void InitializeCollections()");
        AssertContains(controllerText, "_context.VideoFormatComboBox.ItemsSource = _context.ViewModel.AvailableVideoFormats;");
        AssertContains(controllerText, "for (var i = 1; i <= 8; i++)");
        AssertContains(controllerText, "_context.DecoderCountComboBox.Items.Add(i);");
        AssertContains(controllerText, "public void ApplyInitialSelections()");
        AssertContains(controllerText, "_context.FormatComboBox.SelectedItem = _context.ViewModel.SelectedRecordingFormat;");
        AssertContains(controllerText, "_context.CustomBitrateNumberBox.Value = _context.ViewModel.CustomBitrateMbps;");
        AssertContains(controllerText, "_context.ShowAllCaptureOptionsToggle.IsChecked = _context.ViewModel.ShowAllCaptureOptions;");
        AssertContains(controllerText, "_context.TrueHdrPreviewToggle.IsChecked = _context.ViewModel.IsTrueHdrPreviewEnabled;");
        AssertContains(controllerText, "_context.ApplyInitialDecoderCountSelection();");
        AssertContains(controllerText, "_context.ApplyBitrateVisibility();");
        AssertContains(controllerText, "_context.ApplyHdrToggleEnabledState();");
        AssertContains(controllerText, "public void EnsureInitialSelections()");
        AssertContains(controllerText, "_context.EnsureSplitEncodeModeSelection();");
        AssertContains(controllerText, "_context.UpdateDecoderCountVisibility();");
        AssertContains(controllerText, "public void AttachCaptureModeSelectionBindings()");
        AssertContains(controllerText, "_context.ResolutionComboBox.SelectionChanged +=");
        AssertContains(controllerText, "_context.FrameRateComboBox.SelectionChanged +=");
        AssertContains(controllerText, "!string.Equals(resolution.Value, _context.ViewModel.SelectedResolution, StringComparison.OrdinalIgnoreCase)");
        AssertContains(controllerText, "if (CaptureComboBoxSelectionNormalizer.IsAutoFrameRateOption(frameRate))");
        AssertContains(controllerText, "if (!_context.ViewModel.IsAutoFrameRateSelected)");
        AssertContains(controllerText, "else if (!CaptureComboBoxSelectionNormalizer.IsFrameRateMatch(frameRate.Value, _context.ViewModel.SelectedFrameRate))");
        AssertContains(controllerText, "public void AttachRecordingOptionBindings()");
        AssertContains(controllerText, "AttachStringSelection(_context.FormatComboBox, value => _context.ViewModel.SelectedRecordingFormat = value);");
        AssertContains(controllerText, "AttachStringSelection(_context.QualityComboBox, value => _context.ViewModel.SelectedQuality = value);");
        AssertContains(controllerText, "AttachStringSelection(_context.PresetComboBox, value => _context.ViewModel.SelectedPreset = value);");
        AssertContains(controllerText, "AttachStringSelection(_context.SplitEncodeComboBox, value => _context.ViewModel.SelectedSplitEncodeMode = value);");
        AssertContains(controllerText, "_context.VideoFormatComboBox.SelectionChanged +=");
        AssertContains(controllerText, "_context.CustomBitrateNumberBox.ValueChanged +=");
        AssertContains(controllerText, "_context.HdrToggle.Click +=");
        AssertContains(controllerText, "_context.TrueHdrPreviewToggle.Click +=");
        AssertContains(controllerText, "_context.ShowAllCaptureOptionsToggle.Click +=");
        AssertContains(controllerText, "public bool TryHandlePropertyChanged(string propertyName)");
        AssertContains(controllerText, "case nameof(MainViewModel.AudioClipping):");
        AssertContains(controllerText, "_context.ApplyAudioClipVisibility();");
        AssertContains(controllerText, "case nameof(MainViewModel.IsHdrAvailable):");
        AssertContains(controllerText, "case nameof(MainViewModel.SourceIsHdr):");
        AssertContains(controllerText, "_context.ApplyHdrToggleEnabledState();");
        AssertContains(controllerText, "case nameof(MainViewModel.IsHdrEnabled):");
        AssertContains(controllerText, "HandleHdrEnabledChanged();");
        AssertContains(controllerText, "case nameof(MainViewModel.IsTrueHdrPreviewEnabled):");
        AssertContains(controllerText, "HandleTrueHdrPreviewEnabledChanged();");
        AssertContains(controllerText, "case nameof(MainViewModel.HdrResolutionSupportHint):");
        AssertContains(controllerText, "case nameof(MainViewModel.HdrReadinessReason):");
        AssertContains(controllerText, "case nameof(MainViewModel.HdrRuntimeState):");
        AssertContains(controllerText, "_context.RefreshHdrHintText();");
        AssertContains(controllerText, "case nameof(MainViewModel.SourceTelemetrySummaryText):");
        AssertContains(controllerText, "case nameof(MainViewModel.SourceTargetSummaryText):");
        AssertContains(controllerText, "_context.UpdateFpsTelemetryTooltip();");
        AssertContains(controllerText, "case nameof(MainViewModel.SourceWidth):");
        AssertContains(controllerText, "case nameof(MainViewModel.SourceHeight):");
        AssertContains(controllerText, "_context.UpdateVideoContentOverlays();");
        AssertContains(controllerText, "case nameof(MainViewModel.IsCustomBitrateVisible):");
        AssertContains(controllerText, "_context.ApplyBitrateVisibility();");
        AssertContains(controllerText, "case nameof(MainViewModel.CustomBitrateMbps):");
        AssertContains(controllerText, "case nameof(MainViewModel.ShowAllCaptureOptions):");
        AssertContains(controllerText, "public void HandleCustomBitratePropertyChanged()");
        AssertContains(controllerText, "public void HandleHdrEnabledChanged()");
        AssertContains(controllerText, "public void HandleTrueHdrPreviewEnabledChanged()");
        AssertContains(controllerText, "public void HandleShowAllCaptureOptionsChanged()");
        AssertContains(controllerText, "private void AttachHdrToggleBindings()");
        AssertContains(controllerText, "private static void AttachStringSelection(ComboBox comboBox, Action<string> setVmProp)");
        AssertDoesNotContain(controllerText, "private static bool IsFrameRateMatch(double a, double b, double tolerance = 0.01)");
        AssertDoesNotContain(controllerText, "private static bool IsAutoFrameRateOption(FrameRateOption option)");

        AssertContains(bindingsText, "InitializeCaptureOptionCollections();");
        AssertContains(bindingsText, "ApplyInitialCaptureOptionSelections();");
        AssertContains(bindingsText, "EnsureInitialCaptureOptionSelections();");
        AssertContains(bindingsText, "AttachCaptureModeSelectionBindings();");
        AssertContains(bindingsText, "AttachRecordingOptionBindings();");
        AssertContains(bindingsText, "AttachShowAllCaptureOptionsBinding();");
        AssertOccursBefore(bindingsText, "InitializeCaptureOptionCollections();", "ApplyInitialCaptureOptionSelections();");
        AssertOccursBefore(bindingsText, "ApplyInitialCaptureOptionSelections();", "AttachRecordingOptionBindings();");
        AssertOccursBefore(bindingsText, "EnsureInitialCaptureOptionSelections();", "AttachCaptureModeSelectionBindings();");
        AssertOccursBefore(bindingsText, "AttachCaptureModeSelectionBindings();", "AttachRecordingOptionBindings();");
        AssertOccursBefore(bindingsText, "AttachAudioInputToggleBindings();", "AttachShowAllCaptureOptionsBinding();");
        AssertOccursBefore(bindingsText, "AttachShowAllCaptureOptionsBinding();", "AttachFlashbackSettingsBindings();");
        AssertDoesNotContain(selectionBindingFamilyText, "public void AttachRecordingStringSelectionBindings()");
        AssertDoesNotContain(selectionBindingFamilyText, "AttachStringSelection(_context.FormatComboBox, value => _context.ViewModel.SelectedRecordingFormat = value);");
        AssertDoesNotContain(selectionBindingFamilyText, "private static void AttachStringSelection(ComboBox comboBox, Action<string> setVmProp)");

        AssertContains(agentMapText, "`Sussudio/Controllers/Capture/CaptureOptionBindingController.cs` owns the capture");
        AssertContains(agentMapText, "option binding adapter in one file: XAML/view-model adapter context");
        AssertContains(agentMapText, "initialization, resolution/frame-rate selection, recording option event");
        AssertContains(agentMapText, "bindings, capture-option/source-signal property-change routing, HDR/");
        AssertContains(agentMapText, "callbacks for option affordances, telemetry tooltips, and source overlay");
        AssertDoesNotContain(agentMapText, "CaptureOptionBindingController.Context.cs");
        AssertContains(cleanupPlanText, "`Sussudio/Controllers/Capture/CaptureOptionBindingController.cs`. The single");
        AssertContains(cleanupPlanText, "controller owns the full capture-option binding adapter: XAML/view-model");
        AssertContains(cleanupPlanText, "context, video-format and initial decoder projection, initial selection");
        AssertContains(cleanupPlanText, "projection, resolution/frame-rate selection handlers, recording option event");
        AssertContains(cleanupPlanText, "bitrate, capture-option/source-signal property-change routing, custom-bitrate");
        AssertContains(cleanupPlanText, "delegates presentation affordances, telemetry tooltips, and source overlay");
        AssertDoesNotContain(cleanupPlanText, "CaptureOptionBindingController.Context.cs");

        AssertDoesNotContain(captureOptionBindingsText, "VideoFormatComboBox.ItemsSource = ViewModel.AvailableVideoFormats;");
        AssertDoesNotContain(captureOptionBindingsText, "ResolutionComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "FrameRateComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "ViewModel.SelectedFrameRate =");
        AssertDoesNotContain(captureOptionBindingsWithoutVideoFormat, "FormatComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "VideoFormatComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "CustomBitrateNumberBox.ValueChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "HdrToggle.Click +=");
        AssertDoesNotContain(captureOptionBindingsText, "TrueHdrPreviewToggle.Click +=");
        AssertDoesNotContain(captureOptionBindingsText, "ViewModel.SelectedRecordingFormat =");
        AssertDoesNotContain(captureOptionBindingsText, "QualityComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "PresetComboBox.SelectionChanged +=");
        AssertDoesNotContain(captureOptionBindingsText, "SplitEncodeComboBox.SelectionChanged +=");
        AssertDoesNotContain(propertyChangedText, "CustomBitrateNumberBox.Value");
        AssertDoesNotContain(propertyChangedText, "Math.Abs(CustomBitrateNumberBox.Value - ViewModel.CustomBitrateMbps) > 0.01");
        AssertContains(propertyChangedText, "TryHandleCaptureOptionPropertyChanged(propertyName)");
        AssertContains(captureOptionPropertyChangedText, "=> _captureOptionBindingController.TryHandlePropertyChanged(propertyName);");
        AssertDoesNotContain(captureOptionPropertyChangedText, "HandleCustomBitratePropertyChanged();");
        AssertDoesNotContain(captureOptionPropertyChangedText, "HandleHdrEnabledChanged();");
        AssertDoesNotContain(captureOptionPropertyChangedText, "HandleTrueHdrPreviewEnabledChanged();");
        AssertDoesNotContain(captureOptionPropertyChangedText, "HandleShowAllCaptureOptionsChanged();");
        AssertDoesNotContain(captureOptionPropertyChangedText, "HdrToggle.IsChecked = ViewModel.IsHdrEnabled;");
        AssertDoesNotContain(captureOptionPropertyChangedText, "TrueHdrPreviewToggle.IsChecked = ViewModel.IsTrueHdrPreviewEnabled;");
        AssertDoesNotContain(captureOptionPropertyChangedText, "_previewRendererHostController.SetHdrPassthroughEnabled(ViewModel.IsTrueHdrPreviewEnabled);");
        AssertDoesNotContain(captureOptionPropertyChangedText, "ShowAllCaptureOptionsToggle.IsChecked = ViewModel.ShowAllCaptureOptions;");
        AssertDoesNotContain(bindingsText, "ResolutionComboBox.SelectionChanged +=");
        AssertDoesNotContain(bindingsText, "FrameRateComboBox.SelectionChanged +=");
        AssertDoesNotContain(bindingsText, "FormatComboBox.SelectionChanged +=");
        AssertDoesNotContain(bindingsText, "CustomBitrateNumberBox.ValueChanged +=");
        AssertDoesNotContain(bindingsText, "HdrToggle.Click +=");
        AssertDoesNotContain(bindingsText, "ShowAllCaptureOptionsToggle.Click +=");
        AssertDoesNotContain(bindingsText, "ShowAllCaptureOptionsToggle.IsChecked = ViewModel.ShowAllCaptureOptions;");

        return Task.CompletedTask;
    }
}
