static partial class Program
{
    private static void AssertDiagnosticsAlertEventOwnership(AutomationDiagnosticsHubSourceFamily diagnostics)
    {
        AssertContains(diagnostics.AlertsText, "private void UpdateAlerts(AutomationSnapshot snapshot, FlashbackRecordingRecentCounters flashbackRecordingRecent)");
        AssertDoesNotContain(diagnostics.AlertsText, "private void AddEventThrottled(");
        AssertDoesNotContain(diagnostics.AlertsText, "public IReadOnlyList<DiagnosticsEvent> GetRecentEvents");
        AssertContains(diagnostics.EventsText, "private void ObserveFlashbackExportCompletion(AutomationSnapshot snapshot)");
        AssertContains(diagnostics.EventsText, "private void AddEventThrottled(");
        AssertContains(diagnostics.EventsText, "private void SetAlertState(");
        AssertContains(diagnostics.EventsText, "public IReadOnlyList<DiagnosticsEvent> GetRecentEvents");
        AssertContains(diagnostics.AlertsText, "UpdateSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsText, "private void UpdateSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsText, "UpdatePreviewSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsText, "UpdateAudioSignalAlerts(snapshot);");
        AssertContains(diagnostics.SignalAlertsText, "UpdateRecordingGrowthAlerts(snapshot);");
        AssertContains(diagnostics.SignalAlertsText, "UpdateCaptureSignalAlerts(");
        AssertDoesNotContain(diagnostics.SignalAlertsText, "\"preview-blank\"");
        AssertDoesNotContain(diagnostics.SignalAlertsText, "\"capture-cadence-drop\"");
        AssertDoesNotContain(diagnostics.SignalAlertsText, "\"audio-muted-suspect\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "private void UpdatePreviewSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-blank\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-stall\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-startup-timeout\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-startup-failed\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-cadence-slow\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-display-low-1pct\"");
        AssertContains(diagnostics.SignalAlertsCaptureText, "private void UpdateCaptureSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsCaptureText, "\"capture-cadence-drop\"");
        AssertContains(diagnostics.SignalAlertsCaptureText, "\"capture-cadence-low-1pct\"");
        AssertContains(diagnostics.SignalAlertsAudioRecordingText, "private void UpdateAudioSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsAudioRecordingText, "\"audio-muted-suspect\"");
        AssertContains(diagnostics.SignalAlertsAudioRecordingText, "private void UpdateRecordingGrowthAlerts(");
        AssertContains(diagnostics.SignalAlertsAudioRecordingText, "\"recording-not-growing\"");
        AssertDoesNotContain(diagnostics.SignalAlertsPreviewText, "\"capture-cadence-drop\"");
        AssertDoesNotContain(diagnostics.SignalAlertsCaptureText, "\"preview-blank\"");
        AssertDoesNotContain(diagnostics.SignalAlertsAudioRecordingText, "\"preview-blank\"");
        AssertDoesNotContain(diagnostics.AlertsText, "\"preview-blank\"");
        AssertContains(diagnostics.AlertsText, "var nowUnixMs = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();");
        AssertContains(diagnostics.AlertsText, "UpdateFlashbackRecordingAlerts(snapshot, flashbackRecordingRecent);");
        AssertContains(diagnostics.AlertsText, "UpdateFlashbackPlaybackAlerts(snapshot, nowUnixMs);");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "private void UpdateFlashbackRecordingAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "UpdateFlashbackExportAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "UpdateFlashbackStorageAlerts(snapshot);");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "UpdateFlashbackEncoderAlerts(snapshot);");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "UpdateFlashbackRecordingDegradationAlert(");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "private void UpdateFlashbackExportAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "\"flashback-export-stalled\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "\"flashback-export-rotation-gap\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "private void UpdateFlashbackStorageAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "\"flashback-temp-cache-pressure\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "private void UpdateFlashbackEncoderAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "\"flashback-encoding-failed\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "private void UpdateFlashbackRecordingDegradationAlert(");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "\"flashback-recording-degraded\"");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "private void UpdateFlashbackPlaybackAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "UpdateFlashbackPlaybackCommandAlerts(snapshot, nowUnixMs);");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "UpdateFlashbackPlaybackPerformanceAlerts(snapshot);");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "private void UpdateFlashbackPlaybackCommandAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "\"flashback-playback-command-stalled\"");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "private void UpdateFlashbackPlaybackPerformanceAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "UpdateFlashbackPlaybackCadenceAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "UpdateFlashbackPlaybackAudioAlerts(snapshot, playbackActive);");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "UpdateFlashbackPlaybackSubmitFailureAlert(snapshot);");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsCadenceText, "private void UpdateFlashbackPlaybackCadenceAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsCadenceText, "\"flashback-playback-slow\"");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "private void UpdateFlashbackPlaybackAudioAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "\"flashback-playback-audio-master-fallback\"");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "private void UpdateFlashbackPlaybackSubmitFailureAlert(");
        AssertContains(diagnostics.FlashbackPlaybackAlertsText, "\"flashback-playback-submit-failures\"");
        AssertDoesNotContain(diagnostics.FlashbackPlaybackAlertsText, "\"flashback-playback-slow\"");
        AssertDoesNotContain(diagnostics.AlertsText, "\"flashback-export-stalled\"");
        AssertDoesNotContain(diagnostics.HubText, "private void UpdateAlerts(AutomationSnapshot snapshot, FlashbackRecordingRecentCounters flashbackRecordingRecent)");
    }
}
