static partial class Program
{
    private static void AssertDiagnosticsAlertEventOwnership(AutomationDiagnosticsHubSourceFamily diagnostics)
    {
        AssertContains(diagnostics.AlertsText, "private void UpdateAlerts(AutomationSnapshot snapshot, FlashbackRecordingRecentCounters flashbackRecordingRecent)");
        AssertDoesNotContain(diagnostics.AlertsText, "private void AddEventThrottled(");
        AssertDoesNotContain(diagnostics.AlertsText, "public IReadOnlyList<DiagnosticsEvent> GetRecentEvents");
        AssertContains(diagnostics.EventsText, "private void ObserveFlashbackExportCompletion(AutomationSnapshot snapshot)");
        AssertContains(diagnostics.EventsText, "private void AddEventThrottled(");
        AssertContains(diagnostics.EventsText, "private void SetAlertState(");
        AssertContains(diagnostics.EventsText, "public IReadOnlyList<DiagnosticsEvent> GetRecentEvents");
        AssertContains(diagnostics.AlertsText, "UpdateSignalAlerts(");
        AssertContains(diagnostics.AlertsText, "private void UpdateSignalAlerts(");
        AssertContains(diagnostics.AlertsText, "UpdatePreviewSignalAlerts(");
        AssertContains(diagnostics.AlertsText, "UpdateAudioSignalAlerts(snapshot);");
        AssertContains(diagnostics.AlertsText, "UpdateRecordingGrowthAlerts(snapshot);");
        AssertContains(diagnostics.AlertsText, "UpdateCaptureSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsPreviewText, "private void UpdatePreviewSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-blank\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-stall\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-startup-timeout\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-startup-failed\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-cadence-slow\"");
        AssertContains(diagnostics.SignalAlertsPreviewText, "\"preview-display-low-1pct\"");
        AssertContains(diagnostics.SignalAlertsCaptureText, "private void UpdateCaptureSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsCaptureText, "\"capture-cadence-drop\"");
        AssertContains(diagnostics.SignalAlertsCaptureText, "\"capture-cadence-low-1pct\"");
        AssertContains(diagnostics.SignalAlertsAudioRecordingText, "private void UpdateAudioSignalAlerts(");
        AssertContains(diagnostics.SignalAlertsAudioRecordingText, "\"audio-muted-suspect\"");
        AssertContains(diagnostics.SignalAlertsAudioRecordingText, "private void UpdateRecordingGrowthAlerts(");
        AssertContains(diagnostics.SignalAlertsAudioRecordingText, "\"recording-not-growing\"");
        AssertDoesNotContain(diagnostics.SignalAlertsPreviewText, "\"capture-cadence-drop\"");
        AssertDoesNotContain(diagnostics.SignalAlertsCaptureText, "\"preview-blank\"");
        AssertDoesNotContain(diagnostics.SignalAlertsAudioRecordingText, "\"preview-blank\"");
        AssertDoesNotContain(diagnostics.AlertsText, "\"preview-blank\"");
        AssertDoesNotContain(diagnostics.AlertsText, "\"capture-cadence-drop\"");
        AssertDoesNotContain(diagnostics.AlertsText, "\"audio-muted-suspect\"");
        AssertContains(diagnostics.AlertsText, "var nowUnixMs = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();");
        AssertContains(diagnostics.AlertsText, "UpdateFlashbackRecordingAlerts(snapshot, flashbackRecordingRecent);");
        AssertContains(diagnostics.AlertsText, "UpdateFlashbackPlaybackAlerts(snapshot, nowUnixMs);");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "private void UpdateFlashbackRecordingAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "UpdateFlashbackExportAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "UpdateFlashbackStorageAlerts(snapshot);");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "UpdateFlashbackEncoderAlerts(snapshot);");
        AssertContains(diagnostics.FlashbackRecordingAlertsText, "UpdateFlashbackRecordingDegradationAlert(");
        AssertDoesNotContain(diagnostics.FlashbackRecordingAlertsText, "\"flashback-export-stalled\"");
        AssertDoesNotContain(diagnostics.FlashbackRecordingAlertsText, "\"flashback-temp-cache-pressure\"");
        AssertDoesNotContain(diagnostics.FlashbackRecordingAlertsText, "\"flashback-encoding-failed\"");
        AssertDoesNotContain(diagnostics.FlashbackRecordingAlertsText, "\"flashback-recording-degraded\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsExportText, "private void UpdateFlashbackExportAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsExportText, "\"flashback-export-stalled\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsExportText, "\"flashback-export-rotation-gap\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsStorageText, "private void UpdateFlashbackStorageAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsStorageText, "\"flashback-temp-cache-pressure\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsEncoderText, "private void UpdateFlashbackEncoderAlerts(");
        AssertContains(diagnostics.FlashbackRecordingAlertsEncoderText, "\"flashback-encoding-failed\"");
        AssertContains(diagnostics.FlashbackRecordingAlertsDegradationText, "private void UpdateFlashbackRecordingDegradationAlert(");
        AssertContains(diagnostics.FlashbackRecordingAlertsDegradationText, "\"flashback-recording-degraded\"");
        AssertDoesNotContain(diagnostics.FlashbackRecordingAlertsExportText, "\"flashback-temp-cache-pressure\"");
        AssertDoesNotContain(diagnostics.FlashbackRecordingAlertsStorageText, "\"flashback-export-stalled\"");
        AssertDoesNotContain(diagnostics.FlashbackRecordingAlertsEncoderText, "\"flashback-recording-degraded\"");
        AssertContains(diagnostics.AlertsText, "private void UpdateFlashbackPlaybackAlerts(");
        AssertContains(diagnostics.AlertsText, "UpdateFlashbackPlaybackCommandAlerts(snapshot, nowUnixMs);");
        AssertContains(diagnostics.AlertsText, "UpdateFlashbackPlaybackPerformanceAlerts(snapshot);");
        AssertDoesNotContain(diagnostics.AlertsText, "\"flashback-playback-command-stalled\"");
        AssertDoesNotContain(diagnostics.AlertsText, "\"flashback-playback-audio-master-fallback\"");
        AssertDoesNotContain(diagnostics.AlertsText, "\"flashback-playback-submit-failures\"");
        AssertContains(diagnostics.FlashbackPlaybackAlertsCommandsText, "private void UpdateFlashbackPlaybackCommandAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackAlertsCommandsText, "\"flashback-playback-command-stalled\"");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsText, "private void UpdateFlashbackPlaybackPerformanceAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsText, "UpdateFlashbackPlaybackCadenceAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsText, "UpdateFlashbackPlaybackAudioAlerts(snapshot, playbackActive);");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsText, "UpdateFlashbackPlaybackSubmitFailureAlert(snapshot);");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsCadenceText, "private void UpdateFlashbackPlaybackCadenceAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsCadenceText, "\"flashback-playback-slow\"");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsAudioText, "private void UpdateFlashbackPlaybackAudioAlerts(");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsAudioText, "\"flashback-playback-audio-master-fallback\"");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsAudioText, "\"flashback-playback-audio-queue-backlog\"");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsSubmitText, "private void UpdateFlashbackPlaybackSubmitFailureAlert(");
        AssertContains(diagnostics.FlashbackPlaybackPerformanceAlertsSubmitText, "\"flashback-playback-submit-failures\"");
        AssertDoesNotContain(diagnostics.AlertsText, "\"flashback-playback-slow\"");
        AssertDoesNotContain(diagnostics.FlashbackPlaybackPerformanceAlertsCadenceText, "\"flashback-playback-audio-master-fallback\"");
        AssertDoesNotContain(diagnostics.FlashbackPlaybackPerformanceAlertsAudioText, "\"flashback-playback-submit-failures\"");
        AssertDoesNotContain(diagnostics.AlertsText, "\"flashback-export-stalled\"");
        AssertDoesNotContain(diagnostics.HubText, "private void UpdateAlerts(AutomationSnapshot snapshot, FlashbackRecordingRecentCounters flashbackRecordingRecent)");
    }
}
