// Flashback-specific overload assertions for the recording queue policy harness.
static partial class Program
{
    private static void AssertFlashbackRecordingQueueOverloadPolicy(string flashbackSource)
    {
        AssertDoesNotContain(flashbackSource, "QueueBackpressureTimeoutMs");
        AssertDoesNotContain(flashbackSource, "WaitForBackpressureRetryCancellation");
        AssertDoesNotContain(flashbackSource, "FLASHBACK_SINK_VIDEO_BACKPRESSURE_DROP");
        AssertDoesNotContain(flashbackSource, "FLASHBACK_SINK_GPU_BACKPRESSURE_DROP");
        AssertContains(flashbackSource, "var p010FrameSize = MfSourceReaderVideoCapture.GetFrameSizeBytes(_width, _height, isP010: true)");
        AssertContains(flashbackSource, "VideoFramePacket.Frame(buffer, expectedSize, enqueueTick, isP010)");
        AssertContains(flashbackSource, "MfSourceReaderVideoCapture.GetFrameSizeBytes(w, h, packet.IsP010)");
        AssertContains(flashbackSource, "lease.PixelFormat == PooledVideoPixelFormat.P010");
        AssertContains(flashbackSource, "FLASHBACK_SINK_VIDEO_OVERLOAD");
        AssertContains(flashbackSource, "FLASHBACK_SINK_GPU_OVERLOAD");
        AssertContains(flashbackSource, "_onFatalError?.Invoke");
        AssertDoesNotContain(flashbackSource, "catch { /* Callback must not mask the original error */ }");
        AssertContains(flashbackSource, "Logger.Log($\"FLASHBACK_SINK_FATAL_CALLBACK_FAIL type={callbackEx.GetType().Name} msg={callbackEx.Message}\");");
        AssertContains(flashbackSource, "private void OnVideoFrameEncoded()\n    {\n        if (_disposed)\n        {\n            return;\n        }");
        AssertContains(flashbackSource, "if (!_disposed && Volatile.Read(ref _recordingActive) == 1)");
        AssertContains(flashbackSource, "public bool EncodingFailed");
        AssertContains(flashbackSource, "public string? EncodingFailureMessage");
        AssertContains(flashbackSource, "public bool CanBeginRecording");
        AssertContains(flashbackSource, "public bool IsRecordingActive");
        AssertContains(flashbackSource, "Volatile.Read(ref _recordingActive) == 0");
        AssertContains(flashbackSource, "!_bufferManager.IsSessionPreservedForRecovery");
        AssertContains(flashbackSource, "Cannot begin recording: flashback recording is already active.");
        AssertContains(flashbackSource, "Cannot begin recording: flashback session is preserved for recovery.");
        AssertOccursBefore(flashbackSource, "Cannot begin recording: flashback recording is already active.", "_bufferManager.PauseEviction();");
        AssertOccursBefore(flashbackSource, "Cannot begin recording: flashback session is preserved for recovery.", "_bufferManager.PauseEviction();");
        AssertOccursBefore(flashbackSource, "_bufferManager.PauseEviction();", "Volatile.Write(ref _recordingActive, 1);");
        AssertContains(flashbackSource, "public bool IsForceRotateActive");
        AssertContains(flashbackSource, "public bool IsForceRotateRequested");
        AssertContains(flashbackSource, "public bool IsForceRotateDraining");
        AssertContains(flashbackSource, "WaitForForceRotateIdle");
        AssertContains(flashbackSource, "CompletePendingForceRotateWithEmptyResult");
        AssertContains(flashbackSource, "ForceRotateRequest? supersededRequest;");
        AssertContains(flashbackSource, "supersededRequest = _forceRotateRequest;");
        AssertContains(flashbackSource, "FLASHBACK_SINK_FORCE_ROTATE_SUPERSEDED");
        AssertContains(flashbackSource, "supersededRequest.TryCancel();");
        AssertContains(flashbackSource, "if (!RotateSegment(currentPts))\n                {\n                    localRequest.CompleteEmpty();\n                    return true;\n                }");
        AssertContains(flashbackSource, "private bool RotateSegment(TimeSpan currentPts)");
        AssertContains(flashbackSource, "return true;\n        }\n        catch (Exception ex)");
        AssertContains(flashbackSource, "Logger.Log($\"FLASHBACK_SINK_ROTATE_FAIL type={ex.GetType().Name} msg={ex.Message}\");\n            return false;");
        AssertContains(flashbackSource, "TryCancelForceRotate(request)");
        AssertContains(flashbackSource, "ReferenceEquals(_forceRotateRequest, request)");
        AssertContains(flashbackSource, "cancelled={cancelled}");
        AssertContains(flashbackSource, "_forceRotateRequested = false;");
        AssertContains(flashbackSource, "Volatile.Write(ref _forceRotateDraining, false);");
        AssertContains(flashbackSource, "CancelEncodingCts(\"stop_timeout\");\n                CompletePendingForceRotateWithEmptyResult();\n                Logger.Log(\"FLASHBACK_SINK_STOP_DRAIN_TIMEOUT\");");
        AssertContains(flashbackSource, "Cannot begin recording: flashback export rotation is still draining.");
        AssertContains(flashbackSource, "if (_ownsBufferManager)");
        AssertOccursBefore(flashbackSource, "if (_ownsBufferManager)\n        {\n            _bufferManager.PurgeAllSegments();", "_encoder.Dispose();");
        AssertContains(flashbackSource, "CancelRecordingStartRollback");
        AssertContains(flashbackSource, "var wasRecording = Interlocked.Exchange(ref _recordingActive, 0) != 0");
        AssertContains(flashbackSource, "if (!wasRecording)\n        {\n            const string message = \"Flashback recording was not active.\";");
        AssertContains(flashbackSource, "FLASHBACK_RECORDING_END_REJECTED");
        AssertContains(flashbackSource, "finally");
        AssertContains(flashbackSource, "ResumeEvictionBestEffort(_bufferManager, \"recording_end\")");
        AssertContains(flashbackSource, "ResumeEvictionBestEffort(_bufferManager, \"recording_start_rollback\")");
        AssertContains(flashbackSource, "if (Interlocked.Exchange(ref _recordingActive, 0) != 0)\n        {\n            ResumeEvictionBestEffort(_bufferManager, \"dispose\");\n        }");
        AssertContains(flashbackSource, "_gpuEncodingEnabled = false;\n        _audioEnabled = false;\n        _microphoneEnabled = false;\n        _sessionContext = null;\n        _width = 0;\n        _height = 0;\n        _tsFilePath = null;\n        _recordingOutputPath = string.Empty;\n        _segmentStartPts = TimeSpan.Zero;\n        _segmentDuration = TimeSpan.Zero;\n        _ptsBaseOffset = TimeSpan.Zero;\n        Interlocked.Exchange(ref _segmentStartBytes, 0);");
        AssertContains(flashbackSource, "FLASHBACK_SINK_EVICTION_RESUME_WARN");
        AssertContains(flashbackSource, "if (LastRecordingEndPts < LastRecordingStartPts)\n                {\n                    LastRecordingEndPts = _bufferManager.LatestPts;\n                    if (LastRecordingEndPts < LastRecordingStartPts)\n                    {\n                        LastRecordingEndPts = LastRecordingStartPts;\n                    }\n                }");
        AssertContains(flashbackSource, "Cannot begin recording: flashback encoder is not running.");
        AssertContains(flashbackSource, "public int VideoQueueMaxDepth");
        AssertContains(flashbackSource, "public long VideoFramesSubmittedToEncoder");
        AssertContains(flashbackSource, "public long VideoEncoderPacketsWritten");
        AssertContains(flashbackSource, "public long VideoSequenceGaps");
        AssertContains(flashbackSource, "public long VideoQueueOldestFrameAgeMs");
        AssertContains(flashbackSource, "public (int SampleCount, double AverageMs, double P95Ms, double P99Ms, double MaxMs) VideoQueueLatencyMetrics");
        AssertContains(flashbackSource, "public double VideoQueueLatencyP95Ms");
        AssertContains(flashbackSource, "public double VideoQueueLatencyP99Ms");
        AssertContains(flashbackSource, "public long VideoBackpressureWaitMs");
        AssertContains(flashbackSource, "public long VideoBackpressureEvents");
        AssertDoesNotContain(flashbackSource, "_videoLatencyTracker.RecordBackpressure(backpressureStartTick");
        AssertContains(flashbackSource, "_videoLatencyTracker.TrackEnqueueUnderLock(packet.EnqueueTick)");
        AssertContains(flashbackSource, "_videoLatencyTracker.TrackDequeueUnderLock(packet.EnqueueTick)");
        AssertContains(flashbackSource, "_videoLatencyTracker.RecordPacketDequeued(packet.EnqueueTick, packet.SequenceNumber)");
        AssertContains(flashbackSource, "public int GpuQueueMaxDepth");
        AssertContains(flashbackSource, "IRawVideoFrameTryEncoder");
        AssertContains(flashbackSource, "IGpuVideoFrameTryEncoder");
        AssertContains(flashbackSource, "public bool TryEnqueueRawVideoFrame");
        AssertContains(flashbackSource, "public bool TryEnqueueGpuVideoFrame");
        AssertContains(flashbackSource, "VideoEnqueueResult.Rejected");
        AssertContains(flashbackSource, "TryEnqueueGpuPacket");
        AssertContains(flashbackSource, "Volatile.Read(ref _forceRotateDraining)");
        AssertContains(flashbackSource, "Volatile.Read(ref _encodingFailure) != null");
        AssertContains(flashbackSource, "var maxFrameSize = Math.Max(nv12FrameSize, p010FrameSize);");
        AssertContains(flashbackSource, "var matchesConfiguredFrameSize =\n            expectedSize == nv12FrameSize ||\n            (p010FrameSize > 0 && expectedSize == p010FrameSize);");
        AssertContains(flashbackSource, "if (maxFrameSize <= 0 || !matchesConfiguredFrameSize)");
        AssertContains(flashbackSource, "FLASHBACK_SINK_VIDEO_FRAME_INVALID_SIZE expected={expectedSize} max={maxFrameSize}");
        AssertContains(flashbackSource, "if (expectedSize <= 0)\n        {\n            Logger.Log($\"FLASHBACK_SINK_VIDEO_FRAME_INVALID_SIZE expected={expectedSize} actual={frame.Width}x{frame.Height}\");\n            frame.Dispose();\n            return false;\n        }");
        AssertContains(flashbackSource, "if (subresourceIndex < 0)\n        {\n            TrackGpuQueueRejected(\"invalid_subresource\");\n            Logger.Log($\"FLASHBACK_SINK_GPU_FRAME_INVALID_SUBRESOURCE subresource={subresourceIndex}\");\n            return false;\n        }");
        AssertOccursBefore(flashbackSource, "FLASHBACK_SINK_GPU_FRAME_INVALID_SUBRESOURCE", "Marshal.AddRef(d3d11Texture2D);");
    }
}
