using System;
using System.Collections.Generic;

namespace Sussudio.Tests;

public partial class SnapshotModelsTests
{
    private static SnapshotPropertySpec[] CaptureHealthSnapshotPropertySpecs(Type detailType)
    {
        return new SnapshotPropertySpec[]
        {
            new("FlashbackOutputBytes", typeof(long)),
            NullableString("FlashbackFilePath"),
            new("FlashbackEncodedFrames", typeof(long)),
            new("FlashbackDroppedFrames", typeof(long)),
            new("FlashbackGpuEncoding", typeof(bool)),
            new("FlashbackBackendSettingsStale", typeof(bool)),
            NonNullString("FlashbackBackendSettingsStaleReason"),
            NonNullString("FlashbackBackendActiveFormat"),
            NonNullString("FlashbackBackendRequestedFormat"),
            NonNullString("FlashbackBackendActivePreset"),
            NonNullString("FlashbackBackendRequestedPreset"),
            NullableString("EncoderCodecName"),
            new("EncoderTargetBitRate", typeof(uint)),
            new("EncoderWidth", typeof(int)),
            new("EncoderHeight", typeof(int)),
            new("EncoderFrameRate", typeof(double)),
            new("EncoderFrameRateNumerator", typeof(int?)),
            new("EncoderFrameRateDenominator", typeof(int?)),
            new("FlashbackVideoQueueDepth", typeof(int)),
            new("FlashbackAudioQueueDepth", typeof(int)),
            new("FlashbackAudioQueueCapacity", typeof(int)),
            NonNullString("FlashbackPlaybackState"),
            new("FlashbackPlaybackPositionMs", typeof(long)),
            NonNullString("FlashbackDecoderHwAccel"),
            new("FlashbackPlaybackFrameCount", typeof(long)),
            new("FlashbackPlaybackLateFrames", typeof(long)),
            new("FlashbackPlaybackDroppedFrames", typeof(long)),
            new("FlashbackPlaybackAudioMasterDelayDoubles", typeof(long)),
            new("FlashbackPlaybackAudioMasterDelayShrinks", typeof(long)),
            new("FlashbackPlaybackAudioMasterFallbacks", typeof(long)),
            new("FlashbackPlaybackAudioMasterUnavailableFallbacks", typeof(long)),
            new("FlashbackPlaybackAudioMasterStaleFallbacks", typeof(long)),
            new("FlashbackPlaybackAudioMasterDriftOutlierFallbacks", typeof(long)),
            NonNullString("FlashbackPlaybackAudioMasterLastFallbackReason"),
            new("FlashbackPlaybackAudioMasterLastFallbackDriftMs", typeof(double)),
            new("FlashbackPlaybackAudioMasterLastFallbackClockAgeMs", typeof(double)),
            new("FlashbackPlaybackSegmentSwitches", typeof(long)),
            new("FlashbackPlaybackFmp4Reopens", typeof(long)),
            new("FlashbackPlaybackWriteHeadWaits", typeof(long)),
            new("FlashbackPlaybackNearLiveSnaps", typeof(long)),
            new("FlashbackPlaybackDecodeErrorSnaps", typeof(long)),
            new("FlashbackPlaybackSubmitFailures", typeof(long)),
            new("FlashbackPlaybackLastDropUtcUnixMs", typeof(long)),
            NonNullString("FlashbackPlaybackLastDropReason"),
            new("FlashbackPlaybackLastSubmitFailureUtcUnixMs", typeof(long)),
            NonNullString("FlashbackPlaybackLastSubmitFailure"),
            new("FlashbackPlaybackLastSegmentSwitchUtcUnixMs", typeof(long)),
            new("FlashbackPlaybackLastFmp4ReopenUtcUnixMs", typeof(long)),
            new("FlashbackPlaybackLastWriteHeadWaitGapMs", typeof(long)),
            new("FlashbackPlaybackTargetFps", typeof(double)),
            new("FlashbackPlaybackObservedFps", typeof(double)),
            new("FlashbackPlaybackAvgFrameMs", typeof(double)),
            new("FlashbackPlaybackCadenceSampleCount", typeof(int)),
            new("FlashbackPlaybackP95FrameMs", typeof(double)),
            new("FlashbackPlaybackP99FrameMs", typeof(double)),
            new("FlashbackPlaybackMaxFrameMs", typeof(double)),
            new("FlashbackPlaybackSlowFrames", typeof(long)),
            new("FlashbackPlaybackSlowFramePercent", typeof(double)),
            new("FlashbackPlaybackOnePercentLowFps", typeof(double)),
            new("FlashbackPlaybackFivePercentLowFps", typeof(double)),
            new("FlashbackPlaybackSampleDurationMs", typeof(double)),
            new("FlashbackPlaybackRecentFrameIntervalsMs", typeof(double[])),
            new("FlashbackPlaybackPtsCadenceMismatchCount", typeof(long)),
            new("FlashbackPlaybackLastPtsCadenceMismatchUtcUnixMs", typeof(long)),
            new("FlashbackPlaybackLastPtsCadenceDeltaMs", typeof(double)),
            new("FlashbackPlaybackLastPtsCadenceExpectedMs", typeof(double)),
            new("FlashbackPlaybackSeekForwardDecodeCapHits", typeof(long)),
            new("FlashbackPlaybackLastSeekHitForwardDecodeCap", typeof(bool)),
            new("FlashbackPlaybackDecodeSampleCount", typeof(int)),
            new("FlashbackPlaybackDecodeAvgMs", typeof(double)),
            new("FlashbackPlaybackDecodeP95Ms", typeof(double)),
            new("FlashbackPlaybackDecodeP99Ms", typeof(double)),
            new("FlashbackPlaybackDecodeMaxMs", typeof(double)),
            NonNullString("FlashbackPlaybackMaxDecodePhase"),
            new("FlashbackPlaybackMaxDecodeReceiveMs", typeof(double)),
            new("FlashbackPlaybackMaxDecodeFeedMs", typeof(double)),
            new("FlashbackPlaybackMaxDecodeReadMs", typeof(double)),
            new("FlashbackPlaybackMaxDecodeSendMs", typeof(double)),
            new("FlashbackPlaybackMaxDecodeAudioMs", typeof(double)),
            new("FlashbackPlaybackMaxDecodeConvertMs", typeof(double)),
            new("FlashbackPlaybackMaxDecodeUtcUnixMs", typeof(long)),
            new("FlashbackPlaybackMaxDecodePositionMs", typeof(long)),
            new("FlashbackAvDriftMs", typeof(double)),
            new("FlashbackPlaybackThreadAlive", typeof(bool)),
            new("FlashbackPlaybackCommandsEnqueued", typeof(long)),
            new("FlashbackPlaybackCommandsProcessed", typeof(long)),
            new("FlashbackPlaybackCommandsDropped", typeof(long)),
            new("FlashbackPlaybackCommandsSkippedNotReady", typeof(long)),
            new("FlashbackPlaybackScrubUpdatesCoalesced", typeof(long)),
            new("FlashbackPlaybackSeekCommandsCoalesced", typeof(long)),
            new("FlashbackPlaybackCommandQueueCapacity", typeof(int)),
            new("FlashbackPlaybackPendingCommands", typeof(int)),
            new("FlashbackPlaybackMaxPendingCommands", typeof(int)),
            new("FlashbackPlaybackLastCommandQueueLatencyMs", typeof(long)),
            new("FlashbackPlaybackMaxCommandQueueLatencyMs", typeof(long)),
            NonNullString("FlashbackPlaybackMaxCommandQueueLatencyCommand"),
            NonNullString("FlashbackPlaybackLastCommandQueued"),
            NonNullString("FlashbackPlaybackLastCommandProcessed"),
            new("FlashbackPlaybackLastCommandQueuedUtcUnixMs", typeof(long)),
            new("FlashbackPlaybackLastCommandProcessedUtcUnixMs", typeof(long)),
            new("FlashbackPlaybackLastCommandFailureUtcUnixMs", typeof(long)),
            NonNullString("FlashbackPlaybackLastCommandFailure"),
            new("FlashbackExportActive", typeof(bool)),
            new("FlashbackExportId", typeof(long)),
            NonNullString("FlashbackExportStatus"),
            NonNullString("FlashbackExportOutputPath"),
            new("FlashbackExportStartedUtcUnixMs", typeof(long)),
            new("FlashbackExportLastProgressUtcUnixMs", typeof(long)),
            new("FlashbackExportCompletedUtcUnixMs", typeof(long)),
            new("FlashbackExportElapsedMs", typeof(long)),
            new("FlashbackExportLastProgressAgeMs", typeof(long)),
            new("FlashbackExportOutputBytes", typeof(long)),
            new("FlashbackExportThroughputBytesPerSec", typeof(double)),
            new("FlashbackExportSegmentsProcessed", typeof(int)),
            new("FlashbackExportTotalSegments", typeof(int)),
            new("FlashbackExportPercent", typeof(double)),
            new("FlashbackExportInPointMs", typeof(long)),
            new("FlashbackExportOutPointMs", typeof(long)),
            NonNullString("FlashbackExportMessage"),
            NonNullString("FlashbackExportFailureKind"),
            new("FlashbackExportForceRotateFallbacks", typeof(long)),
            new("FlashbackExportLastForceRotateFallbackUtcUnixMs", typeof(long)),
            new("FlashbackExportLastForceRotateFallbackSegments", typeof(int)),
            new("FlashbackExportLastForceRotateFallbackInPointMs", typeof(long)),
            new("FlashbackExportLastForceRotateFallbackOutPointMs", typeof(long)),
            NullableString("FlashbackExportVerificationFormat"),
            NullableString("FlashbackCodecDowngradeReason"),
            new("LastExportId", typeof(long)),
            NullableString("LastExportPath"),
            new("LastExportSuccess", typeof(bool?)),
            NullableString("LastExportMessage"),
            NullableString("SourceVideoFormat"),
            NullableString("SourceColorimetry"),
            NullableString("SourceQuantization"),
            NullableString("SourceHdrTransferFunction"),
            new("SourceHdrTransferCode", typeof(int?)),
            NullableString("SourceFirmware"),
            NullableString("SourceAudioFormat"),
            NullableString("SourceAudioSampleRate"),
            NullableString("SourceInputSource"),
            NullableString("SourceUsbHostProtocol"),
            NullableString("SourceHdcpMode"),
            NullableString("SourceHdcpVersion"),
            NullableString("SourceRxTxHdcpVersion"),
            NullableString("SourceRawTimingHex"),
            NonNullRef("SourceTelemetryDetails", typeof(IReadOnlyList<>).MakeGenericType(detailType), SnapshotNullability.NotNull),
            new("LastVideoEnqueueAgeMs", typeof(long)),
            new("LastVideoWriteAgeMs", typeof(long)),
            new("AvSyncCaptureDriftMs", typeof(double?)),
            new("AvSyncCaptureDriftRateMsPerSec", typeof(double?)),
            new("AvSyncEncoderDriftMs", typeof(double?)),
            new("AvSyncEncoderCorrectionSamples", typeof(long?)),
        };
    }

    private static SnapshotPropertySpec[] CaptureHealthSourceTelemetryDetailPropertySpecs()
    {
        return new SnapshotPropertySpec[]
        {
            NonNullString("Group"),
            NonNullString("Label"),
            NonNullString("DisplayValue"),
            NullableString("RawValue"),
        };
    }
}
