using System.Collections.Generic;
using Sussudio.Models;

namespace Sussudio;

public sealed record StatsSnapshot(
    int SourceCadenceSamples,
    double SourceObservedFps,
    double SourceExpectedFps,
    double SourceAvgIntervalMs,
    double SourceP95IntervalMs,
    double SourceMaxIntervalMs,
    double SourceJitterMs,
    long SourceSevereGaps,
    long SourceEstDrops,
    double SourceEstDropPct,
    int PreviewCadenceSamples,
    double PreviewObservedFps,
    double PreviewAvgIntervalMs,
    double PreviewP95IntervalMs,
    double PreviewP99IntervalMs,
    double PreviewOnePercentLowFps,
    long PreviewSlowFrames,
    double PreviewSlowPct,
    int MjpegPacketHashSamples,
    double MjpegPacketHashInputFps,
    double MjpegPacketHashUniqueFps,
    double MjpegPacketHashDuplicatePercent,
    long MjpegPacketHashLongestDuplicateRun,
    string MjpegPacketHashPattern,
    bool MjpegPacketHashLastFrameDuplicate,
    int VisualCadenceSamples,
    double VisualCadenceOutputFps,
    double VisualCadenceChangeFps,
    double VisualCadenceRepeatPercent,
    long VisualCadenceRepeatFrames,
    long VisualCadenceLongestRepeatRun,
    double VisualCadenceMotionScore,
    string VisualCadenceMotionConfidence,
    int VisualCenterCadenceSamples,
    double VisualCenterCadenceOutputFps,
    double VisualCenterCadenceChangeFps,
    double VisualCenterCadenceRepeatPercent,
    double VisualCenterCadenceMotionScore,
    string VisualCenterCadenceMotionConfidence,
    double PipelineLatencyMs,
    long SourceFramesDelivered,
    long SourceFramesDropped,
    long RendererFramesSubmitted,
    long RendererFramesRendered,
    long RendererFramesDropped,
    double PerformanceScore,
    bool Previewing,
    bool Recording,
    int PreviewNaturalWidth = 0,
    int PreviewNaturalHeight = 0,
    int? CaptureWidth = null,
    int? CaptureHeight = null,
    double? CaptureFrameRate = null,
    int? SourceWidth = null,
    int? SourceHeight = null,
    double? SourceFrameRateExact = null,
    bool? SourceIsHdr = null,
    string? SourceVideoFormat = null,
    string? SourceColorimetry = null,
    string? ReaderSourceSubtype = null,
    string? NegotiatedPixelFormat = null,
    string? TelemetryOrigin = null,
    string? TelemetryConfidence = null,
    IReadOnlyList<SourceTelemetryDetailEntry>? SourceTelemetryDetails = null,
    string? DiagnosticSummary = null,
    string? DiagnosticHealthStatus = null,
    string? DiagnosticLikelyStage = null,
    string? DiagnosticEvidence = null,
    double? AvSyncCaptureDriftMs = null,
    double? AvSyncCaptureDriftRateMsPerSec = null,
    double? AvSyncEncoderDriftMs = null,
    long? AvSyncEncoderCorrectionSamples = null,
    string? EncoderCodecName = null,
    int EncoderWidth = 0,
    int EncoderHeight = 0,
    double EncoderFrameRate = 0,
    uint EncoderTargetBitRate = 0,
    IReadOnlyList<double>? MjpegPacketHashRecentUniqueIntervalsMs = null,
    IReadOnlyList<double>? VisualCadenceRecentChangeIntervalsMs = null,
    IReadOnlyList<double>? VisualCenterCadenceRecentChangeIntervalsMs = null,
    IReadOnlyList<double>? PreviewRecentPresentIntervalsMs = null,
    IReadOnlyList<double>? PreviewRecentLatencyMs = null);
