namespace Sussudio.Services.Telemetry;

public sealed partial class NativeXuAtCommandProvider
{
    private readonly record struct NativeXuSnapshotCommandResults(
        AtCommandResult Vic,
        AtCommandResult Vfreq,
        AtCommandResult AviInfo,
        AtCommandResult HdrMetadata,
        AtCommandResult SystemInfo,
        AtCommandResult Hdr2Sdr,
        AtCommandResult AudioFormat,
        AtCommandResult AudioSamplingRate,
        AtCommandResult InputSource,
        AtCommandResult FlashAudio,
        AtCommandResult AdcOnOff,
        AtCommandResult AdcVolumeGain,
        AtCommandResult UacVolumeGain,
        AtCommandResult UacOut1Mute,
        AtCommandResult UacOut2Mute,
        AtCommandResult UacOut2MixerSource,
        AtCommandResult UsbHostProtocol,
        AtCommandResult UsbCdc,
        AtCommandResult UsbLinkState,
        AtCommandResult UsbForceSpeed,
        AtCommandResult TxHpd,
        AtCommandResult TxVrr,
        AtCommandResult TxEdidValid,
        AtCommandResult UvcOutputTiming,
        AtCommandResult UvcVideoFormat,
        AtCommandResult UvcErrStatus,
        AtCommandResult HdcpMode,
        AtCommandResult HdcpVersion,
        AtCommandResult RxTxHdcpVersion,
        AtCommandResult Hdr2SdrExtended,
        AtCommandResult CustomerVersion,
        AtCommandResult RescueVersion,
        AtCommandResult Hdr2SdrColorParam,
        AtCommandResult ColorRangeSetting,
        AtCommandResult Vtem,
        AtCommandResult BitError,
        AtCommandResult RawTiming);
}
