using System;
using Sussudio.Models;

namespace Sussudio.Controllers;

internal static class PreviewRuntimeSnapshotController
{
    public static PreviewRuntimeSnapshot Build(PreviewRuntimeSnapshotInput input)
    {
        var d3dProjection = PreviewRuntimeD3DProjection.Build(input);
        var health = PreviewRuntimeSnapshotHealthPolicy.Evaluate(new PreviewRuntimeSnapshotHealthInput
        {
            IsPreviewing = input.IsPreviewing,
            IsStartupWaitingForFirstVisual = input.IsStartupWaitingForFirstVisual,
            StartupRequestedUtc = input.StartupRequestedUtc,
            StartupTimeoutMs = input.StartupTimeoutMs,
            RendererAttached = d3dProjection.RendererAttached,
            GpuActive = d3dProjection.GpuActive,
            FramesArrived = d3dProjection.FramesArrived,
            FramesDisplayed = d3dProjection.FramesDisplayed,
            LastPresentedTick = input.LastPresentedTick,
            CurrentTick = Environment.TickCount64,
            UtcNow = DateTimeOffset.UtcNow
        });

        return new PreviewRuntimeSnapshot
        {
            TimestampUtc = DateTimeOffset.UtcNow,
            IsPreviewing = input.IsPreviewing,
            GpuActive = d3dProjection.GpuActive,
            PlaceholderVisible = input.PlaceholderVisible,
            GpuElementVisible = input.GpuElementVisible,
            CpuElementVisible = input.CpuElementVisible,
            RendererAttached = d3dProjection.RendererAttached,
            StartupState = input.StartupState,
            StartupAttemptId = input.StartupAttemptId,
            StartupElapsedMs = health.StartupElapsedMs,
            StartupTimeoutMs = input.StartupTimeoutMs,
            StartupGpuSignalMediaOpened = input.StartupGpuSignalMediaOpened,
            StartupGpuSignalFirstFrame = input.StartupGpuSignalFirstFrame,
            StartupGpuSignalPlaybackAdvancing = input.StartupGpuSignalPlaybackAdvancing,
            StartupRequiredSignals = input.StartupRequiredSignals,
            StartupReceivedSignals = input.StartupReceivedSignals,
            StartupStrategy = input.StartupStrategy,
            StartupMissingSignals = input.StartupMissingSignals,
            StartupRecoveryAttemptCount = input.StartupRecoveryAttemptCount,
            StartupLastFailureReason = input.StartupLastFailureReason,
            FirstVisualConfirmed = input.FirstVisualConfirmed,
            FramesArrived = d3dProjection.FramesArrived,
            FramesDisplayed = d3dProjection.FramesDisplayed,
            FramesDropped = d3dProjection.FramesDropped,
            DisplayCadenceSampleCount = d3dProjection.DisplayCadenceSampleCount,
            DisplayCadenceObservedFps = d3dProjection.DisplayCadenceObservedFps,
            DisplayCadenceExpectedIntervalMs = d3dProjection.DisplayCadenceExpectedIntervalMs,
            DisplayCadenceAverageIntervalMs = d3dProjection.DisplayCadenceAverageIntervalMs,
            DisplayCadenceP95IntervalMs = d3dProjection.DisplayCadenceP95IntervalMs,
            DisplayCadenceP99IntervalMs = d3dProjection.DisplayCadenceP99IntervalMs,
            DisplayCadenceMaxIntervalMs = d3dProjection.DisplayCadenceMaxIntervalMs,
            DisplayCadenceOnePercentLowFps = d3dProjection.DisplayCadenceOnePercentLowFps,
            DisplayCadenceFivePercentLowFps = d3dProjection.DisplayCadenceFivePercentLowFps,
            DisplayCadenceSampleDurationMs = d3dProjection.DisplayCadenceSampleDurationMs,
            DisplayCadenceRecentIntervalsMs = d3dProjection.DisplayCadenceRecentIntervalsMs,
            DisplayCadenceJitterStdDevMs = d3dProjection.DisplayCadenceJitterStdDevMs,
            DisplayCadenceSlowFrameCount = d3dProjection.DisplayCadenceSlowFrameCount,
            DisplayCadenceSlowFramePercent = d3dProjection.DisplayCadenceSlowFramePercent,
            BlankSuspected = health.BlankSuspected,
            StallSuspected = health.StallSuspected,
            RendererMode = d3dProjection.RendererMode,
            D3DPresentSyncInterval = d3dProjection.D3DPresentSyncInterval,
            D3DMaxFrameLatency = d3dProjection.D3DMaxFrameLatency,
            D3DSwapChainBufferCount = d3dProjection.D3DSwapChainBufferCount,
            D3DSwapChainAddress = d3dProjection.D3DSwapChainAddress,
            D3DFramesSubmitted = d3dProjection.D3DFramesSubmitted,
            D3DFramesRendered = d3dProjection.D3DFramesRendered,
            D3DFramesDropped = d3dProjection.D3DFramesDropped,
            D3DRenderThreadFailureCount = d3dProjection.D3DRenderThreadFailureCount,
            D3DLastRenderThreadFailureType = d3dProjection.D3DLastRenderThreadFailureType,
            D3DLastRenderThreadFailureMessage = d3dProjection.D3DLastRenderThreadFailureMessage,
            D3DLastRenderThreadFailureHResult = d3dProjection.D3DLastRenderThreadFailureHResult,
            D3DPendingFrameCount = d3dProjection.D3DPendingFrameCount,
            D3DInputColorSpace = d3dProjection.D3DInputColorSpace,
            D3DOutputColorSpace = d3dProjection.D3DOutputColorSpace,
            D3DCpuTimingSampleCount = d3dProjection.D3DCpuTimingSampleCount,
            D3DInputUploadCpuAvgMs = d3dProjection.D3DInputUploadCpuAvgMs,
            D3DInputUploadCpuP95Ms = d3dProjection.D3DInputUploadCpuP95Ms,
            D3DInputUploadCpuP99Ms = d3dProjection.D3DInputUploadCpuP99Ms,
            D3DInputUploadCpuMaxMs = d3dProjection.D3DInputUploadCpuMaxMs,
            D3DRenderSubmitCpuAvgMs = d3dProjection.D3DRenderSubmitCpuAvgMs,
            D3DRenderSubmitCpuP95Ms = d3dProjection.D3DRenderSubmitCpuP95Ms,
            D3DRenderSubmitCpuP99Ms = d3dProjection.D3DRenderSubmitCpuP99Ms,
            D3DRenderSubmitCpuMaxMs = d3dProjection.D3DRenderSubmitCpuMaxMs,
            D3DPresentCallAvgMs = d3dProjection.D3DPresentCallAvgMs,
            D3DPresentCallP95Ms = d3dProjection.D3DPresentCallP95Ms,
            D3DPresentCallP99Ms = d3dProjection.D3DPresentCallP99Ms,
            D3DPresentCallMaxMs = d3dProjection.D3DPresentCallMaxMs,
            D3DTotalFrameCpuAvgMs = d3dProjection.D3DTotalFrameCpuAvgMs,
            D3DTotalFrameCpuP95Ms = d3dProjection.D3DTotalFrameCpuP95Ms,
            D3DTotalFrameCpuP99Ms = d3dProjection.D3DTotalFrameCpuP99Ms,
            D3DTotalFrameCpuMaxMs = d3dProjection.D3DTotalFrameCpuMaxMs,
            D3DPipelineLatencySampleCount = d3dProjection.D3DPipelineLatencySampleCount,
            D3DPipelineLatencyAvgMs = d3dProjection.D3DPipelineLatencyAvgMs,
            D3DPipelineLatencyP95Ms = d3dProjection.D3DPipelineLatencyP95Ms,
            D3DPipelineLatencyP99Ms = d3dProjection.D3DPipelineLatencyP99Ms,
            D3DPipelineLatencyMaxMs = d3dProjection.D3DPipelineLatencyMaxMs,
            D3DFrameLatencyWaitEnabled = d3dProjection.D3DFrameLatencyWaitEnabled,
            D3DFrameLatencyWaitHandleActive = d3dProjection.D3DFrameLatencyWaitHandleActive,
            D3DFrameLatencyWaitCallCount = d3dProjection.D3DFrameLatencyWaitCallCount,
            D3DFrameLatencyWaitSignaledCount = d3dProjection.D3DFrameLatencyWaitSignaledCount,
            D3DFrameLatencyWaitTimeoutCount = d3dProjection.D3DFrameLatencyWaitTimeoutCount,
            D3DFrameLatencyWaitUnexpectedResultCount = d3dProjection.D3DFrameLatencyWaitUnexpectedResultCount,
            D3DFrameLatencyWaitLastResult = d3dProjection.D3DFrameLatencyWaitLastResult,
            D3DFrameLatencyWaitLastMs = d3dProjection.D3DFrameLatencyWaitLastMs,
            D3DFrameLatencyWaitSampleCount = d3dProjection.D3DFrameLatencyWaitSampleCount,
            D3DFrameLatencyWaitAvgMs = d3dProjection.D3DFrameLatencyWaitAvgMs,
            D3DFrameLatencyWaitP95Ms = d3dProjection.D3DFrameLatencyWaitP95Ms,
            D3DFrameLatencyWaitP99Ms = d3dProjection.D3DFrameLatencyWaitP99Ms,
            D3DFrameLatencyWaitMaxMs = d3dProjection.D3DFrameLatencyWaitMaxMs,
            D3DFrameStatsSampleCount = d3dProjection.D3DFrameStatsSampleCount,
            D3DFrameStatsSuccessCount = d3dProjection.D3DFrameStatsSuccessCount,
            D3DFrameStatsFailureCount = d3dProjection.D3DFrameStatsFailureCount,
            D3DFrameStatsLastError = d3dProjection.D3DFrameStatsLastError,
            D3DFrameStatsPresentCount = d3dProjection.D3DFrameStatsPresentCount,
            D3DFrameStatsPresentRefreshCount = d3dProjection.D3DFrameStatsPresentRefreshCount,
            D3DFrameStatsSyncRefreshCount = d3dProjection.D3DFrameStatsSyncRefreshCount,
            D3DFrameStatsSyncQpcTime = d3dProjection.D3DFrameStatsSyncQpcTime,
            D3DFrameStatsLastPresentDelta = d3dProjection.D3DFrameStatsLastPresentDelta,
            D3DFrameStatsLastPresentRefreshDelta = d3dProjection.D3DFrameStatsLastPresentRefreshDelta,
            D3DFrameStatsLastSyncRefreshDelta = d3dProjection.D3DFrameStatsLastSyncRefreshDelta,
            D3DFrameStatsMissedRefreshCount = d3dProjection.D3DFrameStatsMissedRefreshCount,
            D3DLastSubmittedPreviewPresentId = d3dProjection.D3DLastSubmittedPreviewPresentId,
            D3DLastSubmittedSourceSequenceNumber = d3dProjection.D3DLastSubmittedSourceSequenceNumber,
            D3DLastSubmittedSourcePtsTicks = d3dProjection.D3DLastSubmittedSourcePtsTicks,
            D3DLastSubmittedQpc = d3dProjection.D3DLastSubmittedQpc,
            D3DLastSubmittedUtcUnixMs = d3dProjection.D3DLastSubmittedUtcUnixMs,
            D3DLastRenderedPreviewPresentId = d3dProjection.D3DLastRenderedPreviewPresentId,
            D3DLastRenderedSourceSequenceNumber = d3dProjection.D3DLastRenderedSourceSequenceNumber,
            D3DLastRenderedSourcePtsTicks = d3dProjection.D3DLastRenderedSourcePtsTicks,
            D3DLastRenderedQpc = d3dProjection.D3DLastRenderedQpc,
            D3DLastRenderedUtcUnixMs = d3dProjection.D3DLastRenderedUtcUnixMs,
            D3DLastRenderedSchedulerToPresentMs = d3dProjection.D3DLastRenderedSchedulerToPresentMs,
            D3DLastRenderedPipelineLatencyMs = d3dProjection.D3DLastRenderedPipelineLatencyMs,
            D3DLastDroppedPreviewPresentId = d3dProjection.D3DLastDroppedPreviewPresentId,
            D3DLastDroppedSourceSequenceNumber = d3dProjection.D3DLastDroppedSourceSequenceNumber,
            D3DLastDroppedSourcePtsTicks = d3dProjection.D3DLastDroppedSourcePtsTicks,
            D3DLastDroppedQpc = d3dProjection.D3DLastDroppedQpc,
            D3DLastDroppedUtcUnixMs = d3dProjection.D3DLastDroppedUtcUnixMs,
            D3DLastDropReason = d3dProjection.D3DLastDropReason,
            D3DRecentSlowFrames = d3dProjection.D3DRecentSlowFrames,
            EstimatedPipelineLatencyMs = d3dProjection.EstimatedPipelineLatencyMs,
            GpuPlaybackState = d3dProjection.GpuPlaybackState,
            GpuNaturalVideoWidth = d3dProjection.GpuNaturalVideoWidth,
            GpuNaturalVideoHeight = d3dProjection.GpuNaturalVideoHeight,
            GpuPositionMs = d3dProjection.GpuPositionMs,
            GpuPositionEventCount = input.GpuPositionEventCount
        };
    }
}
